.travis.yml, src/RadioGroup.js, test/RadioGroupSpec.js
Fix: https://github.com/rsuite/rsuite/issues/48#issuecomment-392290392
=> Fix event is not defined in the RadioGroup's onChange

.travis.yml, styles/less/modals.less, styles/less/picker.less
=> Fix:Full Modal size not working

src/AutoComplete.js, test/AutoCompleteSpec.js
update code according to https://github.com/rsuite/rsuite/commit/6d296d5b416b8594916c7f5eb0c1bf53037e8145#r29242338
=> chore(AutoComplete): correct code and tests

src/Slider.js, styles/core.less, styles/form.less, styles/picker.less, styles/rsuite.less, styles/slider.less
1. Make sure slider tooltips correct show
2. Show help-block icon.
3. Resolve error import.
=> Fix some style problems

styles/picker.less
=> update: Unity picker style when select values.

styles/button-group.less
=> bugfixed: Button is missing border-radius in ButtonGroup

styles/date-picker.less, styles/mixins/button.less, styles/nav.less, styles/panel.less, styles/progress.less, styles/sidebar.less, styles/slider.less, styles/table.less, styles/toggle.less, styles/utilities.less, styles/variables.less
Replace `transition-*` to `transition` for compatibility with the post-css autoprefixer.
=> Compatibility with the post-css autoprefixer.

styles/tree-picker.less
=> bugfixed: Tree will show scrollbar.

src/DatePicker/DatePicker.js, test/DatePicker/DatePickerSpec.js
fixed: https://github.com/rsuite/rsuite/issues/171
=> Bugfix: An error occurred in the `null` value when it was controlled

styles/auto-complete.less, styles/check-picker.less, styles/select-picker.less
Remove minimum with limit for menu of <SelectPicker/>,<CheckPicker/> and <AutoComplete/> component.
Make sure the style is more friendly when the search is not available.
=> Remove minimum with limit for menu of picker menu.

styles/variables.less
Change <Modal/> backdrop and <Drawer/> backdrop zindex the same with these content.
=> update:Change <Modal/> backdrop and <Drawer/> backdrop zindex .

scripts/generate-styles.js, styles/core.less, styles/rsuite.less
Move `icon.less` to `core.less`.
=> bugfixed:Resolve the problem that icon exception when modularity.

src/Form.js, src/FormControl.js
=> form control组件从form context中获取当前错误信息

types/index.d.ts
https://github.com/rsuite/rsuite/issues/248
=> Fix ts type check error

styles/font-awesome.less
Reference: https://github.com/FortAwesome/Font-Awesome/issues/14223
=> Bugfix: Fixed the problem that property `fixedWith` of `<Icon/>` is invalid.

package.json, src/Modal.js
issue: https://github.com/rsuite/rsuite/issues/256
=> Bugfix: The height of `body` should be reset when the content in `<Modal>`  is updated

src/Modal.js
Fix: https://github.com/rsuite/rsuite/issues/272
=> Bugfix: The Drawer will trigger onHide when clicking inside the Drawer

styles/drawer.less, styles/form.less, styles/input-picker.less, styles/picker.less, styles/tag-picker.less
1.  Fixed the problem that drawer without backdrop but page unclickable.
2.  Fixed the problem that hover effect when mouse hover on  disabled picker toggle.
3.  Fixed issue where cursor is not disabled when disabled tag picker.
4.  Remove radio label & checkbox label line-height unit.
=> Fix some  style issues.

src/_picker/MenuWrapper.js, test/Cascader/DropdownSpec.js, test/CheckPickerSpec.js, test/InputPicker/DropdownSpec.js, test/MultiCascader/DropdownSpec.js, test/SelectPickerSpec.js, test/TagPicker/TagPickerSpec.js
https://github.com/rsuite/rsuite/issues/328
=> Fixed `<CheckPicker>` setting `toggleComponentClass` which will cause an error

styles/form.less
=> Fixed issues of form inline layout.

package-lock.json, package.json, styles/table.less, styles/variables.less
Close: https://github.com/rsuite/rsuite/issues/330
=> Support fixed column to the right  on `<Table>`

src/CheckboxGroup.js, styles/checkbox.less, styles/form.less, styles/radio.less
Fix: https://github.com/rsuite/rsuite/issues/347
=>  RadioGroup/CheckboxGroup supported mutiple line when setting inline.

package-lock.json, package.json, styles/mixins/utilities.less, styles/table.less
Fix: https://github.com/rsuite/rsuite/issues/363
=> Support `virtualized` on `<Table>`, effectively render large tabular data

styles/mixins/hacks.less
=> Fixed issues that cannot display text after a quick click in the sidenav menu.

package-lock.json, src/CheckboxGroup.js, src/RadioGroup.js, test/CheckboxGroupSpec.js, test/RadioGroupSpec.js
=>  Fix an issue where the onChange event is overridden in the Group

src/DropdownMenu.js, src/DropdownMenuItem.js, styles/dropdown.less, styles/mixins/sidenav.less, styles/sidenav.less, styles/variables.less
1. Fix issues that can't use icon in `<DropDownMenu/>` title props.
2. Supported ` [icon]` in `<Sidenav/>`  use `<DropdownMenu/>`.
=> Update and bugfixed some <Dropdown/> styles.

src/Notification.js, styles/notification.less
Resolve an issue where the title is too long to be processed when the notification has an icon.
=> Resolve notification styles issues.

package-lock.json, package.json
Fix: https://github.com/rsuite/rsuite/issues/234
=> Fixed a passively triggered onScroll event on Table that caused the scrollbar to be misaligned

src/TagGroup.js, src/index.js, styles/tag.less, test/TagGroupSpec.js, test/TagSpec.js, types/TagGroup.d.ts, types/index.d.ts
```
<TagGroup>
<Tag>name</Tag>
<Tag>name</Tag>
</TagGroup>
```
=> Add TagGroup

README_zh.md
=> modify a invalid link

scripts/generate-styles.js
=> Fixed modular styles issues for animation.

types/index.d.ts
=> Fixed Typescript incorrectly extends interface (#428)

src/DatePicker/DatePicker.js, src/DateRangePicker/DateRangePicker.js, test/DatePicker/DatePickerSpec.js, test/DateRangePicker/DateRangePickerSpec.js, types/DatePicker.d.ts, types/DateRangePicker.d.ts
https://github.com/rsuite/rsuite/issues/434
=> Support `renderValue` on <DatePicker> and <DateRangePicker>

package.json, scripts/gulpfile.js
=> Update *.d.ts file directory for import on demand

types/RadioGroup.d.ts
=> supplement: value type error

scripts/gulpfile.js
=> Fix path separator for windows users.

src/Uploader.js
=> Fix uploader reset button will trigger automatic upload

src/CheckTreePicker/CheckTreePicker.tsx, src/TreePicker/TreePicker.tsx
Fix TreePicker, CheckTreePicker layer not correct when using virtualized
=> Fix TreePicker, CheckTreePicker layer not correct

src/AutoComplete/test/AutoCompleteSpec.js, src/CheckPicker/test/CheckPickerSpec.js, src/Checkbox/Checkbox.tsx, src/Checkbox/styles/common.less, src/Checkbox/test/CheckboxSpec.js, src/DatePicker/test/DatePickerSpec.js, src/InputNumber/InputNumber.tsx, src/InputNumber/test/InputNumberSpec.js, src/InputPicker/InputPicker.tsx, src/InputPicker/test/InputPickerSpec.js, src/Picker/PickerToggle.tsx, src/Picker/test/PickerToggleSpec.js, src/Radio/Radio.tsx, src/Radio/styles/common.less, src/Radio/test/RadioSpec.js, src/SelectPicker/test/SelectPickerSpec.js
Fix
https://github.com/rsuite/rsuite/issues/559
=>  Add events for `onBlur` and `onFocus` on form controls

src/Progress/ProgressLine.tsx
=> Fix `strokeWidth` cannot change background height

styles/loader.less, styles/variables.less
It is followed rsuite@4 . And it fixed some compatibility issue.
=> Update loader styles replace table layout to flex.

src/Calendar/MonthDropdown.tsx, src/Calendar/test/CalendarMonthDropdownSpec.js
https://github.com/rsuite/rsuite/issues/592
=> Fix disabled month issue

src/List/AutoScroller.ts, src/List/List.tsx, src/List/ListItem.tsx, src/List/utils.ts
=> Fix collection issue for List. #603

src/DateRangePicker/DateRangePicker.d.ts, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.js, src/DateRangePicker/utils.ts
https://github.com/rsuite/rsuite/issues/590
=> Support `defaultCalendarValue` on `<DateRangePicker>`

package-lock.json, package.json
https://github.com/rsuite/dom-lib/issues/3
=> Fix ESM compilation error

src/Alert/Alert.d.ts, src/Notification/Notification.d.ts
Added missed type definitions for Notifications and Alert
=> Missed type definitions for Notification and Alert

src/Slider/Slider.tsx
Fix: https://github.com/rsuite/rsuite/issues/659
=> Fix the precision of floating point arithmetic in Slider

.babelrc.js, package.json
Fix: https://github.com/rsuite/rsuite/issues/672
=> Add the babel plugin for `lodash` and `date-fns`

src/Dropdown/styles/common.less
Make sure dropdown vertical alignment with button,button group and so on.
=> Fix: Make sure dropdown vertical alignment with button,button group.

src/utils/defaultProps.ts
Fix: https://github.com/rsuite/rsuite/issues/691
=> Fix the problem that  can't extends in the ie10 browser

package.json
Fix: https://github.com/rsuite/rsuite/issues/700
Fix: https://github.com/rsuite/rsuite/issues/704
=> Fix sideEffects configuration

src/Uploader/Uploader.d.ts, src/Uploader/Uploader.tsx, src/Uploader/test/UploaderSpec.js, src/Uploader/utils.ts
Resolved:
https://github.com/rsuite/rsuite/issues/673
https://github.com/rsuite/rsuite/issues/689
=> Added for `fileListVisible` on `<Uploader>`

src/Calendar/TableRow.tsx
Fix: https://github.com/rsuite/rsuite/issues/654
=> Fix DatePicker format issue

src/Carousel/Carousel.tsx, src/Carousel/index.tsx, src/Carousel/styles/common.less
Ensures correct Carousel behavior in RTL mode.
=> Fixes #730

src/DateRangePicker/styles/common.less
=> Fixed <DateRangePicker> panel collapse issue.

src/Drawer/styles/common.less, src/Modal/Modal.tsx, src/styles/keyframes.less, src/utils/directionUtil.ts, src/utils/index.ts
This PR depends on https://github.com/rsuite/rsuite.github.io/pull/161
=> Fixes #727

src/InputPicker/styles/common.less, src/InputPicker/test/InputPickerStylesSpec.js
=> Fixed <InputPicker> background color issue.

src/Calendar/MonthDropdown.tsx, src/Calendar/test/CalendarMonthDropdownSpec.js, src/Calendar/test/CalendarStyleSpec.js, src/DateRangePicker/test/DatePickerSpec.js
=> Improved the speed at which DateRangePicker opens

src/Tooltip/Tooltip.tsx, src/Tooltip/test/TooltipSpec.js
=> Revert "Added rest props to <Tooltip>"

src/Placeholder/PlaceholderParagraph.d.ts, src/Placeholder/PlaceholderParagraph.tsx, src/Placeholder/styles/common.less, src/Placeholder/test/PlaceholderParagraphSpec.js, src/styles/themes/dark/variables.less, src/styles/themes/default/variables.less, src/styles/variables.less
https://github.com/rsuite/rsuite/issues/737
=> Added option `image` to the `graph` property of Placeholder

src/Cascader/Cascader.d.ts, src/Cascader/Cascader.tsx, src/Cascader/DropdownMenu.tsx, src/Cascader/test/CascaderSpec.js, src/MultiCascader/DropdownMenu.tsx, src/MultiCascader/MultiCascader.d.ts, src/MultiCascader/MultiCascader.tsx, src/Picker/DropdownMenu.tsx
https://github.com/rsuite/rsuite/issues/751
=> Added support for `parentSelectable` on `<Cascader>`

src/CheckTreePicker/CheckTreePicker.tsx, src/TreePicker/TreePicker.tsx
- change width does't work when setting virtualized prop
- children node does't display when loading data asynchronously
=> Fix CheckTreePicker and TreePicker Bug

src/InputGroup/styles/common.less
=> Ensure correct height for input group button

src/Toggle/styles/common.less, src/Toggle/styles/mixin.less, src/styles/variables.less
Ensures text/icon sizes to be relative to toggle size.
=> Fix toggle text/icon font size

src/Picker/styles/mixin.less
=> Fix vertical alignment of xs datepicker icon

src/utils/prefix.ts
=> Fixed "script-src" content security policy (CSP) failure

src/Slider/Graduated.tsx, src/Slider/test/SliderSpec.js
=> Fix mark cannot be customized rendering in `Slider` correctly

docs/components/TopLevelNav/TopLevelNav.tsx, docs/pages/_app.tsx, docs/utils/themeHelpers.ts
1. Auto change theme color when toggle system dark/light mode.
2. Fixed the issue that change theme to dark , `<TopLevelNav/>` icon is not match.
=> Auto change theme and resolve theme load issue.

docs/pages/components/navbar/appearance.md, docs/pages/components/navbar/basic.md, docs/pages/components/navbar/en/appearance.md, docs/pages/components/navbar/en/basic.md
=> Supplement syles for navbar docs.

docs/components/AppContext.tsx, docs/locales/index.ts
=> Add declare to dict and messages.

docs/pages/_app.tsx, docs/pages/styles.less
=> Revert "Added mourning theme to doc site"

docs/components/Logo/Logo.tsx
=> Revert "docs: Gray rsuite logos on 2020/4/4"

src/Calendar/Calendar.tsx, src/CheckTreePicker/CheckTreeNode.tsx, src/Checkbox/Checkbox.tsx, src/Input/Input.tsx, src/InputPicker/InputSearch.tsx, src/Modal/ModalDialog.tsx, src/Radio/Radio.tsx, src/TreePicker/TreeNode.tsx, src/Whisper/Whisper.tsx, src/utils/index.ts, src/utils/refType.ts, src/utils/withStyleProps.tsx
Fix: https://github.com/rsuite/rsuite/issues/926
=> Fix incorrect PropTypes definition

src/styles/variables.less
=> Revert "Modify @btn-link-color equal to @link-color."

docs/package.json
=> Added name and color to concurrently task.

docs/pages/guide/intl/en/index.md, docs/pages/guide/intl/index.md, src/IntlProvider/locales/index.d.ts, src/IntlProvider/locales/index.ts, src/IntlProvider/locales/it_IT.d.ts, src/IntlProvider/locales/it_IT.ts
Hello,
Thanks for this nice library.
Here there is a proposal for Italian Localization, tell me if you think I've missed somethig.
=> Italian localization

src/Dropdown/DropdownMenu.tsx, src/Sidenav/test/SidenavSpec.js
Fix: https://github.com/rsuite/rsuite/issues/1006
=> fix(DropdownMenu): Fix the expanded state of the menu

src/Picker/DefaultToggleButton.tsx, src/Picker/PickerToggle.tsx, src/Picker/test/PickerToggleSpec.js
Reference [Click event on child inside button not firing in IE
](https://stackoverflow.com/questions/43769412/click-event-on-child-inside-button-not-firing-in-ie?noredirect=1&lq=1)
=> Fixed #1014

src/Carousel/Carousel.d.ts, src/Carousel/Carousel.tsx, src/Carousel/test/CarouselSpec.js, src/Carousel/test/CarouselStylesSpec.js, src/utils/ReactChildren.tsx
=> Fixed Carousel unable to render invalid children

package-lock.json, src/Notification/NoticeManager.tsx
Fix for [#1046](https://github.com/rsuite/rsuite/issues/1046)
=> Notification - Fix #1046

src/Loader/styles/mixin.less
Fix for [#1058](https://github.com/rsuite/rsuite/issues/1058)
=> Loader - Fix #1058

.huskyrc, commitlint.config.js, package-lock.json, package.json
Using [commintlint](https://github.com/conventional-changelog/commitlint) and [husky](https://github.com/typicode/husky) lint commit message.
=> chore(commitlint):  lint commit message

docs/pages/components/dropdown/basic.md, docs/pages/components/dropdown/en/size.md, docs/pages/components/dropdown/index.tsx, docs/pages/components/dropdown/size.md, package.json, src/Button/styles/mixin.less, src/Dropdown/styles/common.less, src/Dropdown/styles/mixin.less, src/Form/styles/mixin.less, src/Picker/styles/mixin.less, src/TreePicker/styles/common.less, src/styles/mixins/palette.less, src/styles/mixins/tiny-color.less, src/styles/normalize.less
=> fix(dropdown): fix incorrect Dropdown caret position

src/ButtonGroup/ButtonGroup.tsx, src/ButtonGroup/test/ButtonGroupSpec.js
=> fix(buttongroup): fixed Button componentClass not work with ButtonGroup

src/Dropdown/Dropdown.d.ts, src/Dropdown/Dropdown.tsx, src/Nav/Nav.tsx, src/Nav/NavItem.tsx, src/Whisper/index.tsx, src/utils/appendTooltip.tsx
Fixed an issue where Dropdown did not display Tooltip when sidenav collapsed
fix #1084
=> fix(sidenav): fixed display issue when sidenav was collapsed

src/InputNumber/InputNumber.tsx, src/InputNumber/test/InputNumberSpec.js
fix: https://github.com/rsuite/rsuite/issues/1093
=> fix(inputpicker): fix InputNumber will not trigger onChange when input

docs/pages/components/steps/description.md, docs/pages/components/steps/en/description.md, src/Steps/StepItem.tsx, src/Steps/styles/common.less
=> fix(steps): fixed the description of <Steps> will break layout

src/DateRangePicker/DateRangePicker.d.ts, src/TreePicker/TreePicker.d.ts
=> fix(ts): fix errors in Typescript

src/DateRangePicker/Calendar/Calendar.tsx
=> #1117 - ShowOneCalendar disabled Months after date

.babelrc.js, package-lock.json, package.json, src/Carousel/Carousel.tsx, src/Carousel/styles/common.less, src/styles/keyframes.less, src/styles/variables.less
- fix: animation in `rtl` and `placement=left` or `placement=right`
- `autoplay` can be interrupted now.
- fix some error when changing children node . fix: #1107
=> fix: autoplay can now be interrupted in Carousel

docs/utils/component.config.json, src/Dropdown/Dropdown.d.ts, src/Dropdown/Dropdown.tsx, src/Dropdown/styles/common.less, src/Nav/Nav.tsx
Dropdown displays the header in Sidenav.
=> fix(dropdown): fixed an issue where the menu and tooltip overlapped

docs/babel.config.js, docs/package-lock.json, docs/package.json, src/@types/common.d.ts, src/Animation/Transition.tsx, src/Animation/propTypes.ts, src/AutoComplete/AutoComplete.d.ts, src/AutoComplete/AutoComplete.tsx, src/Cascader/Cascader.tsx, src/CheckPicker/CheckPicker.tsx, src/CheckTreePicker/CheckTreePicker.tsx, src/DatePicker/DatePicker.tsx, src/DateRangePicker/DateRangePicker.tsx, src/InputPicker/InputPicker.tsx, src/MultiCascader/MultiCascader.tsx, src/Overlay/Overlay.tsx, src/Overlay/OverlayTrigger.d.ts, src/Picker/PickerToggleTrigger.tsx, src/Picker/propTypes.ts, src/SelectPicker/SelectPicker.tsx, src/TreePicker/TreePicker.tsx, src/utils/index.ts
Fix: https://github.com/rsuite/rsuite/issues/1145
```jsx
const positionRef = React.createRef();
window.addEventListener('resize', () => {
positionRef.current?.updatePosition?.();
});
return (
<DateRangePicker positionRef={positionRef} placement="bottomEnd" />
);
```
=> feat(pickers): support `positionRef` on pickers

docs/pages/components/input-number/en-US/index.md, docs/pages/components/input-number/zh-CN/index.md, src/InputNumber/InputNumber.d.ts, src/InputNumber/InputNumber.tsx
=> feat(inputnumber): support `scrollable` on `<InputNumber>`

src/InputGroup/styles/common.less
Fixed an issue where the InputGroup and FormControl were used in combination
=> fix(inputgroup): fix a formControl use issue

src/InputGroup/styles/common.less
Fix an issue where FormControl haven't show error message in InputGroup.
=> fix(inputgroup): fix a styles issue for InputGroup component

src/Modal/Modal.tsx
=> fix(modal): fixed the issue of height reduction when reopening Modal

src/Overlay/OverlayTrigger.tsx
=> fix(overlaytrigger): fix Whisper delay not working

docs/client/polyfills.ts
=> docs: fix IE11 compatibility issue

docs/pages/components/input-number/en-US/fix.md, docs/pages/components/input-number/index.tsx, docs/pages/components/input-number/styles.less, docs/pages/components/input-number/zh-CN/fix.md, docs/pages/styles.less
=> docs: 添加InputNumber示列

docs/pages/components/check-tree-picker/zh-CN/index.md
=> docs(checktreepicker): fix typos

docs/pages/components/affix/zh-CN/index.md
=> docs: fix typos

docs/pages/components/tree/en-US/index.md, docs/pages/components/tree/zh-CN/index.md, src/Tree/Tree.d.ts, src/Tree/TreeDrag.d.ts, src/TreePicker/TreePicker.d.ts
1. Tree.d.ts add Drag and Drop types.
2. Tree component update english doc.
=> docs(tree): update Tree.d.ts and Tree Docs

docs/pages/components/rate/en-US/character.md, docs/pages/components/rate/zh-CN/character.md
(cherry picked from commit f98a8d01ce4dcc8424ffba9f0597410c481e4e60)
=> fix(Rate):  fix typos in docs

docs/pages/components/input/en-US/index.md, docs/pages/components/input/zh-CN/index.md
See https://github.com/rsuite/rsuite/issues/1242.
=> docs(input): fix type of value and defaultValue (#1242)

docs/pages/components/tag-picker/en-US/custom.md, docs/pages/components/tag-picker/index.tsx, docs/pages/components/tag-picker/zh-CN/custom.md
https://github.com/rsuite/rsuite/issues/1238
=> docs(tag-picker): update custom tag for TagPicker

docs/pages/components/button/en-US/disabled.md, docs/pages/components/button/zh-CN/disabled.md, src/Button/Button.tsx, src/Button/test/ButtonSpec.js
=> fix(button): fixed that the disabled button did not disable href

src/AutoComplete/AutoComplete.tsx, src/Avatar/Avatar.tsx, src/Breadcrumb/Breadcrumb.tsx, src/Button/Button.tsx, src/ButtonGroup/ButtonGroup.tsx, src/Drawer/index.tsx, src/Dropdown/Dropdown.tsx, src/FlexboxGrid/FlexboxGrid.tsx, src/FormGroup/FormGroup.tsx, src/Input/Input.tsx, src/InputGroup/InputGroup.tsx, src/List/List.tsx, src/Loader/Loader.tsx, src/Modal/Modal.tsx, src/Modal/ModalDialog.tsx, src/Nav/Nav.tsx, src/Navbar/Navbar.tsx, src/Rate/Rate.tsx, src/Sidenav/Sidenav.tsx, src/Steps/Steps.tsx, src/Table/Table.tsx, src/Table/TablePagination.tsx, src/Tag/Tag.tsx, src/TagPicker/index.tsx, src/Timeline/Timeline.tsx, src/Timeline/TimelineItem.tsx, src/Toggle/Toggle.tsx, src/Uploader/Uploader.tsx, src/utils/defaultProps.ts, src/utils/withStyleProps.tsx
=> fix(recompose): fix the problem of not working under vite app

src/CheckTreePicker/CheckTreePicker.tsx, src/CheckTreePicker/test/CheckTreePickerSpec.js, src/CheckTreePicker/utils.ts, src/SelectPicker/SelectPicker.tsx, src/Tree/styles/index.ts, src/Tree/styles/themes/dark.ts, src/Tree/styles/themes/default.ts, src/Tree/test/TreeStylesSpec.js, src/TreePicker/TreePicker.tsx, src/utils/treeUtils.ts
1. Fix SelectPicker typo
2. Update CheckPicker cascader logic when using virtualized
3. Update useCallback dep
4. Update TreePicker and CheckTreePicker test case
=> Update CheckTreePicker cascade logic and test case

docs/pages/components/icon/en-US/custom-svg.md, docs/pages/components/icon/zh-CN/custom-svg.md
=> fix(docs/icon): strocke => stroke

src/CheckTreePicker/CheckTreePicker.tsx, src/CheckTreePicker/test/CheckTreePickerSpec.js, src/Picker/utils.ts, src/TreePicker/TreePicker.tsx, src/TreePicker/test/TreePickerSpec.js, src/utils/treeUtils.ts
- Tree support Left and Right Arrow keyboard event
- using `useToggleKeyDownEvent` to handle Picker toggle
- fixed some bugs
- update Tree test case
=> Tree support Left and Right arrow keyboard event

docs/pages/_app.tsx, src/CheckTreePicker/CheckTreeNode.tsx, src/TreePicker/TreeNode.tsx
also update Sentry config
- only works in production environment
- using package.version init Sentry.release
=> CheckTreePicker、TreePicker adjust padding style

.prettierrc.js, src/Dropdown/Dropdown.tsx, src/Overlay/RootCloseWrapper.tsx
=> fix(dropdown): fixed the dropdown trigger multiple callbacks when closed

docs/pages/components/button/en-US/active.md, docs/pages/components/button/en-US/disabled.md, docs/pages/components/button/zh-CN/active.md, docs/pages/components/button/zh-CN/disabled.md, src/IconButton/styles/common.less
=> fix(iconbutton): fix IconButton style error when disabled

src/Form/styles/mixin.less
=> fix(input-group): fix `InputGroup.Addon` height error when `inside` mode

src/Modal/Modal.tsx
=> fix(modal): fix Modal will change size when opened

docs/components/SideNavbar/styles.less, docs/pages/components/slider/en-US/index.md, docs/pages/components/slider/zh-CN/index.md, package-lock.json, package.json, src/RangeSlider/RangeSlider.tsx, src/Slider/Handle.tsx, src/Slider/Slider.tsx
=> feat(slider): support `onChangeCommitted` on Slider and RangeSlider

docs/pages/components/tree/en-US/index.md
=> docs(tree): Update the props description of tree

docs/pages/components/rate/fragments/basic.md, docs/pages/components/rate/fragments/character.md, docs/pages/components/rate/fragments/color.md, docs/pages/components/rate/fragments/custom-character.md, docs/pages/components/rate/fragments/disabled.md, docs/pages/components/rate/fragments/half-select.md, docs/pages/components/rate/fragments/hover.md, docs/pages/components/rate/fragments/size.md, docs/pages/components/rate/fragments/vertical.md, docs/pages/components/rate/index.tsx, karma.conf.js, src/Rate/Rate.tsx, src/Rate/styles/common.less, src/Rate/styles/mixin.less
The style problem caused by replacing with svg icon.
=> fix(rate): fix the half-ratings style of Rate

src/Picker/DropdownMenu.tsx, src/Picker/test/DropdownMenuSpec.js
=> fix(picker): fixed the non-unique key in the Picker option when groupBy

src/Popover/styles/common.less, src/Popover/test/PopoverStylesSpec.js, src/Tooltip/styles/common.less
=> fix(whisper): fix overlay jittering when the cursor is hovered

src/Dropdown/Dropdown.tsx, src/utils/index.ts
=> fix(dropdown): fix the issue of Dropdown close event

src/InputPicker/InputAutosize.tsx, src/InputPicker/styles/common.less
=> fix(tag-picker): fix TagPicker clear button not work

package-lock.json, package.json, src/Table/styles/common.less
=> fix(table): fixed unhandled scroll bar width when Cell is fixed on right

src/Footer/Footer.tsx, src/Footer/test/FooterSpec.js
Use `<footer>` tag instead of `<div>` for `<Footer>`.
=> fix(footer): use footer tag for Footer

src/InputPicker/InputAutosize.tsx, src/InputPicker/InputPicker.tsx, src/InputPicker/test/InputPickerSpec.js, src/TagPicker/test/TagPickerSpec.js
fix #1487
for TagPicker and InputPicker
=> fix(inputpicker): fix the input does not work when focused by keyboard

src/RangeSlider/RangeSlider.tsx
Fix the RangeSlider bar no color when clicking bar after handles are in same value
fix #1485
=> fix(rangeslider): fix RangeSlider style problem

src/styles/utilities.less
=> fix(pickers): picker should not be interactive during animation exit

src/DateRangePicker/DateRangePicker.tsx
Modify the `character`prop to be optional on DateRangePicker
=> fix(daterangepicker): modify the `character` prop to be optional on DateRangePicker

src/InputPicker/InputPicker.tsx
=> fix(inputpicker): fix can’t click option on InputPicker

docs/components/SearchDrawer/SearchDrawer.tsx, docs/components/TopLevelNav/TopLevelNav.tsx
fix: https://github.com/rsuite/rsuite/issues/1536
=> docs(search-drawer): fix the problem that search panel cannot be opened

src/Uploader/Uploader.tsx
fix: https://github.com/rsuite/rsuite/issues/1545
=> fix(uploader): fixed Uploader unable to upload removed files

src/Nav/Nav.tsx, src/Nav/test/NavSpec.js
fix: https://github.com/rsuite/rsuite/issues/1549
=> fix(nav): fix `onSelect` not working on Nav.Item

src/Overlay/Modal.tsx
=> fix(modal): fix input is not allowed to input text in Modal

src/@types/common.ts, src/Tree/Tree.tsx
=> fix(pickers): Fixed the inability to pass the type check when the `labelKey` and `valueKey` of the pickers are changed.

src/Cascader/test/CascaderSpec.js, src/Cascader/utils.ts, src/utils/index.ts
=> fix(cascader): fixed the option not re-rendering after data update

package-lock.json, package.json
=> build(deps): bump rsuite-table from 3.14.4 to 3.14.6

docs/package-lock.json, docs/package.json, docs/pages/components/icon/en-US/index.md, docs/pages/components/icon/fragments/custom-react-icons.md, docs/pages/components/icon/index.tsx, docs/pages/components/icon/zh-CN/index.md
=> docs(icon): add an example for react-icons

docs/package.json
=> chore: update dev script

docs/pages/guide/intl/en-US/index.md, docs/pages/guide/intl/fragments/locales.md, docs/pages/guide/intl/index.tsx, docs/pages/guide/intl/zh-CN/index.md, src/Calendar/CalendarPanel.tsx, src/CustomProvider/CustomProvider.tsx, src/CustomProvider/FormattedDate.tsx, src/CustomProvider/test/CustomProviderSpec.js, src/CustomProvider/test/FormattedDateSpec.js, src/DatePicker/DatePicker.tsx, src/locales/ar_EG.ts, src/locales/da_DK.ts, src/locales/de_DE.ts, src/locales/default.ts, src/locales/en_US.ts, src/locales/es_AR.ts, src/locales/es_ES.ts, src/locales/fi_FI.ts, src/locales/it_IT.ts, src/locales/ko_KR.ts, src/locales/pt_BR.ts, src/locales/ru_RU.ts, src/locales/sv_SE.ts, src/locales/zh_CN.ts, src/locales/zh_TW.ts, src/utils/useCustom.ts
=> fix(customprovider): integrate the locale of date-fns in CustomProvider

src/Table/styles/common.less
fix https://github.com/rsuite/rsuite/issues/1635
=> fix(table): fix long strings in table cells were incorrectly truncated

src/CheckTreePicker/CheckTreePicker.tsx, src/CustomProvider/test/CustomProviderSpec.js, src/TreePicker/TreePicker.tsx
remove locale from defaultProps
example: https://codesandbox.io/s/sleepy-joliot-usk5o?file=/src/index.js
=> fix(locale): fix the locale cannot be overwritten on TreePicker and CheckTreePicker

.github/workflows/codeql-analysis.yml
Uses [CodeQL Analysis](https://github.com/rsuite/rsuite/security/code-scanning) action provided by GitHub.
=> Add CI workflow for code scanning

src/InputPicker/InputPicker.tsx, src/InputPicker/test/InputPickerSpec.js
=> fix(input-picker): fix InputPicker value not rendering when plaintext

src/Cascader/Cascader.tsx, src/CheckPicker/CheckPicker.tsx, src/CheckTreePicker/CheckTreePicker.tsx, src/MultiCascader/MultiCascader.tsx, src/Picker/SearchBar.tsx, src/Picker/utils.ts, src/SelectPicker/SelectPicker.tsx, src/SelectPicker/test/SelectPickerSpec.js, src/TreePicker/TreePicker.tsx
The search box gets focus when typing characters and numbers.
close: #1688
=> feat(pickers): improve picker keyboard interaction experience

src/Radio/styles/index.less, src/Radio/test/RadioStylesSpec.js
=> fix(radio): fix checked radio style in disabled state

src/Checkbox/styles/mixin.less, src/Radio/styles/index.less
=> fix(radio): fix disabled radio hover style

src/Cascader/styles/index.less, src/MultiCascader/styles/index.less
=> fix(cascader): fix search result row height

src/InputPicker/InputPicker.tsx, src/InputPicker/test/InputPickerStylesSpec.js
=> fix(input-picker): fix extra height in disabled state

src/Dropdown/styles/index.less
=> fix(navbar): fix navbar dropdown hover text color

src/Checkbox/styles/mixin.less, src/InputPicker/InputPicker.tsx, src/TagPicker/styles/index.less
=> Fix plaintext style for Checkbox and TagPicker

src/Calendar/Calendar.tsx, src/DatePicker/styles/index.less, src/DateRangePicker/styles/index.less, src/DateRangePicker/test/DateRangePickerStylesSpec.js, src/styles/variables.less
=> fix(datepicker): fix gap between date cells

src/Timeline/styles/index.less
=> fix(timeline): fix incorrect spacing around axis in alternate alignment

src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.js
=> fix(date-picker): correct the style of non-current month dates

src/MultiCascader/test/MultiCascaderSpec.js, src/MultiCascader/utils.ts
=> Revert "fix: MultiCascader  data cann't be controlled"

.github/workflows/nodejs-ci.yml, README.md, README_zh.md
Add Codecov integration at https://app.codecov.io/gh/rsuite/rsuite/
=> ci: codecov integration

README.md, README_zh.md, docs/pages/guide/introduction/en-US/index.md, docs/pages/guide/introduction/zh-CN/index.md, examples/with-vite/.gitignore, examples/with-vite/README.md, examples/with-vite/index.html, examples/with-vite/package.json, examples/with-vite/src/App.jsx, examples/with-vite/src/index.jsx, examples/with-vite/src/index.less, examples/with-vite/vite.config.js
=> docs(examples): with-vite

src/Cascader/Cascader.tsx, src/Cascader/test/CascaderSpec.js, src/MultiCascader/MultiCascader.tsx, src/MultiCascader/test/MultiCascaderSpec.js, src/MultiCascader/utils.ts, src/Picker/utils.ts
=> fix(cascader): fix data not controlled on MultiCascader

gulpfile.js, package.json, test/validateBuilds.js
=> fix: add less plugins to output lib dir

src/styles/variables.less, test/validateBuilds.js
=> fix(styles): enable dark mode by default

docs/pages/components/input-picker/en-US/index.md, docs/pages/components/input-picker/zh-CN/index.md, docs/pages/components/tag-picker/en-US/index.md, docs/pages/components/tag-picker/zh-CN/index.md
fix #1774
This bug has been fixed in another PR:
https://github.com/rsuite/rsuite/pull/1747/files#diff-50e5923a9cfbdb087b7221772ddb83f85a14a36ec9d28268ee848d73d3ff4a48R439
=> docs(tag-picker): removed the default value of creatable

src/Cascader/Cascader.tsx, src/MultiCascader/MultiCascader.tsx
fix: https://github.com/rsuite/rsuite/issues/1750
=> fix(cascader): update the position after the overlay size is changed

docs/pages/components/grid/en-US/index.md
Fixed type. Changes 'response' to 'responsive'
=> Fixed Typo

src/Calendar/TimeDropdown.tsx, src/DatePicker/test/DatePickerSpec.js
fix: https://github.com/rsuite/rsuite/issues/1793
=> fix(date-picker): fix AM/PM display incorrect issue when switching hours

docs/components/SearchDrawer/SearchDrawer.tsx, docs/components/SearchDrawer/styles.less, docs/package.json, docs/scripts/algolia-indices.js
=> docs(search): improved search of documents

src/Calendar/useCalendarDate.ts, src/DatePicker/test/DatePickerSpec.js
=> fix(date-picker): fix DatePicker cannot be used as controlled

docs/pages/components/tag-picker/en-US/index.md, docs/pages/components/tag-picker/fragments/trigger.md, docs/pages/components/tag-picker/zh-CN/index.md, src/InputPicker/InputPicker.tsx, src/TagPicker/index.tsx, src/TagPicker/test/TagPickerSpec.js, src/utils/constants.ts
A tag can be created by typing a space or a comma.
```tsx
<TagPicker creatable trigger="Comma" /> 
<TagPicker creatable trigger={["Enter", "Comma", "Space"]} /> 
```
=> feat(tag-picker): support `trigger` on `<TagPicker>`

docs/pages/guide/v5-features/en-US/index.md, docs/pages/guide/v5-features/zh-CN/index.md
Sorry for the PR without previous discussion, but it looked too obvious and small a change. I hope this does not bother you.
=> Fixed useRef typos

src/List/ListItem.tsx
=> fix(list-item): fix unable to set HTML event on List.Item

docs/pages/components/date-picker/en-US/index.md, docs/pages/components/date-picker/zh-CN/index.md, src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.js, src/DatePicker/test/ToolbarSpec.js
=> feat(date-picker): remove `inline` on `<DatePicker>`

docs/pages/components/animation/fragments/collapse.md, src/Animation/Bounce.tsx, src/Animation/Collapse.tsx, src/Animation/Fade.tsx, src/Animation/Slide.tsx, src/Animation/styles/index.less, src/Animation/styles/mixin.less, src/Animation/test/CollapseSpec.js, src/Drawer/styles/index.less, src/Drawer/styles/mixin.less, src/Drawer/test/DrawerSpec.js, src/Modal/styles/index.less, src/Panel/test/PanelSpec.js, src/Popover/styles/index.less, src/Tooltip/styles/index.less, src/styles/mixins/utilities.less
fix https://github.com/rsuite/rsuite/issues/1888
fix https://github.com/rsuite/rsuite/issues/582
fix https://github.com/rsuite/rsuite/issues/996
fix https://github.com/rsuite/rsuite/issues/1898
=> refactor(animation): add a prefix to animation-related className

src/DatePicker/styles/index.less
=> fix(date-picker): fix calendar header wrapping

docs/package.json, src/Menu/MenuItem.tsx, src/Menu/test/MenuItemSpec.js
=> fix(navbar,dropdown): unexpected focus submenu

docs/pages/_app.tsx
=> docs: fix page stuck on system color scheme change

README.md
=> docs(readme): fix rsuite v4 documentation url

docs/pages/guide/use-next-app/en-US/index.md, docs/pages/guide/use-next-app/zh-CN/index.md
https://github.com/rsuite/rsuite/issues/711
=> docs(use-nextjs): use as instead of componentClass on Nav.Item

src/FormControl/FormControl.tsx
=> fix(FormControl): infer additional props from accepter

src/locales/fa_IR.ts
I just noticed that the date picker is shown the dates in a longer format so it cause some styling issues so I fix that with this PR
=> trim fa_IR long text of days to shorter ones

docs/pages/components/dropdown/en-US/index.md, docs/pages/components/dropdown/zh-CN/index.md
See discussion here https://github.com/rsuite/rsuite/issues/2090#issuecomment-957218840
=> docs(Dropdown): remove deprecated open prop

examples/create-react-app/package.json, examples/create-react-app/src/App.js
=> build: upgrade to rsuite 5 in examples/create-react-app

docs/pages/components/cascader/en-US/index.md, docs/pages/components/cascader/zh-CN/index.md, docs/pages/components/check-picker/en-US/index.md, docs/pages/components/check-picker/zh-CN/index.md, docs/pages/components/check-tree-picker/en-US/index.md, docs/pages/components/check-tree-picker/zh-CN/index.md, docs/pages/components/date-picker/en-US/index.md, docs/pages/components/date-picker/zh-CN/index.md, docs/pages/components/date-range-picker/en-US/index.md, docs/pages/components/date-range-picker/zh-CN/index.md, docs/pages/components/input-picker/en-US/index.md, docs/pages/components/input-picker/zh-CN/index.md, docs/pages/components/multi-cascader/en-US/index.md, docs/pages/components/multi-cascader/zh-CN/index.md, docs/pages/components/select-picker/en-US/index.md, docs/pages/components/select-picker/zh-CN/index.md, docs/pages/components/tree-picker/en-US/index.md, docs/pages/components/tree-picker/zh-CN/index.md, src/Picker/PickerToggle.tsx, src/Picker/test/PickerToggleSpec.js
=> refactor(Picker): rename caretComponent prop to caretAs

src/AutoComplete/AutoComplete.tsx, src/List/helper/useSortHelper.ts, src/Message/Message.tsx, src/Notification/Notification.tsx, src/utils/index.ts, src/utils/test/useIsMountedSpec.js, src/utils/useIsMounted.ts
=> fix: can't perform a React state update on an unmounted component

src/Button/styles/index.less
Some people like right-angle buttons, such as me, so I think it’s better to customize it. Before V4, it can be customized.
=> Add button radius variable

.eslintrc.js, src/Dropdown/DropdownItem.tsx, src/Dropdown/useRenderDropdownItem.tsx, src/Sidenav/SidenavDropdownItem.tsx, src/Sidenav/test/SidenavSpec.js
`<Dropdown.Item as>` inside `<Sidenav>` does not work with `<Link to>` from `react-router-dom`.
=> fix(Sidenav): sidenav dropdown item accept as prop

src/Dropdown/DropdownItem.tsx, src/Dropdown/test/DropdownMenuItemSpec.js
=> fix(Dropdown): dropdown item panel not rendering content

src/utils/test/ajaxUploadSpec.js
=> test(ajaxUpload): mock xhr and timer

src/PanelGroup/styles/index.less
=> fix(PanelGroup): missing border for nested panels

docs/pages/components/button/fragments/icon-button.md, src/Button/styles/index.less
=> fix(IconButton): primary icon button with text wrong bg

docs/pages/_app.tsx, docs/pages/components/checkbox/zh-CN/index.md, docs/pages/components/radio/zh-CN/index.md
1. fix v4 docs typo
2. update v5 release text of global banner
=> fix v4 docs typo in CheckBox and Radio

src/Menu/Menu.tsx, src/Menu/MenuItem.tsx
=> perf(Menu): prevent uneccesary re-render when mouseove on menuitems

docs/pages/guide/use-next-app/en-US/index.md, docs/pages/guide/use-next-app/zh-CN/index.md
This PR is basically a replacement of the inactive #2030.
=> Update guide for using with Next.js

src/utils/test/useElementResizeSpec.js, src/utils/useElementResize.ts
fix: https://sentry-prd.hypers.cc/sentry/rsuitejs-com/issues/113802/?query=url%3A%22https%3A%2F%2Frsuitejs.com%2Fcomponents%2Faffix%2F%22
=> fix(useElementResize): fix ResizeObserver being created repeatedly

.codesandbox/ci.json, src/Picker/utils.ts, src/SelectPicker/test/SelectPickerSpec.js
fix: https://codesandbox.io/s/silent-voice-6kzx7
=> fix(pickers): fix custom input in Picker cannot be focused

package-lock.json, package.json
* **Column:** fix alignment is overwritten in ColumnGroup ([#282](https://github.com/rsuite/rsuite-table/issues/282)) ([0ea6a71](https://github.com/rsuite/rsuite-table/commit/0ea6a7100360f80de820e4f53996a03ee3bf7c3e))
=> build(deps): bump rsuite-table from 5.2.1 to 5.2.2

src/Modal/Modal.tsx, src/Modal/test/ModalSpec.js, src/Overlay/Modal.tsx, src/Overlay/ModalManager.ts
=> fix(Modal): fix Modal not focused when opened

docs/pages/components/check-tree/en-US/index.md, docs/pages/components/check-tree/fragments/show-indent-line.md, docs/pages/components/check-tree/zh-CN/index.md, docs/pages/components/tree/en-US/index.md, docs/pages/components/tree/fragments/show-indent-line.md, docs/pages/components/tree/zh-CN/index.md, src/CheckTree/test/CheckTreeSpec.js, src/CheckTreePicker/CheckTreeNode.tsx, src/CheckTreePicker/CheckTreePicker.tsx, src/CheckTreePicker/styles/index.less, src/Tree/Tree.tsx, src/Tree/test/TreeSpec.js, src/TreePicker/TreeNode.tsx, src/TreePicker/TreePicker.tsx, src/TreePicker/styles/index.less, src/utils/treeUtils.ts
```tsx
<Tree showIndentLine />
<CheckTree showIndentLine />
```
=> feat(tree): support showIndentLine on <Tree> and <CheckTree>

package-lock.json, src/Button/Button.tsx, src/ButtonGroup/ButtonGroup.tsx, src/ButtonGroup/ButtonGroupContext.ts, src/ButtonGroup/index.tsx, src/ButtonGroup/styles/index.less, src/ButtonGroup/test/ButtonGroupSpec.js, src/ButtonGroup/test/ButtonGroupStylesSpec.js
=> fix(Button): apply size from parent ButtonGroup

src/Steps/StepItem.tsx, src/Steps/test/StepItemSpec.js
=> fix(Steps): step item not rendering number

docs/less/pages/components/overview.less, docs/pages/components/overview/CategorizedList.tsx, docs/pages/components/overview/SortedList.tsx, docs/pages/components/overview/index.tsx, docs/utils/component.config.json
=> docs(overview): support sorting overview by character

src/Modal/test/ModalSpec.js, src/Overlay/Modal.tsx
=> fix(Modal): fix Modal focus being reset on re-rendering

src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.js
=> fix(DateRangePicker): fix selecting ending date not working

src/Toggle/Toggle.tsx, src/Toggle/test/ToggleSpec.js
=> fix(Toggle): fix Toggle is still clickable in loading state

src/Dropdown/DropdownToggle.tsx, src/Dropdown/styles/index.less, src/Dropdown/test/DropdownStylesSpec.js, src/Nav/Nav.tsx, src/Nav/NavContext.ts, src/Nav/styles/index.less, src/Nav/test/NavStylesSpec.js, test/testUtils.js
=> fix(Nav): fix incorrect Dropdown button background

karma.conf.js, test/setupTests.js
=> test: prevent circular structure error thrown from chai

docs/pages/components/form/fragments/modal-layout.md, src/Modal/test/ModalSpec.js, src/Overlay/Modal.tsx, src/Overlay/Overlay.tsx, src/Overlay/OverlayContext.ts, src/Overlay/OverlayTrigger.tsx, src/Overlay/Position.tsx, src/utils/usePortal.tsx
=> fix(Overlay): overlay is rendered inside Modal by default

src/DatePicker/DatePicker.tsx, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.js
=> fix(DatePicker,DateRangePicker): suppress depreated caretComponent warning

package-lock.json, package.json
v4 supporting table’s kid is a react.fragment
=> feat: rsuite-table => 3.16.0

src/Navbar/styles/index.less, src/Navbar/test/NavbarStylesSpec.js
=> fix(Navbar): fix icon style in Navbar items

src/Radio/Radio.tsx, src/Radio/styles/index.less
=> fix(Radio): fix unclickable without children

src/Toggle/Toggle.tsx, src/Toggle/test/ToggleSpec.js
=> fix(Toggle): dismiss uncontrolled input warning

src/Sidenav/styles/index.less, src/Sidenav/test/SidenavStylesSpec.js, test/testUtils.js
=> fix(Sidenav): fix missing highlight on selected dropdown items

src/Disclosure/Disclosure.tsx, src/Disclosure/DisclosureButton.tsx, src/Disclosure/DisclosureContext.ts, src/Disclosure/test/DisclosureSpec.js, src/Dropdown/Dropdown.tsx, src/Dropdown/DropdownItem.tsx, src/Dropdown/DropdownMenu.tsx, src/Navbar/index.tsx, src/Navbar/styles/index.less, src/Navbar/test/NavbarSpec.js
=> fix(Navbar): fix dropdown submenu throwing error

src/Affix/Affix.tsx, src/utils/index.ts, src/utils/test/useMountSpec.js, src/utils/useMount.ts
=> fix(Affix): fix unupdated position after window size change

src/Modal/Modal.tsx, src/Modal/styles/index.less, src/Modal/test/ModalSpec.js, src/Overlay/Modal.tsx
https://user-images.githubusercontent.com/1203827/147219478-6864e927-e26f-4f96-acad-0f224131b5d6.mp4
fix https://codesandbox.io/s/busy-knuth-8w9jt
=> fix(Modal): improve the mouse scrolling experience on Modal

src/Drawer/styles/index.less, src/Drawer/test/DrawerSpec.js, src/Drawer/test/DrawerStylesSpec.js
fix https://github.com/rsuite/rsuite/issues/2258
=> fix(Drawer): fix Drawer cannot be closed when backdrop is clicked

src/Calendar/useCalendarDate.ts, src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.js
=> fix(DatePicker): fix clear button not working

src/Nav/NavItem.tsx, src/Navbar/test/NavbarSpec.js
=> fix(Navbar): fix Whisper on Nav.Item within Navbar wrong positioning

src/Dropdown/DropdownMenu.tsx, src/Dropdown/styles/index.less
=> fix(Dropdown): wrong submenu placement in RTL direction

src/MultiCascader/MultiCascader.tsx, src/MultiCascader/test/MultiCascaderSpec.js
=> fix(MultiCascader): fix not rendering the count of selected values

src/InputNumber/InputNumber.tsx, src/InputNumber/test/InputNumberSpec.js
Implement keyboard interacitons as an [ARIA spinbutton](https://www.w3.org/TR/wai-aria-practices-1.2/#spinbutton)
| Key | Action |
| --- | ------ |
| Up Arrow | Increases the value. |
| Down Arrow | Decreases the value. |
| Home | If the spinbutton has a minimum value, sets the value to its minimum. |
| End | If the spinbutton has a maximum value, sets the value to its maximum. |
=> feat(InputNumber): support keyboard interaction

src/InputNumber/InputNumber.tsx, src/InputNumber/test/InputNumber.test.tsx
=> fix(InputNumber): inherit html input attributes

src/Dropdown/Dropdown.tsx, src/Dropdown/test/Dropdown.test.tsx
=> fix(Dropdown): infer toggleAs component props

src/Modal/styles/mixin.less
Make the modal responsive, for screens smaller than the target modal size
=> feat(Modal): Make responsive for small screen size

src/InputNumber/InputNumber.tsx, src/InputNumber/test/InputNumberSpec.js
=> fix: fix inputNumber uncontrolled

README.md, README_zh.md, docs/pages/guide/introduction/en-US/index.md, docs/pages/guide/introduction/zh-CN/index.md, docs/pages/guide/use-with-create-react-app/en-US/index.md, docs/pages/guide/use-with-create-react-app/zh-CN/index.md, docs/pages/resources/palette/en-US/index.md, docs/pages/resources/palette/zh-CN/index.md
Links for custom theme on documentation and README.md was broken. Fixed #2333
=> Fix: broken links to customization page

docs/pages/components/date-picker/fragments/one-tap.md, src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.js
=> fix(DatePicker): fixed oneTap to work in month view

docs/components/LanguageButton/LanguageButton.tsx, src/IconButton/IconButton.tsx, src/IconButton/test/IconButton.test.tsx
=> fix(IconButton): infer addtional props from as prop

docs/pages/components/message/index.tsx, src/utils/test/useTimeoutSpec.js, src/utils/useTimeout.ts
=> fix(useTimeout): fix callback not being called after timeout

docs/pages/guide/customization/en-US/index.md, docs/pages/guide/customization/zh-CN/index.md
Update correct light.less link in `/guide/customization` page .
=> docs(customization): update less link

src/CheckTreePicker/CheckTreePicker.tsx, src/CheckTreePicker/test/CheckTreePickerSpec.js
fix checkTreePicker replacement data expand failure
=> fix: fix checkTreePicker replacement data expand failure

src/Affix/Affix.tsx
- Affix: remove left offset for better fixed position
- closed #2369
=> fix(Affix): fix left offset not update after position change

docs/package-lock.json, docs/package.json
=> docs: update @rsuite/document-nav

package-lock.json, package.json
* **rerender:** fix table infinite rerender ([#319](https://github.com/rsuite/rsuite-table/issues/319)) ([da4b36b](https://github.com/rsuite/rsuite-table/commit/da4b36b8f361fbcbcb4327fd093ef9a33cb9e06b))
=> build(deps): bump rsuite-table from 5.3.3 to 5.3.4

package-lock.json, package.json
* **scroll:** fix horizontal scroll position exception ([#323](https://github.com/rsuite/rsuite-table/issues/323)) ([aef4bd5](https://github.com/rsuite/rsuite-table/commit/aef4bd5ee12398aab225c026abd114bbe62c59ef))
=> build(deps): bump rsuite-table from 5.3.4 to 5.3.5

docs/pages/components/check-tree-picker/en-US/index.md, docs/pages/components/check-tree-picker/zh-CN/index.md, docs/pages/components/input-picker/en-US/index.md, docs/pages/components/input-picker/zh-CN/index.md, docs/pages/components/select-picker/en-US/index.md, docs/pages/components/select-picker/zh-CN/index.md, docs/pages/components/tag-picker/en-US/index.md, docs/pages/components/tag-picker/zh-CN/index.md
docs: add `open` property for CheckTreePicker, SelectPicker, InputPicker, TagPicker
=> docs(Pickers): add `open` property

package-lock.json, package.json
- **Columns:** fix Fragment render in nested array ([#327](https://github.com/rsuite/rsuite-table/issues/327)) ([a29e38c](https://github.com/rsuite/rsuite-table/commit/a29e38ce565af662f8577ce8b32026fd4f15cda1))
=> build(deps): bump rsuite-table from 5.3.5 to 5.3.6

src/CheckTree/index.tsx
add `uncheckableItemValues` missing type definition
=> fix(checktree): fix missing type definition

package-lock.json, package.json
fix when use Fragment for table,the fixed columns fail
=> fix: fix when use Fragment for table,the fixed columns fail

src/Uploader/index.tsx
**Changes:**
This PR exposes public types used by the Uploader to be imported by consumer
**Rationale:**
As public types, they should be exposed for the consumer to use in case of need.
=> fix(Uploader): expose missing public types

src/CheckPicker/CheckPicker.d.ts, src/InputPicker/InputPicker.d.ts, src/SelectPicker/SelectPicker.d.ts, src/TagPicker/TagPicker.d.ts
=> fix: fix selectPicker type issue

src/Dropdown/test/DropdownMenuSpec.js, src/Menu/MenuItem.tsx
=> Fix menu item hover highlight

src/SelectPicker/test/SelectPickerSpec.js
delete test case only :sweat_smile:
=> fix: delete test case only

src/Checkbox/Checkbox.tsx, src/Checkbox/test/CheckboxSpec.js, src/CheckboxGroup/CheckboxGroupContext.ts, src/CheckboxGroup/test/CheckboxGroupSpec.js, src/Picker/DropdownMenuCheckItem.tsx
=> fix(Checkbox): set checked attribute on underlying input

src/RangeSlider/RangeSlider.tsx, src/RangeSlider/test/RangeSliderSpec.js
fix https://github.com/rsuite/rsuite/issues/2425
=> fix(RangeSlider): fix RangeSlider progress bar misalignment

docs/pages/components/cascader/en-US/index.md, docs/pages/components/cascader/zh-CN/index.md, src/Cascader/Cascader.tsx, src/Cascader/test/CascaderSpec.js
- add `renderSearchItem` for customizing search result
```ts
{
renderSearchItem?: (itemLabel: React.ReactNode, item: ItemDataType) => React.ReactNode;
}
```
=> feat(Cascader): add `renderSearchItem` for customizing search result

src/DateRangePicker/index.tsx
```ts
import type { ValueType, DateRange, RangeType, DisabledDateFunction } from 'rsuite/DateRangePicker';
```
=> fix(DateRangePicker): export type definition

src/Button/Button.tsx
=> button typo

docs/pages/components/form-validation/en-US/index.md, docs/pages/components/form-validation/zh-CN/index.md
docs: fix form-validation schema link error
=> docs: fix form-validation schema link error

docs/components/Head.tsx, docs/pages/404.tsx, docs/pages/_document.tsx
1. <img width="1271" alt="image" src="https://user-images.githubusercontent.com/15609339/164705182-243fe106-f405-4906-b190-14dea4130711.png">
2. <img width="1395" alt="image" src="https://user-images.githubusercontent.com/15609339/164705151-08eb1dda-9305-441d-aa99-ad92ac664071.png">
=> improve: clear some next warning message

README.md, docs/components/PageContent.tsx, docs/components/VercelBanner.tsx
Make this repo fulfill [Vercel's sponsorship criteria](https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project#sponsorship-criteria) so that we can apply for a sponsored open source account.
- Add Vercel banner in README
- Add Vercel banner in footer of each page on the doc site
=> chore: fulfill vercel sponsorship criteria

src/Picker/utils.ts
=> fix(listbox): fix broken keyboard navigation after filtering

docs/components/TopLevelNav/TopLevelNav.tsx, docs/pages/components/whisper/en-US/props.md, docs/pages/components/whisper/zh-CN/props.md, src/FormHelpText/FormHelpText.tsx, src/Overlay/OverlayTrigger.tsx, src/Whisper/Whisper.tsx, src/Whisper/test/Whisper.test.tsx, src/index.tsx
Add documentation for accessing Whisper methods via `ref`
Fix #2501
=> Document Whisper `ref`

docs/pages/components/sidenav/fragments/appearance.md, docs/pages/components/sidenav/fragments/collapsed.md, src/Sidenav/SidenavToggle.tsx, src/Sidenav/styles/index.less, src/styles/color-modes/dark.less, src/styles/color-modes/high-contrast.less, src/styles/color-modes/light.less, src/styles/variables.less
=> fix(Sidenav): correct Sidenav.Toggle styles

src/Panel/Panel.tsx, src/PanelGroup/test/PanelGroupSpec.js
Before
https://user-images.githubusercontent.com/1203827/170982202-8a30703c-5728-4546-a3d4-b09f7d64d879.mp4
After
https://user-images.githubusercontent.com/1203827/170982732-0df0b891-470c-4bce-902c-e4c50ae5bee8.mp4
=> fix(Panel): fix accordion not collapsible expanded panel

src/Table/styles/index.less, src/styles/variables.less
=> fix(Table): fix elements in merged cells being occluded

src/Nav/test/NavItemSpec.js, src/Sidenav/SidenavDropdownToggle.tsx, src/Sidenav/SidenavItem.tsx
=> fix(Sidenav): display tooltip when hovering collapsed Sidenav item

src/Form/Form.tsx, src/Form/test/Form.test.tsx, src/index.tsx
=> fix(Form): make FormInstance methods non-nullable

src/Modal/test/Modal.test.tsx, src/Overlay/Modal.tsx
=> fix(Modal): expose missing props

src/DatePicker/test/DatePickerSpec.js
=> test(DatePicker): fix validation timeout tests

docs/pages/components/sidenav/fragments/appearance.md
=> docs(Sidenav): fix props usage error in example

docs/pages/components/radio/fragments/radio-group-inline-picker.md
Simple correction of spelling error ("Enbaled", line 27)
=> docs: spelling correction on radio-group-inline-picker

karma.conf.js
=> ci(mocha): changed timeout from 2000 to 10000

docs/pages/components/input-number/fragments/combination.md, src/Form/styles/mixin.less, src/InputGroup/styles/index.less
Before
After
Added another example
=> fix(InputNumber): fix unexpected focus ring when used within an InputGroup

src/CheckPicker/CheckPicker.tsx, src/CheckPicker/test/CheckPicker.test.tsx, src/SelectPicker/SelectPicker.tsx, src/SelectPicker/test/SelectPicker.test.tsx
Add missing `label` prop declaration
=> fix(SelectPicker,CheckPicker): add missing label prop declaration

src/SelectPicker/SelectPicker.tsx, src/SelectPicker/test/SelectPicker.test.tsx
Make `value` and `onChange`'s `value` parameter nullable.
=> fix(SelectPicker): make controlled value nullable

docs/pages/components/slider/fragments/vertical.md
=> docs(slider): fix unrendered examples

docs/pages/components/notification/fragments/with-toaster.md, src/CustomProvider/CustomProvider.tsx, src/toaster/test/useToasterSpec.js, src/utils/usePortal.tsx
=> fix(CustomProvider): fix warnings caused by server-side rendering

src/Overlay/OverlayTrigger.tsx, src/Overlay/test/OverlayTriggerSpec.js
=> fix(OverlayTrigger): fix invalid rendering without followCursor

src/Picker/styles/index.less, src/TreePicker/styles/index.less
Styles common to pickers should not be placed in TreePicker.
=> fix(Picker): fix style dependency

src/Picker/DropdownMenu.tsx, src/SelectPicker/SelectPicker.tsx, src/SelectPicker/test/SelectPicker.test.tsx, src/Tree/Tree.tsx, src/Tree/test/Tree.test.tsx
fix: https://github.com/rsuite/rsuite/issues/2616#issuecomment-1196451778
=> fix(listProps): fix properties in listProps to be optional

docs/components/CodeView/CodeView.tsx, docs/components/CodeView/ReactCodeView.tsx, docs/less/index.less, docs/package-lock.json, docs/package.json, docs/pages/components/container/fragments/login-page.md, docs/pages/components/container/fragments/navbar-page.md, docs/pages/components/container/fragments/sidebar-page.md, docs/pages/components/dropdown/fragments/toggle-as.md, docs/pages/components/input/fragments/input-group.md, docs/pages/components/input/fragments/masked-input.md, docs/pages/components/placeholder/fragments/paragraph.md, docs/pages/components/table/fragments/colspan.md, docs/pages/components/table/index.tsx
Use sucrase instead of @swc/wasm-web to improve transcoding performance
=> build(deps): bump react-code-view to 2.2.0 from 2.1.0

docs/components/IconList/IconList.tsx, docs/less/pages/resources/icons.less, docs/locales/en-US/index.ts, docs/locales/zh-CN/index.ts, docs/pages/resources/icons/index.tsx
https://rsuitejs.com/resources/icons/
=> docs(icons): improved icon search with no results

src/AutoComplete/AutoComplete.tsx, src/AutoComplete/test/AutoComplete.test.tsx
fix https://github.com/rsuite/rsuite/issues/2643
=> fix(AutoComplete): fix missing definition of string in datatype

src/Disclosure/Disclosure.tsx, src/Disclosure/test/DisclosureSpec.js, src/Navbar/NavbarDropdownMenu.tsx
fix https://github.com/rsuite/rsuite/pull/2595#issuecomment-1207366678
=> fix(Disclosure): prevent onmouseout from firing on child elements

src/Calendar/Header.tsx
=> fix(DatePicker,DateRangePicker): display month name as title of month calendar view

docs/components/PageToolbar/PageToolbar.tsx
=> docs(PageToolbar): add a sponsor button

docs/pages/components/panel/en-US/index.md, docs/pages/components/panel/fragments/with-action.md, docs/pages/components/panel/index.tsx, docs/pages/components/panel/zh-CN/index.md
=> docs(panel): add an example with action buttons to the panel

package-lock.json, package.json
https://github.com/rsuite/rsuite-table/releases/tag/5.7.0
=> build(deps): bump rsuite-table from 5.6.0 to 5.7.0

docs/pages/components/table/en-US/index.md, docs/pages/components/table/fragments/expanded.md, docs/pages/components/table/zh-CN/index.md
https://github.com/rsuite/rsuite/issues/2666#issuecomment-1223406527
=> docs(Table): add usage instructions for Tree Table

docs/pages/components/date-picker/en-US/index.md, docs/pages/components/date-picker/zh-CN/index.md, docs/pages/components/date-range-picker/en-US/index.md, docs/pages/components/date-range-picker/zh-CN/index.md
=> docs(DateRangePicker): fix markdown untransformed links

docs/pages/components/date-picker/en-US/index.md, docs/pages/components/date-picker/fragments/editable.md, docs/pages/components/date-picker/zh-CN/index.md, docs/pages/components/date-range-picker/en-US/index.md, docs/pages/components/date-range-picker/fragments/editable.md, docs/pages/components/date-range-picker/zh-CN/index.md, src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.js, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.js
Support `editable` on DatePicker and DateRangePicker. Its default value is true.
```tsx
<DatePicker editable={false} />
<DateRangePicker editable={false} />
```
=> feat(DatePicker,DateRangePicker): support to disable keyboard input

docs/pages/components/form/fragments/fluid.md, src/FormControl/styles/index.less
fix: https://github.com/rsuite/rsuite/issues/2669
=> fix(FormControl): fix InputGroup not filling the container when fluid

docs/pages/components/whisper/en-US/props.md, docs/pages/components/whisper/zh-CN/props.md
=> docs(Whisper): fix wrong link

package-lock.json, package.json
https://github.com/rsuite/rsuite-table/releases/tag/5.7.1
=> build(deps): bump rsuite-table 5.7.1

docs/pages/components/date-range-picker/fragments/custom-shortcut-options.md, src/DatePicker/Toolbar.tsx, src/DatePicker/styles/index.less, src/DatePicker/test/ToolbarSpec.js
fix: https://github.com/rsuite/rsuite/issues/2691
=> fix(DateRangePicker): fix predefined range and OK button conflict

src/Form/styles/mixin.less
Before
https://user-images.githubusercontent.com/8225666/189083009-764b59d6-ecef-4a16-9901-6445b2866b7c.mov
After
https://user-images.githubusercontent.com/8225666/189083004-2b72f702-4bf9-4f21-84e9-93410b50a5e5.mov
=> fix(Input): fix missing focus ring when mouse hover

src/CheckPicker/test/CheckPickerSpec.js, src/Picker/PickerToggle.tsx, src/Picker/styles/index.less, src/SelectPicker/test/SelectPickerSpec.js
=> fix(CheckPicker,SelectPicker): fix inconsistent label spacing

src/Sidenav/SidenavItem.tsx, src/Sidenav/test/SidenavSpec.js
before
https://user-images.githubusercontent.com/1203827/191716835-7b108592-bddf-4d31-99aa-712dcf1f6949.mp4
after
https://user-images.githubusercontent.com/1203827/191717125-fb8e6005-dd1b-40a7-bd2e-f2de6871e130.mp4
=> fix(Sidenav): fix tooltip blocking menu items

package-lock.json, package.json
https://github.com/rsuite/rsuite-table/releases/tag/5.7.2
=> build(deps): bump rsuite-table from 5.7.1 to 5.7.2

package-lock.json, package.json
fix: https://ci.codesandbox.io/status/rsuite/rsuite/pr/2792
=> build(deps): bump gulp-postcss from 7.0.1 to 9.0.1

src/DatePicker/PredefinedRanges.tsx, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.js
=> fix(DateRangePicker): fix predefined range affecting calendar height

src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.js, src/Overlay/OverlayTrigger.tsx, src/Picker/PickerToggleTrigger.tsx, src/Whisper/Whisper.tsx
Before
https://user-images.githubusercontent.com/8225666/195821138-17bca5a6-c3e7-4139-9f1b-41037a93a494.mov
After
https://user-images.githubusercontent.com/8225666/195821129-418a52b4-333b-4390-83b8-db6091552da4.mov
=> fix(DatePicker): reset calendar selection after closing picker menu

src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.js
fix https://github.com/rsuite/rsuite/issues/2839
=> fix(DateRangePicker): fix end time will change with the start time

docs/pages/_common/types/range.md, docs/pages/components/date-picker/en-US/index.md, docs/pages/components/date-picker/fragments/custom.md, src/DatePicker/DatePicker.tsx, src/DatePicker/styles/index.less, src/DatePicker/test/DatePickerSpec.js, src/DatePicker/types.ts
=> feat(DatePicker): allow ranges on left of calendar

docs/components/PageContent.tsx, docs/less/carbonads.less, docs/less/index.less
=> docs: install carbon

docs/pages/components/table/en-US/index.md, docs/pages/components/table/zh-CN/index.md
=> docs(Table): add instructions for `wordWrap`

docs/pages/components/date-range-picker/fragments/controlled.md, src/Calendar/Calendar.tsx, src/Calendar/CalendarContainer.tsx, src/Calendar/MonthDropdownItem.tsx, src/Calendar/TimeDropdown.tsx, src/Calendar/test/CalendarMonthDropdownItemSpec.js, src/Calendar/test/CalendarMonthDropdownSpec.js, src/Calendar/test/CalendarTimeDropdownSpec.js, src/Calendar/types.ts, src/DatePicker/DatePicker.tsx, src/DateRangePicker/Calendar.tsx, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/CalendarSpec.js, src/DateRangePicker/test/DateRangePickerSpec.js, src/DateRangePicker/test/utilsSpec.js, src/DateRangePicker/utils.ts, src/utils/dateUtils.ts, src/utils/test/dateUtilsSpec.js
Example to reproduce the bug  https://codesandbox.io/s/stoic-sun-fgw8er
=> fix(DateRangePicker): fix time on calendar changing with date change

src/Dropdown/test/DropdownSpec.tsx, src/Menu/MenuItem.tsx
=> fix(Dropdown): fix error on deletion of last Dropdown.Item

docs/pages/components/date-picker/zh-CN/index.md
=> docs(DatePicker): remove timezone

docs/pages/components/table/fragments/basic.md, docs/pages/components/table/fragments/edit.md
本次 commit 是为了让 Table 组件的示例更加合理，修改内容如下：
1、使用 Button 组件展示 Edit 项，使其不再是复制的鼠标样式；
2、由于示例代码中使用了 Button 组件，因此加上引用 Button 组件的部分。
=> docs(Table): optimizing the sample code

src/Container/test/ContainerSpec.tsx
Use `waitFor` instead of `setTimeout`
=> test(Container): remove test scripts with side effects

src/Menu/Menu.tsx, src/Menu/test/MenuSpec.tsx
=> test(Menu): add test cases for unstable test coverage

docs/pages/components/auto-complete/en-US/index.md, docs/pages/components/auto-complete/fragments/size.md, docs/pages/components/auto-complete/index.tsx, docs/pages/components/auto-complete/zh-CN/index.md, src/AutoComplete/AutoComplete.tsx, src/AutoComplete/test/AutoCompleteSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/2982
=> fix(AutoComplete): fix AutoComplete size property not working

src/Navbar/test/NavbarBrandSpec.tsx, src/utils/createComponent.tsx
=> fix(Navbar.Brand): fix missing href prop

src/Cascader/Cascader.tsx, src/Cascader/utils.ts, src/MultiCascader/MultiCascader.tsx, src/MultiCascader/test/MultiCascaderSpec.tsx, src/MultiCascader/utils.ts
=> fix(MultiCascader): fix load async data error in inline mode 

package-lock.json, package.json
https://github.com/rsuite/rsuite-table/releases/tag/5.8.2
=> build(deps): bump rsuite-table from 5.8.1 to 5.8.2

CONTRIBUTING.md, CONTRIBUTING.zh-CN.md
Add [BDD assertion style](https://www.chaijs.com/api/bdd/) for Testing.
> See: https://github.com/rsuite/rsuite/pull/3003#discussion_r1065281992
=> docs(CONTRIBUTING.md): add BDD's assertion style

src/Calendar/TableHeaderRow.tsx, src/Calendar/styles/index.less, src/DatePicker/styles/index.less, src/DatePicker/styles/mixin.less, src/styles/color-modes/dark.less, src/styles/color-modes/high-contrast.less, src/styles/color-modes/light.less
https://user-images.githubusercontent.com/1203827/211966212-9ceca049-bc4b-40a9-b137-28b2dd5614cb.mp4
https://rsuite-nextjs-git-fix-datepicker-rsuite.vercel.app/components/date-picker/
=> fix(DatePicker,DateRangePicker): fix the background color error when the cell is hovered

src/Calendar/MonthDropdown.tsx, src/DatePicker/test/DatePickerSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/2997
=> fix(DatePicker): fix first click not working on month selection

docs/pages/components/button/fragments/disabled.md, src/styles/color-modes/dark.less
=> fix(Button): fix disabled icon button bug in dark mode

src/Button/styles/index.less, src/styles/color-modes/dark.less, src/styles/color-modes/light.less
https://user-images.githubusercontent.com/1203827/212598572-3beca7cf-6dea-4f17-a70f-06a31cc08cb0.mp4
https://user-images.githubusercontent.com/1203827/212598594-e2fdb840-cf50-4f37-9958-a492af5ae472.mp4
=> fix(Button): improved button color when hovered and activated

docs/pages/components/select-picker/en-US/index.md
=> docs(SelectPicker): remove link from title

src/Breadcrumb/styles/index.less, src/Breadcrumb/test/BreadcrumbItemStylesSpec.tsx, src/styles/color-modes/dark.less, src/styles/color-modes/high-contrast.less, src/styles/color-modes/light.less
=> fix(Breadcrumb): improve font color for active item

src/@types/global.d.ts, src/Overlay/OverlayTrigger.tsx, src/Overlay/test/OverlayTriggerSpec.tsx, src/Whisper/test/Whisper.test.tsx, test/chai-assertions.js
fix: https://github.com/rsuite/rsuite/issues/3008
=> fix(Whisper): add type checking for child components

src/locales/index.ts, src/locales/nl_NL.ts
Added the Dutch locale (nl_NL)
=> feat: added Dutch locale (nl_NL)

src/Drawer/test/DrawerBodySpec.tsx
=> test(Drawer): test Drawer.Body ref is HTMLDivElement

src/Navbar/NavbarDropdown.tsx, src/Navbar/test/NavbarSpec.tsx
=> fix(Nav.Menu): open with hover trigger in Navbar

src/InputPicker/InputPicker.tsx, src/TagInput/index.tsx, src/TagInput/test/TagInputSpec.tsx
=> Fix issue 3042

docs/pages/components/form-validation/fragments/custom-form-control.md, docs/pages/components/form-validation/index.tsx, src/FormControl/FormControl.tsx, src/FormControl/test/FormControlSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3036#issuecomment-1408365439
=> fix(Form.Control): fix `acceptor` prop can not accept `Toggle`

docs/pages/guide/i18n/en-US/index.md, docs/pages/guide/i18n/fragments/example.md, docs/pages/guide/i18n/index.tsx, docs/pages/guide/i18n/zh-CN/index.md, src/locales/index.ts
=> docs(i18n): add guidance on support Dutch

docs/pages/guide/introduction/en-US/index.md, docs/pages/guide/v5-features/en-US/index.md, docs/pages/guide/v5-features/zh-CN/index.md
=> docs(guide): fix document formatting and errors

src/Schema/Schema.ts, src/Schema/test/Schema.test.ts
=> fix(Schema): add missing Types.MixedType

docs/utils/mock.ts
=> chore: replace deprecated API in @faker-js/faker

docs/package-lock.json, docs/package.json, docs/pages/_app.tsx
Enable Vercel Analytics in docs site follow this guide https://vercel.com/docs/concepts/analytics/audiences/quickstart
See dashboard at https://vercel.com/rsuite/rsuite-nextjs/analytics/audience
=> chore(docs): add vercel analytics integration

docs/package-lock.json, docs/package.json
The latest version fixes a problem, more details: https://github.com/rsuite/document-nav/pull/49.
=> docs(deps): upgrade document-nav@1.0.18

docs/pages/components/dropdown/en-US/index.md, docs/pages/components/dropdown/zh-CN/index.md
=> docs(Dropdown.Item): fix the default type of as

src/AutoComplete/AutoComplete.tsx, src/AutoComplete/test/AutoCompleteSpec.tsx
=> fix(AutoComplete): fix readOnly not work

package-lock.json, package.json, src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.tsx, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx, src/Sidenav/test/SidenavSpec.tsx, src/utils/dateUtils.ts, src/utils/deprecatePropType.ts
=> refactor(DatePicker,DateRangePicker): rename prop disabledDate -> isDateDisabled

src/Cascader/Cascader.tsx, src/Cascader/test/CascaderSpec.tsx
Fixed #3130 
- fix typo 
- fix infinite load state on inline mode
=> fix(Cascader): fix infinite load state on inline mode and fix typo

docs/pages/components/date-picker/en-US/index.md, docs/pages/components/date-picker/zh-CN/index.md, docs/pages/components/date-range-picker/en-US/index.md, docs/pages/components/date-range-picker/zh-CN/index.md, package-lock.json, package.json
Update docs for renamed props on DatePicker and DateRangePicker in #3102
=> docs(DatePicker,DateRangePicker): rename disabled* props

src/Calendar/CalendarHeader.tsx, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/DateRangePickerContext.ts, src/DateRangePicker/test/DateRangePickerSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3128
=> fix(DateRangePicker): fix the error of invalid time during date selection

package-lock.json, package.json
https://github.com/rsuite/rsuite-table/releases/tag/5.10.3
=> build(deps): bump rsuite-table from 5.10.1 to 5.10.3

src/Calendar/Calendar.tsx, src/Calendar/CalendarContainer.tsx, src/Calendar/styles/index.less, src/Calendar/test/CalendarSpec.tsx, src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.tsx, src/DateRangePicker/Calendar.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx
> UI design: https://rsuite.vercel.app/design/default/#s93
=> fix(Calendar): fix style errors that are not as designed

docs/pages/components/nav/fragments/responsive-nav.md
Prevent the overlap of responsive-nav with the sidebar.
close #3142
=> update responsive -nav.md

docs/pages/components/toggle/fragments/loading.md, docs/pages/components/toggle/index.tsx, src/Toggle/styles/mixin.less
=> fix(Toggle): fix spinner size in sm/lg Toggles

src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.tsx
=> fix(DatePicker): fix defaultValue not changing month on calendar

src/CheckPicker/test/CheckPickerSpec.tsx, src/Picker/utils.ts
fix: https://github.com/rsuite/rsuite/issues/3166
=> fix(pickers): fix keyboard events still responding when readOnly

package-lock.json, package.json
https://github.com/rsuite/rsuite-table/releases/tag/5.10.5
=> build(deps): bump rsuite-table from 5.10.4 to 5.10.5

docs/package-lock.json, docs/pages/components/timeline/en-US/index.md, docs/pages/components/timeline/fragments/custom-active-item.md, docs/pages/components/timeline/zh-CN/index.md
Fulfill this PR after #3198 is released.
=> docs(Timeline): add example and description for isItemActive props

docs/components/Frame.tsx, docs/components/SideNavbar/SideNavbar.tsx
=> fix(docs): sidebar cannot open the problem

docs/components/TopLevelNav/TopLevelNav.tsx
=> fix(docs): wrong menuToggle style in RTL direction

src/Dropdown/test/DropdownSpec.tsx
=> test(Dropdown): fix `Forbidden non-null assertion`

src/TreePicker/styles/index.less
https://github.com/rsuite/rsuite/assets/1203827/6ac86639-9082-4994-baac-20924ded665c
> https://rsuitejs.com/components/tree-picker/#disabled-and-read-only
=> fix(TreePicker): fix tree node disabled still can interact

docs/pages/components/button/zh-CN/index.md
=> docs: fix the confusing document of the Button component

src/InputPicker/InputPicker.tsx, src/TagInput/test/TagInputSpec.tsx
ignore key press while composing.
close #3243
=> fix(TagInput): fix tag create during text composing

src/locales/index.ts, src/locales/ja_JP.ts
=> feat: added Japanese locale (ja_JP) 

src/MultiCascader/MultiCascader.tsx
Remove unnecessary console.log statements of MultiCascader.
=> chore(MultiCascader): remove console.log

docs/pages/components/modal/en-US/index.md, docs/pages/components/modal/zh-CN/index.md
Close #3250 
See https://github.com/rsuite/rsuite/issues/3250#issuecomment-1610934457
=> docs(Modal): change default value of size prop to sm

package-lock.json, package.json
https://github.com/rsuite/rsuite-table/releases/tag/5.11.0
=> build(deps): bump rsuite-table from 5.10.6 to 5.11.0

.github/workflows/nodejs-ci.yml, package.json
Lint job only need to be run once
=> ci: separate lint job from test job

docs/pages/components/input-picker/fragments/custom.md, docs/pages/components/input-picker/index.tsx
=> docs(InputPicker): fix sample data is incomplete

src/locales/index.ts, src/locales/ne_NP.ts
locale for Nepali language added.
=> Create ne_NP.ts for Nepali Locale Support.

package-lock.json, package.json, src/CheckTreePicker/CheckTreePicker.tsx, src/CheckTreePicker/test/CheckTreePickerSpec.tsx, src/CheckTreePicker/utils.ts, src/utils/treeUtils.ts
This PR picks several changes from main (next major version under development) to 5.x (current major version).
After merging this, a new v5 version is going to be released.
=> Pick changes to v5

src/InputGroup/InputGroup.tsx, src/InputGroup/test/InputGroupSpec.tsx, src/Modal/ModalHeader.tsx, src/Picker/PickerToggleTrigger.tsx
fix: https://github.com/rsuite/rsuite/issues/3393
=> fix(InputGroup): fix child element's event not firing after InputGroup is disabled

src/Button/test/ButtonStylesSpec.tsx, src/Nav/test/NavItemStylesSpec.tsx, src/styles/color-modes/light.less
=> feat(Button,Nav): improved font color contrast in subtle appearance

src/utils/getDOMNode.ts
fix https://github.com/rsuite/rsuite/issues/3248
=> fix: add a safety check for the deprecated findDOMNode

src/Form/Form.tsx, src/Form/FormContext.tsx, src/FormControl/FormControl.tsx, src/FormControl/test/FormControlSpec.tsx
refer: https://github.com/rsuite/rsuite/pull/3399
close #3390
=> fix(form): form doesn't pass correct formValue to context  #3390

src/AutoComplete/AutoComplete.tsx, src/AutoComplete/test/AutoCompleteSpec.tsx
=> fix(AutoComplete): fix AutoComplete plaintext mode not working

src/toaster/test/useToasterSpec.tsx, src/toaster/useToaster.ts
fix: https://github.com/rsuite/rsuite/issues/3349
=> fix(toaster): fix useToaster not keep same reference when re-renders

src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.tsx, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx, src/Picker/PickerToggle.tsx
fix: https://github.com/rsuite/rsuite/issues/3443
=> fix(DatePicker,DateRangePicker): fix inability to clear values via Backspace key

package-lock.json, package.json
* **Table:** fix the compatibility issue with verticalAlign ([#435](https://github.com/rsuite/rsuite-table/issues/435)) ([2ed844c](https://github.com/rsuite/rsuite-table/commit/2ed844c67bcb440b55c652de9acc994c3badd108))
=> build(deps): bump rsuite-table from 5.15.0 to 5.16.0

src/Button/styles/index.less
fix: https://github.com/rsuite/rsuite/issues/3448
=> fix(Button): fix button radius using wrong less variable

docs/pages/components/table/en-US/index.md, docs/pages/components/table/zh-CN/index.md, package-lock.json, package.json
* **Table:** support get scroll position of the table through ref ([#473](https://github.com/rsuite/rsuite-table/issues/473)) ([8f44c93](https://github.com/rsuite/rsuite-table/commit/8f44c93fe465504e545039d6861c1f13421c37b8))
=> build(deps): bump rsuite-table from 5.16.0 to 5.17.0

src/styles/color-modes/dark.less, src/styles/color-modes/high-contrast.less
fix: https://github.com/rsuite/rsuite/issues/3473
=> fix(CSS): fix CSS calc syntax compatibility issue

docs/pages/components/tag-picker/en-US/index.md, docs/pages/components/tag-picker/fragments/custom.md, docs/pages/components/tag-picker/index.tsx, docs/pages/components/tag-picker/zh-CN/index.md, src/Checkbox/Checkbox.tsx, src/InputPicker/InputPicker.tsx, src/InputPicker/InputPickerContext.tsx, src/Picker/DropdownMenu.tsx, src/Picker/DropdownMenuCheckItem.tsx, src/TagInput/index.tsx, src/TagPicker/index.tsx, src/TagPicker/test/TagPickerSpec.tsx
Resolves #3468 
```tsx
<TagPicker
renderMenuItemCheckbox={checkboxProps => {
const { children, checked, ...restProps } = checkboxProps;
return (
<Checkbox checked={checked} {...restProps} indeterminate={checked}>
{children}
</Checkbox>
);
}}
/>
```
=> feat(TagPicker): add support for renderMenuItemCheckbox

src/List/test/ListSpec.tsx, src/List/test/ListStyleSpec.tsx
According to https://github.com/rsuite/rsuite/discussions/3200, made refactoring for a few test files.
Do you have plans to remove Karma from the project, and use Jest or something similar? Seems like Karma is already deprecated - https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes.
If yes, please let me know, and I can take a look how to make a smooth transition.
=> refactor(List): tests

docs/pages/components/carousel/fragments/appearance.md, docs/pages/components/drawer/fragments/backdrop.md, docs/pages/components/drawer/fragments/size.md, docs/pages/components/form-validation/fragments/custom-check-trigger.md, docs/pages/components/form/fragments/status.md, docs/pages/components/modal/fragments/backdrop.md, docs/pages/components/radio/fragments/radio-group-inline-picker.md
=> docs: fix `RadioGroup` style error when there is label inside

docs/pages/components/whisper/fragments/overlay.md, src/Overlay/OverlayTrigger.tsx, src/Overlay/test/OverlayTriggerSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3490
=> fix(Whisper): fix delay and other related props not working

src/Cascader/test/CascaderSpec.tsx, src/CheckPicker/test/CheckPickerSpec.tsx, src/CheckTreePicker/test/CheckTreePickerSpec.tsx, src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx, src/InputPicker/test/InputPickerSpec.tsx, src/MultiCascader/test/MultiCascaderSpec.tsx, src/SelectPicker/test/SelectPickerSpec.tsx, src/TagPicker/test/TagPickerSpec.tsx, src/TreePicker/test/TreePickerSpec.tsx, test/utils/testPickers.tsx
fix https://github.com/rsuite/rsuite/issues/3508 and remove redundant tests
=> fix(DatePicker): fix `menuStyle` prop not working

babel.config.js, package-lock.json, package.json
fix: https://github.com/rsuite/rsuite/issues/3520
=> fix(build): fix environment variable undefined error when building

src/CustomProvider/CustomProvider.tsx, src/utils/index.ts, src/utils/useIsomorphicLayoutEffect.ts
fix: https://github.com/rsuite/rsuite/issues/3514
=> fix(CustomProvider): fix the flicker when initializing in Dark mode

src/FormControl/FormControl.tsx, src/FormControl/test/FormControlSpec.tsx
The mysql json type in background development is becoming more and more common, and the one-dimensional data structure is difficult to meet the current business, so i write a wrapped FormControl component in my project like this do, if we can merge to origin that will he helpful..
(Non-breaking update, I wrote some test cases and tested the shouldResetWithUnmound configuration)
=> FormControl multi-dimensional data support

src/InputGroup/styles/index.less, src/styles/variables.less
fix: https://github.com/rsuite/rsuite/issues/3531
=> fix(InputGroup): fix style conflict caused by zIndex set in InputGoup

src/Calendar/CalendarContainer.tsx, src/DatePicker/test/DatePickerSpec.tsx, src/utils/dateUtils.ts
=> fix(DatePicker): fix DatePicker can't select after typing with keyboard

src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/index.tsx, src/DateRangePicker/test/DateRangePicker.test.tsx
fix: https://github.com/rsuite/rsuite/issues/3596
=> fix(DateRangePicker): fix incorrect static method type definition

docs/pages/components/dropdown/fragments/submenu.md, src/Dropdown/DropdownItem.tsx, src/Dropdown/test/DropdownSpec.tsx, src/Nav/test/NavSpec.tsx, src/internals/Menu/Menu.tsx
fix: https://github.com/rsuite/rsuite/issues/3562
=> fix(Menu): fix the menuitem cannot be closed correctly when it contains child elements

docs/pages/components/message/en-US/index.md, docs/pages/components/message/fragments/basic.md, docs/pages/components/message/fragments/close.md, docs/pages/components/message/fragments/full.md, docs/pages/components/message/fragments/header.md, docs/pages/components/message/fragments/icons.md, docs/pages/components/message/fragments/types.md, docs/pages/components/message/fragments/with-toaster.md, docs/pages/components/message/index.tsx, docs/pages/components/message/zh-CN/index.md, src/Message/styles/index.less, src/Message/styles/mixin.less, src/Message/test/MessageStylesSpec.tsx, src/styles/color-modes/light.less, src/styles/variables.less
=> fix(Message): make the visual style of Message more prominent

src/internals/Picker/ListCheckItem.tsx
fix: https://github.com/rsuite/rsuite/issues/3613
=> fix(CheckPicker): remove debug script

src/CheckTree/test/CheckTreeSpec.tsx, src/CheckTreePicker/CheckTreePicker.tsx, src/Tree/test/TreeSpec.tsx, src/TreePicker/TreePicker.tsx
fix:  https://github.com/rsuite/rsuite/issues/3612
=> fix(Tree,CheckTree): fix `classPrefix` and `className` not working correctly

docs/pages/guide/usage/index.tsx, package-lock.json
fixes (#3619) : fixed ui of Install guide commands
=> fix: fixed issue with install guide page (#3619)

src/InputGroup/styles/index.less
fix: https://github.com/rsuite/rsuite/issues/3566
=> fix(InputGroup): fix Input padding issue in InputGroup

docs/pages/components/form/fragments/status.md, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3626
=> fix(DateRangePicker): fix error state when value is empty array

src/InputPicker/InputPicker.tsx, src/TagPicker/styles/index.less, src/TagPicker/test/TagPickerSpec.tsx
=> fix(TagPicker): fix the margin issue between tags in plaintext mode

docs/components/SideNavbar/SideNavbar.tsx, docs/components/scripts.ts, docs/less/index.less, docs/package-lock.json, docs/package.json, docs/pages/components/form-formik/en-US/index.md, docs/pages/components/form-formik/fragments/basic.md, docs/pages/components/form-formik/fragments/other-input-components.md, docs/pages/components/form-formik/fragments/usage.md, docs/pages/components/form-formik/fragments/validation.md, docs/pages/components/form-formik/fragments/yup-schema-validation.md, docs/pages/components/form-formik/index.tsx, docs/pages/components/form-formik/zh-CN/index.md, docs/pages/components/form-validation/fragments/custom-form-control.md, docs/utils/component.config.json, src/FormGroup/styles/index.less
https://rsuite-nextjs-git-docs-formik-rsuite.vercel.app/components/form-formik/
=> docs(form): add guide for integration with formik

docs/pages/components/input-number/en-US/index.md, docs/pages/components/input-number/fragments/basic.md, docs/pages/components/input-number/fragments/combination.md, docs/pages/components/input-number/fragments/controlled.md, docs/pages/components/input-number/fragments/decimals.md, docs/pages/components/input-number/fragments/disabled.md, docs/pages/components/input-number/fragments/formatter.md, docs/pages/components/input-number/fragments/max-min.md, docs/pages/components/input-number/fragments/size.md, docs/pages/components/input-number/fragments/step.md, docs/pages/components/input-number/index.tsx, docs/pages/components/input-number/zh-CN/index.md, src/InputNumber/InputNumber.tsx, src/InputNumber/test/InputNumberSpec.tsx
https://rsuite-nextjs-git-feat-input-numberformatter-rsuite.vercel.app/components/input-number/#formatter
=> feat(InputNumber): add support for `formatter` on `<InputNumber>`

docs/pages/components/pagination/en-US/index.md, docs/pages/components/pagination/zh-CN/index.md, src/Pagination/LimitPicker.tsx, src/Pagination/Pagination.tsx, src/Pagination/PaginationButton.tsx, src/Pagination/PaginationGroup.tsx, src/Pagination/styles/pagination-group.less, src/Pagination/test/PaginationButtonSpec.tsx, src/Pagination/test/PaginationGroupSpec.tsx, src/Pagination/test/PaginationSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3050
=> fix(Pagination): fix SelectPicker rendering misalignment

src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3646
=> fix(DateRangePicker): fix time picker does not update when clicking the shortcut item

docs/pages/components/slider/fragments/value.md, docs/pages/components/slider/fragments/vertical.md, package-lock.json, package.json, src/Cascader/DropdownMenu.tsx, src/Cascader/TreeView.tsx, src/RangeSlider/RangeSlider.tsx, src/Slider/Handle.tsx, src/Slider/ProgressBar.tsx, src/Slider/Slider.tsx, src/Slider/test/HandleSpec.tsx, src/Slider/test/SliderSpec.tsx, src/Slider/test/SliderStylesSpec.tsx, src/Slider/useDrag.ts, src/Slider/utils.ts
fix: https://github.com/rsuite/rsuite/issues/3644
=> fix(Slider,RangeSlider): fix touch event not working

src/Calendar/styles/index.less, src/DatePicker/styles/index.less
=> fix(Calendar): fix misalignment of month selection menu layout

src/DatePicker/DatePicker.tsx, src/DatePicker/styles/index.less, src/DatePicker/test/DatePickerStylesSpec.tsx, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/styles/index.less, src/DateRangePicker/test/DateRangePickerStylesSpec.tsx
=> fix(DatePicker,DateRangePicker): fix the problem of padding

src/InlineEdit/InlineEdit.tsx
fix: https://github.com/rsuite/rsuite/issues/3683
=> fix(InlineEdit): fix type conflict for defined `children`

src/DateInput/DateField.ts, src/DateInput/test/DateInputSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3715
=> fix(DatePicker,DateRangePicker): fix the date change when the input date is incomplete

src/Avatar/Avatar.tsx, src/AvatarGroup/AvatarGroup.tsx, src/AvatarGroup/styles/index.less, src/AvatarGroup/test/AvatarGroupSpec.tsx, src/AvatarGroup/test/AvatarGroupStylesSpec.tsx
=> fix(AvatarGroup): fix avatar deformation in group

src/CheckPicker/test/CheckPickerSpec.tsx, src/Checkbox/Checkbox.tsx, src/Checkbox/styles/index.less, src/Checkbox/test/CheckboxStylesSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3724
=> fix(Checkbox): fix Checkbox not clickable in Firefox

src/Sidenav/styles/index.less, src/Sidenav/test/SidenavStylesSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3731
=> fix(Sidenav): fix secondary menu cannot expand

docs/pages/components/placeholder/en-US/index.md, docs/pages/components/placeholder/fragments/graph-square.md, docs/pages/components/placeholder/fragments/paragraph-graph.md, docs/pages/components/placeholder/fragments/paragraph-image.md, docs/pages/components/placeholder/fragments/paragraph-square.md, docs/pages/components/placeholder/zh-CN/index.md, src/Placeholder/PlaceholderGraph.tsx, src/Placeholder/PlaceholderGrid.tsx, src/Placeholder/PlaceholderParagraph.tsx, src/Placeholder/styles/index.less, src/Placeholder/styles/mixin.less, src/Placeholder/test/PlaceholderGraphSpec.tsx, src/Placeholder/test/PlaceholderGraphStylesSpec.tsx, src/Placeholder/test/PlaceholderGridSpec.tsx, src/Placeholder/test/PlaceholderGridStylesSpec.tsx, src/Placeholder/test/PlaceholderParagraphSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3733
=> fix(Placeholder): fix Placeholder SSR and CSR mismatch

package-lock.json, package.json
* https://github.com/rsuite/schema-typed/pull/80
=> build: security upgrade schema-typed from 2.2.1 to 2.2.2

.github/workflows/nodejs-ci.yml
=> ci: add token for codecov/codecov-action

docs/pages/components/date-range-picker/en-US/index.md, docs/pages/components/date-range-picker/fragments/show-only-calendar.md, docs/pages/components/date-range-picker/zh-CN/index.md, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/DateRangePickerContext.ts, src/DateRangePicker/Header.tsx, src/DateRangePicker/disabledDateUtils.ts, src/DateRangePicker/index.tsx, src/DateRangePicker/styles/index.less, src/DateRangePicker/test/DateRangePickerSpec.tsx
https://github.com/rsuite/rsuite/assets/1203827/c91ee438-2225-4fe6-901c-2b1c1012c023
fix: https://github.com/rsuite/rsuite/issues/3739
=> fix(DateRangePicker): fix the end time cannot be changed when only one calendar is displayed

docs/pages/components/date-picker/fragments/disabled.md, src/Calendar/CalendarContainer.tsx, src/DatePicker/DatePicker.tsx, src/DatePicker/PredefinedRanges.tsx, src/DatePicker/Toolbar.tsx, src/DatePicker/hooks/useFocus.ts, src/DatePicker/hooks/useMonthView.ts, src/DatePicker/index.tsx, src/DatePicker/test/DatePickerSpec.tsx, src/DatePicker/types.ts, src/DatePicker/utils.ts, src/DateRangePicker/DateRangePicker.tsx, src/utils/dateUtils.ts
fix: https://github.com/rsuite/rsuite/issues/3717
=> fix(DatePicker): fix disabled date and month can be selected

docs/components/AppContext.tsx, docs/components/CodeView/CodeView.tsx, docs/components/Frame.tsx, docs/components/IconList/IconList.tsx, docs/components/PageContainer/PageContainer.tsx, docs/components/PageContent.tsx, docs/components/PageToolbar/MoreActions.tsx, docs/components/PageToolbar/PageToolbar.tsx, docs/components/PageToolbar/SwitchTheme.tsx, docs/components/SideNavbar/SideNavbar.tsx, docs/components/TopLevelNav/TopLevelNav.tsx, docs/locales/en-US/index.ts, docs/locales/index.ts, docs/locales/zh-CN/index.ts, docs/pages/_app.tsx, docs/pages/_error.tsx, docs/pages/components/icon-button/en-US/index.md, docs/pages/components/overview/index.tsx, docs/pages/index.tsx, docs/pages/resources/design/index.tsx, docs/pages/resources/extensions/index.tsx, docs/pages/resources/icons/index.tsx, docs/utils/usePages.tsx
=> docs: add link to request new components

src/TagPicker/styles/index.less
=> fix(TagPicker): fix misalignment of large size tag with textbox

src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3775
fix: https://github.com/rsuite/rsuite/discussions/3617#discussioncomment-9281912
=> fix(DateRangePicker): fix not updating time on calendar when typing to change time

src/DateRangePicker/styles/index.less
=> fix(DateRangePicker): fix calendar panel vertical display

src/Placeholder/styles/index.less
fix: https://github.com/rsuite/rsuite/issues/3802
=> fix(Placeholder.Grid): fix `active` not working

docs/pages/components/date-picker/fragments/custom.md, src/DateRangePicker/styles/index.less
=> fix(DatePicker): fix calendar component style issue

docs/pages/components/calendar/fragments/week-start.md, docs/pages/components/modal/fragments/overflow.md, docs/pages/components/multi-cascader/fragments/cascade.md, docs/pages/components/pagination/fragments/advanced.md, docs/pages/components/tag/en-US/index.md, docs/pages/components/tag/zh-CN/index.md, docs/pages/components/toggle/en-US/index.md, docs/pages/components/toggle/fragments/color.md, docs/pages/components/toggle/fragments/disabled.md, docs/pages/components/toggle/fragments/inner.md, docs/pages/components/toggle/fragments/loading.md, docs/pages/components/toggle/fragments/size.md, docs/pages/components/toggle/fragments/with-label.md, docs/pages/components/toggle/index.tsx, docs/pages/components/toggle/zh-CN/index.md, src/Toggle/Toggle.tsx, src/Toggle/styles/index.less, src/Toggle/styles/mixin.less, src/Toggle/test/ToggleSpec.tsx
=> feat(Toggle): add support for color and children

.github/workflows/notify-twitter.yml
=> ci: add a Github Action to send Twitter notifications

src/DateInput/DateField.ts, src/DateInput/DateInput.tsx, src/DateInput/hooks/useFieldCursor.ts, src/DateInput/test/DateInputSpec.tsx, src/DateInput/test/testUtils.tsx, src/DatePicker/test/DatePickerSpec.tsx, src/DateRangeInput/DateRangeInput.tsx, src/DateRangeInput/test/DateRangeInputSpec.tsx
fix https://github.com/rsuite/rsuite/issues/3828
=> fix(DateInput,DateRangeInput): fix date input error when manually input date

package-lock.json, package.json
https://github.com/rsuite/rsuite-table/releases/tag/5.18.3
=> build(deps): bump rsuite-table from 5.18.2 to 5.18.3

src/Drawer/Drawer.tsx, src/Modal/Modal.tsx, src/Modal/test/ModalInDrawerSpec.tsx, src/Modal/utils.ts
fix: https://github.com/rsuite/rsuite/issues/3830
=> fix(Modal): fix `overflow` not working when Modal is in Drawer

examples/with-nextjs-app/package-lock.json, examples/with-nextjs-app/package.json, package-lock.json, package.json
fix: https://github.com/rsuite/rsuite/issues/3842
=> fix: remove unnecessary dependencies

docs/pages/components/panel/en-US/index.md, docs/pages/components/panel/zh-CN/index.md, src/Panel/PanelBody.tsx, src/Panel/test/PanelSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/1258
=> fix(Panel): fix unable to add className to PanelBody

docs/pages/components/stack/fragments/divider.md, docs/pages/components/stack/fragments/interactive.md, docs/pages/components/stack/index.tsx, docs/utils/component.config.json, src/Divider/styles/index.less
```tsx
const App = () => {
return (
<Stack divider={<Divider />} direction="column" alignItems="flex-start">
<Button>Item 1</Button>
<Stack divider={<Divider vertical />} style={{ height: 40 }}>
<Button>Item 2</Button>
<Button>Item 3</Button>
<Button>Item 4</Button>
</Stack>
</Stack>
);
};
```
=> fix(Divider): fix Stack horizontal divider not working

src/DatePicker/DatePicker.tsx, src/DateRangePicker/DateRangePicker.tsx, src/internals/Picker/styles/index.less, src/styles/color-modes/light.less
fix: https://github.com/rsuite/rsuite/issues/3851
=> fix(DatePicker,DateRangePicker): fix the priority of the style in the error state

src/Table/styles/index.less, src/styles/color-modes/dark.less, src/styles/color-modes/high-contrast.less, src/styles/color-modes/light.less
=> fix(Table): fix table row border not full

docs/less/index.less, src/styles/color-modes.less, src/styles/mixins/color-modes.less, src/styles/variables.less
Fixes https://github.com/rsuite/rsuite/issues/3860
=> fix(theme): add less variable to opt-out of high-contrast theme bundling

src/FormControl/hooks/useField.ts, src/FormControl/test/FormControlSpec.tsx
close  https://github.com/rsuite/rsuite/issues/3866
=> fix: errorMessage isn't shown when using ArrayType().of

src/AutoComplete/test/AutoCompleteStylesSpec.tsx, src/Stack/Stack.tsx, src/Stack/test/StackSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3883
=> fix(Stack): fix StackItem cannot be rendered correctly in server-side rendering

src/DateInput/DateField.ts, src/DateInput/DateInput.tsx, src/DateInput/hooks/useDateInputState.ts, src/DateInput/hooks/useKeyboardInputEvent.ts, src/DateInput/test/DateInputSpec.tsx, src/DateRangeInput/DateRangeInput.tsx, src/DateRangeInput/test/DateRangeInputSpec.tsx, test/mocks/data-mock.tsx
fix: https://github.com/rsuite/rsuite/issues/3887
=> fix(DateInput,DateRangeInput): fix the date in the text box cannot be copied

src/internals/utils/BrowserDetection.ts
fix: https://github.com/rsuite/rsuite/issues/3885
=> fix(Stack): fix the compatibility of spacing in Linux Firefox

src/Whisper/test/Whisper.test.tsx, src/internals/Overlay/OverlayTrigger.tsx, src/internals/Overlay/test/OverlayTriggerSpec.tsx, src/internals/utils/ReactChildren.tsx
```tsx
<Whisper speaker={<Tooltip>1000 comments</Tooltip>}>{1000}</Whisper>
```
=> fix(Whisper): fix Whisper children not support string and other basic types

docs/package-lock.json, docs/package.json, docs/pages/components/calendar/en-US/index.md, docs/pages/components/calendar/fragments/compact.md, docs/pages/components/calendar/fragments/lunar.md, docs/pages/components/calendar/fragments/week-start.md, docs/pages/components/calendar/index.tsx, docs/pages/components/calendar/zh-CN/index.md
> https://rsuite-nextjs-git-docs-calendar-lunar-rsuite.vercel.app/components/calendar/#lunar
=> docs(Calendar): add example for lunar

src/useMediaQuery/useMediaQuery.ts
fix: https://github.com/rsuite/rsuite/issues/3908
=> fix(useMediaQuery): fix media query change cannot be listened to when using multiple useMediaQuery

src/CustomProvider/CustomProvider.tsx, src/DateInput/hooks/useDateInputState.ts, src/DatePicker/test/DatePickerSpec.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx, src/internals/hooks/useCustom.ts
fix: https://github.com/rsuite/rsuite/issues/3869
=> fix(DatePicker, DateRangePicker): fix the component crash due to invalid format

docs/pages/components/table/en-US/index.md, docs/pages/components/table/fragments/appearance.md, docs/pages/components/table/fragments/edit.md, docs/pages/components/table/fragments/height.md, docs/pages/components/table/fragments/loading.md, docs/pages/components/table/index.tsx, docs/pages/components/table/zh-CN/index.md, docs/utils/mock.ts, package-lock.json, package.json, storybook/mocks/index.ts
* **Table:** add support for `maxHeight` prop ([#498](https://github.com/rsuite/rsuite-table/issues/498)) ([1d3598d](https://github.com/rsuite/rsuite-table/commit/1d3598d99a4d3e0599fdeffede2d0529fe32ce6a))
=> build(deps): bump rsuite-table from 5.18.3 to 5.19.0

src/Cascader/test/CascaderSpec.tsx, src/CheckPicker/test/CheckPickerSpec.tsx, src/CheckTreePicker/test/CheckTreePickerSpec.tsx, src/MultiCascader/MultiCascader.tsx, src/MultiCascader/test/MultiCascaderSpec.tsx, src/SelectPicker/test/SelectPickerSpec.tsx, src/TreePicker/TreePicker.tsx, src/TreePicker/test/TreePickerSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3926
=> fix(TreePicker,MultiCascader): fix not focusing on the search box when typing characters

src/CascadeTree/CascadeTree.tsx, src/CascadeTree/SearchView.tsx, src/CascadeTree/types.ts, src/Cascader/Cascader.tsx, src/Cascader/test/CascaderSpec.tsx, src/MultiCascadeTree/MultiCascadeTree.tsx, src/MultiCascadeTree/SearchView.tsx, src/MultiCascadeTree/types.ts, src/MultiCascader/MultiCascader.tsx, src/MultiCascader/test/MultiCascaderSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3925
=> fix(Cascader,MultiCascader): fix `locale` property can't override global config

package-lock.json, package.json, src/Table/styles/index.less
=> fix(Table): fix border style when rowSpan is used

src/Breadcrumb/Breadcrumb.tsx, src/Breadcrumb/test/BreadcrumbSpec.tsx, src/internals/utils/ReactChildren.tsx, src/internals/utils/test/ReactChildrenSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3945
=> fix(Breadcrumb): fix the rendering exception of the child node separator

src/Form/Form.tsx, src/Form/hooks/useFormValidate.ts, src/Form/hooks/useSchemaModel.ts, src/FormControl/hooks/useField.ts, src/FormControl/test/FormControlSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3957
fix: https://github.com/rsuite/rsuite/issues/3958
=> fix(Form): fix the error message of the nested field not displayed when the form is submitted

docs/pages/components/date-range-picker/en-US/index.md, docs/pages/components/date-range-picker/zh-CN/index.md, src/DatePicker/DatePicker.tsx, src/DatePicker/test/DatePickerSpec.tsx, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx
close: https://github.com/rsuite/rsuite/issues/3959#issuecomment-2345620988
=> feat(DateRangePicker): add support for `hideHours`, `hideMinutes`, `hideSeconds`

docs/components/CategorizedList.tsx, docs/components/SideNavbar/NavGroup.tsx, docs/components/SideNavbar/SideNavbar.tsx, docs/components/SideNavbar/styles.less, docs/components/SortedList.tsx, docs/pages/components/overview/index.tsx, docs/utils/component.config.json, docs/utils/usePages.tsx
=> docs: support nested collapse in navigation menu

docs/pages/components/check-picker/fragments/virtualized.md, docs/pages/components/select-picker/fragments/virtualized.md, src/internals/Picker/Listbox.tsx, src/internals/Picker/styles/index.less
fix: https://github.com/rsuite/rsuite/issues/3983
=> fix(SelectPicker,CheckPicker): fix the virtual list option text being wrapped

src/DateInput/DateInput.tsx, src/DateInput/test/DateInputSpec.tsx, src/DateRangeInput/DateRangeInput.tsx, src/DateRangeInput/test/DateRangeInputSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/2762
=> fix(DateInput,DateRangeInput): fix the issue that the value cannot be cleared by the Backspace key

src/InlineEdit/renderChildren.tsx, src/InlineEdit/test/InlineEditSpec.tsx, src/InlineEdit/useFocusEvent.ts
fix: https://github.com/rsuite/rsuite/issues/3986
=> fix(InlineEdit): ix the issue that InputPicker needs to be clicked twice to focus

docs/pages/components/calendar/en-US/index.md, docs/pages/components/calendar/fragments/basic.md, docs/pages/components/calendar/fragments/compact.md, docs/pages/components/calendar/fragments/custom-cell.md, docs/pages/components/calendar/fragments/week-start.md, docs/pages/components/calendar/index.tsx, docs/pages/components/calendar/zh-CN/index.md, src/Calendar/styles/index.less, src/Calendar/test/CalendarStyleSpec.tsx, src/DatePicker/styles/index.less, src/styles/variables.less
=> fix(Calendar): fix the week not aligning in the cell

docs/pages/components/calendar/fragments/lunar.md, docs/pages/components/calendar/fragments/week-start.md, src/Calendar/MonthDropdown/MonthDropdown.tsx, src/Calendar/MonthDropdown/MonthDropdownItem.tsx, src/Calendar/MonthDropdown/index.tsx, src/Calendar/styles/index.less, src/Calendar/test/CalendarMonthDropdownItemSpec.tsx, src/Calendar/utils/index.ts, src/Calendar/utils/isEveryDateInMonth.ts, src/DatePicker/DatePicker.tsx, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/styles/index.less
=> feat(Calendar): support localized month calendar

.github/workflows/nodejs-publish.yml
https://docs.npmjs.com/generating-provenance-statements
=> ci: add GitHub provenance for publishing

src/Calendar/hooks/useCalendarState.ts, src/Calendar/test/CalendarContainerSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/3996
=> fix(Calendar): fix not triggering the `onToggleTimeDropdown` event when collapsing the time panel

src/CheckTree/test/CheckTreeSpec.tsx, src/internals/hooks/useFocusVirtualListItem.ts
fix: https://github.com/rsuite/rsuite/issues/4014
=> fix(CheckTree): fix focus lost when search keyword matches selected item

docs/components/IconList/IconModal.tsx, docs/less/pages/resources/icons.less
=> docs(icons): fix the style problem of the icon preview page

docs/less/markdown.less, src/DateRangePicker/DateRangePicker.tsx, src/DateRangePicker/test/DateRangePickerSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/4038
=> fix(DateRangePicker): fix the date range is not restored after deselecting

gulpfile.js, package.json
fix: https://github.com/rsuite/rsuite/issues/4040
=> fix(CSS): fix the problem of failing to load index.css.map

babel.config.js, src/Panel/AccordionButton.tsx, src/Panel/test/PanelSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/4043
=> fix(Panel): fix AccordionButton missing type causing form submission

docs/components/FakeBrowser/FakeBrowser.tsx, docs/components/FakeBrowser/styles.less
=> docs: add support for full screen on FakeBrowser

docs/pages/components/list/en-US/index.md, docs/pages/components/list/fragments/collection.md, docs/pages/components/list/fragments/custom.md, docs/pages/components/list/fragments/default.md, docs/pages/components/list/fragments/no-divider.md, docs/pages/components/list/fragments/size.md, docs/pages/components/list/fragments/sort-fixed.md, docs/pages/components/list/fragments/sortable.md, docs/pages/components/list/index.tsx, docs/pages/components/list/zh-CN/index.md, src/List/List.tsx, src/List/ListItem.tsx, src/List/styles/index.less, src/List/test/ListItemSpec.tsx, src/List/test/ListSpec.tsx, src/Stack/HStack.tsx, src/Stack/VStack.tsx
https://rsuite-nextjs-git-feat-list-divider-rsuite.vercel.app/components/list/#no-divider
=> feat(List): add support `divider` on List

.github/workflows/size-limit.yml, package-lock.json, package.json
This pull request introduces a new workflow to monitor the size of the built project and updates the `package.json` to include necessary dependencies and scripts for this functionality. The most important changes are:
* [`.github/workflows/size-limit.yml`](diffhunk://#diff-0e6e5ca89e96a26ead6e3deb4656444c810f6ba3838a573084d9f2ba78c0395aR1-R16): Added a new GitHub Actions workflow to check the size of the project on pull requests to the `main` and `next` branches.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R37): Added a new script `size` to run `size-limit` after building the project.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R100): Added the `@size-limit/preset-big-lib` …
=> ci: add size-limit

docs/pages/components/toaster/fragments/custom-container.md, src/CustomProvider/CustomProvider.tsx, src/internals/utils/index.ts, src/toaster/ToastContainer.tsx, src/toaster/render.ts, src/toaster/test/toasterSpec.tsx, src/toaster/toaster.tsx, src/useToaster/test/useToasterSpec.tsx, src/useToaster/useToaster.ts
https://github.com/user-attachments/assets/30266b84-0214-4921-a0a1-ae5e6939fea2
https://github.com/user-attachments/assets/2adf8818-e9b9-49f4-95fa-dba892168a56
=> fix(useToaster): support dynamic container of useToaster with correct styles

docs/pages/components/badge/en-US/index.md, docs/pages/components/badge/zh-CN/index.md, docs/pages/components/tag/en-US/index.md, docs/pages/components/tag/fragments/color.md, docs/pages/components/tag/zh-CN/index.md, src/Badge/Badge.tsx, src/Tag/Tag.tsx, src/Tag/styles/index.less, src/Tag/test/TagSpec.tsx, src/internals/types/colours.ts, src/internals/utils/colours.ts, src/internals/utils/css.ts, src/internals/utils/index.ts, src/internals/utils/test/coloursSpec.ts, src/internals/utils/test/cssSpec.ts
- Add support for custom color in Tag component
- Add createColorVariables utility function
- Add createOffsetStyles utility function
- Add tests for custom color functionality
- Update Badge component to use new utility functions
=> feat(Tag): support custom color

docs/pages/components/check-picker/fragments/loading.md, src/internals/Picker/styles/mixin.less
=> fix(Picker): fix loader icon position in different sizes

docs/pages/components/text/en-US/index.md, docs/pages/components/text/fragments/color.md, docs/pages/components/text/zh-CN/index.md, src/Text/Text.tsx, src/Text/styles/index.less, src/Text/test/TextSpec.tsx
This pull request introduces several updates to the `Text` component, including enhancements to color handling, documentation updates, and additional tests. The most important changes are summarized below:
* [`src/Text/Text.tsx`](diffhunk://#diff-bfe5e1afa05adb0aa45b08fbfb95c6eab5d2919288c370ddbb11305f1fdd9d89L1-R14): Updated the `color` prop to accept both preset colors and CSS color values. Added utility functions `mergeStyles`, `isPresetColor`, and `createColorVariables` to handle custom color styles. [[1]](diffhunk://#diff-bfe5e1afa05adb0aa45b08fbfb95c6eab5d2919288c370ddbb11305f1fdd9d89L1-R14) [[2]](diffhunk://#diff-bfe5e1afa05adb0aa45b08fbfb95c6eab5d2919288c370ddbb11305f1fdd9d89L72-R91)
* [`src/Text/styles/index.less`](diffhunk://#diff-20c80b43f0c0dbee594397709f2335de4f25d9746bb03a8d8 …
=> feat(Text): support custom color

.gitignore, docs/pages/components/form-validation/fragments/form-nested-fields.md, package-lock.json, package.json, src/Form/test/FormValidationSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/4129
This pull request includes updates to the form validation component and its dependencies. The main changes involve adding support for nested array validation, updating validation messages, and enhancing the test coverage for these new features. Additionally, there are updates to package dependencies.
Form validation improvements:
* [`docs/pages/components/form-validation/fragments/form-nested-fields.md`](diffhunk://#diff-59c19b79b0e8ab48a2086aee2b80a77fa793f52037f8c3bad4a35bfaae3f9a6cL19-R31): Added `ArrayType` to the schema and updated validation messages for better clarity. Introduced validation for nested array fields `skills`. [[1]](diffhunk://#diff-59c19b79b0e8ab48a2086aee2b80a77fa793f52037f8c3bad4a35bfaae3f9a6cL19-R31) …
=> fix(Form): validation for nested array fields

src/Cascader/test/Cascader.test.tsx, src/CheckPicker/CheckPicker.tsx, src/CheckPicker/test/CheckPicker.test.tsx, src/InputPicker/InputPicker.tsx, src/InputPicker/test/InputPicker.test.tsx, src/MultiCascader/MultiCascader.tsx, src/MultiCascader/test/MultiCascader.test.tsx, src/SelectPicker/SelectPicker.tsx, src/SelectPicker/index.tsx, src/SelectPicker/test/SelectPicker.test.tsx, src/TagPicker/index.tsx, src/TagPicker/test/TagPicker.test.tsx, src/internals/types/index.ts
fix: https://github.com/rsuite/rsuite/issues/3417
This pull request includes several changes to various components within the codebase, focusing on improving type safety, adding custom render functions, and enhancing component interfaces. The most important changes include modifications to `CheckPicker`, `InputPicker`, `MultiCascader`, `SelectPicker`, and `TagPicker` components.
=> fix(pickers): improve pickers `renderValue` property type definition

docs/pages/components/animation/fragments/bounce.md, docs/pages/components/animation/fragments/collapse.md, docs/pages/components/animation/fragments/fade.md, docs/pages/components/animation/fragments/slide.md, docs/pages/components/animation/fragments/transition.md, docs/pages/components/animation/index.tsx
- Update all animation examples with consistent Card-based design
- Add unique gradient backgrounds for each example
- Improve layout and typography across examples
- Add multiple transition effects (zoom, flip, rotate, bounce)
- Clean up and standardize code structure
=> feat(docs): enhance animation examples

docs/pages/components/container/examples/center.tsx, docs/pages/components/dropdown/fragments/with-popover.md, docs/pages/components/menu/fragments/description.md, docs/pages/components/nav/en-US/index.md, docs/pages/components/nav/zh-CN/index.md, docs/pages/components/navbar/en-US/index.md, docs/pages/components/navbar/fragments/mege-menu.md, docs/pages/components/navbar/index.tsx, docs/pages/components/navbar/zh-CN/index.md, src/Nav/AdaptiveNavItem.tsx, src/Nav/Nav.tsx, src/Nav/NavMegaMenu.tsx, src/Nav/NavMenu.tsx, src/Nav/index.tsx, src/Nav/test/NavMegaMenuSpec.tsx, src/Navbar/NavbarMegaMenu.tsx, src/Navbar/styles/index.less, src/Navbar/test/NavbarMegaMenuSpec.tsx, src/internals/types/html.ts
https://rsuite-nextjs-git-feat-megamenu-rsuite.vercel.app/components/navbar/#mega-menu
This pull request introduces a new `Nav.MegaMenu` component to the navigation system, along with updates to documentation and tests. The most important changes include the addition of the `Nav.MegaMenu` component, updates to the navigation bar documentation, and the implementation of new styles and tests for the component.
=> feat(Navbar): add support for Nav.MegaMenu

src/FormErrorMessage/styles/index.less
Replace font-size variable with radius variable for border-radius to follow design system standards
=> fix(FormErrorMessage): use standard radius variable

docs/components/FakeBrowser/styles.less, docs/pages/components/drawer/en-US/index.md, docs/pages/components/drawer/zh-CN/index.md, docs/pages/components/modal/en-US/index.md, docs/pages/components/modal/examples/index.tsx, docs/pages/components/modal/examples/responsive.tsx, docs/pages/components/modal/fragments/alert-dialog.md, docs/pages/components/modal/fragments/centered.md, docs/pages/components/modal/fragments/form.md, docs/pages/components/modal/index.tsx, docs/pages/components/modal/zh-CN/index.md, src/Image/test/ImageSpec.tsx, src/Modal/Modal.tsx, src/Modal/styles/index.less
- Modal supports centered display on the page
- Added examples for mobile devices
=> feat(Modal): add centered property and improve documentation for Modal and Drawer components

docs/pages/components/breadcrumb/en-US/index.md, docs/pages/components/breadcrumb/fragments/background.md, docs/pages/components/breadcrumb/fragments/icons.md, docs/pages/components/breadcrumb/fragments/max-items.md, docs/pages/components/breadcrumb/fragments/separator.md, docs/pages/components/breadcrumb/fragments/size.md, docs/pages/components/breadcrumb/index.tsx, docs/pages/components/breadcrumb/zh-CN/index.md, docs/pages/components/container/index.tsx, src/Breadcrumb/Breadcrumb.tsx, src/Breadcrumb/BreadcrumbItem.tsx, src/Breadcrumb/styles/index.less, src/Breadcrumb/test/BreadcrumbItemSpec.tsx, src/Breadcrumb/test/BreadcrumbItemStylesSpec.tsx, src/Breadcrumb/test/BreadcrumbSpec.tsx
- Added `size` property to Breadcrumb
- Added `icon` property to BreadcrumbItem
=> feat(Breadcrumb): enhance Breadcrumb component with size, icon support

src/useToaster/useToaster.ts
This pull request includes a small change to the `src/useToaster/useToaster.ts` file. The change updates the URL in the documentation comment to point to the correct page for the toaster component.
=> fix(useToaster): fix the incorrect @see link in the useToaster comment

docs/pages/components/slider/en-US/index.md, src/RangeSlider/RangeSlider.tsx, src/Slider/Handle.tsx, src/Slider/Slider.tsx, src/Slider/test/HandleSpec.tsx, src/Slider/useDrag.ts
=> feature for #4180: keepTooltipOpen

docs/pages/components/toggle/en-US/index.md, docs/pages/components/toggle/fragments/color.md, docs/pages/components/toggle/fragments/disabled.md, docs/pages/components/toggle/fragments/inner.md, docs/pages/components/toggle/fragments/loading.md, docs/pages/components/toggle/fragments/size.md, docs/pages/components/toggle/index.tsx, docs/pages/components/toggle/zh-CN/index.md, src/Toggle/Toggle.tsx, src/Toggle/styles/index.less, src/Toggle/test/ToggleSpec.tsx, src/styles/root.less, src/styles/variables.less
This pull request includes several updates to the `Toggle` component documentation and styles, introducing new size options and updating the layout of the examples. The most important changes include the addition of new size options, updates to the documentation examples, and modifications to the styles to support these new sizes.
=> feat(Toggle): add `xl` and `xs` values to `size` prop

src/List/List.tsx, src/List/helper/useSortHelper.ts, src/List/helper/utils.ts, src/List/test/ListSpec.tsx
fix: https://github.com/rsuite/rsuite/issues/4214
https://github.com/user-attachments/assets/4da926f7-2ca3-4d5d-94c7-0b2c36fba05e
- Fix mouse event tests with proper async handling using sinon timers
- Add error handling for getScrollingParent in test environment
- Fix document.body.style.overflow cleanup after tests
=> fix(List): fix sorting issue on mobile devices

src/Image/Image.tsx, src/Image/hooks/useImage.ts, src/Image/test/ImageSpec.tsx
This pull request includes significant updates to the `Image` component and its associated hooks and tests to improve loading, error handling, and lazy loading functionality.
fix: https://github.com/rsuite/rsuite/issues/4223
=> fix(Image): fix lazy loading not working

docs/pages/components/overview/styles.less, docs/pages/components/rate/en-US/index.md, docs/pages/components/rate/fragments/advanced-rating.md, docs/pages/components/rate/fragments/character.md, docs/pages/components/rate/fragments/color.md, docs/pages/components/rate/fragments/custom-character.md, docs/pages/components/rate/fragments/disabled.md, docs/pages/components/rate/fragments/fractional.md, docs/pages/components/rate/fragments/hover.md, docs/pages/components/rate/fragments/size.md, docs/pages/components/rate/fragments/vertical.md, docs/pages/components/rate/index.tsx, docs/pages/components/rate/zh-CN/index.md, src/Rate/Character.tsx, src/Rate/Rate.tsx, src/Rate/styles/index.less, src/Rate/test/RateSpec.tsx, src/Rate/types.ts, src/Rate/useRatingStates.ts, src/Rate/utils.ts, src/styles/color-modes/dark.less, src/styles/color-modes/high-contrast.less, src/styles/color-modes/light.less
https://rsuite-nextjs-git-feature-rate-fractional-rsuite.vercel.app/components/rate/#fractional-ratings
close: https://github.com/rsuite/rsuite/issues/3207
=> feat(rate): add fractional rating support

docs/pages/components/form-formik/fragments/other-input-components.md, docs/pages/components/form-formik/fragments/validation.md, docs/pages/components/form-formik/fragments/yup-schema-validation.md, docs/pages/components/form-react-hook-form/fragments/basic.md, docs/pages/components/form-react-hook-form/fragments/other-input-components.md, docs/pages/components/form-react-hook-form/fragments/validation.md, docs/pages/components/form-react-hook-form/fragments/yup-schema-validation.md
update all form-related demos to use <Form.Stack fluid>
- ensures consistent spacing/layout across formik, react-hook-form, yup-schema-validation, etc.
=> docs(form): unify demo layout with Form.Stack

docs/package-lock.json, docs/package.json, docs/pages/components/drawer/index.tsx, docs/pages/components/form-validation/index.tsx, docs/pages/components/form/index.tsx, docs/pages/components/link/index.tsx, docs/pages/components/modal/index.tsx, docs/pages/components/password-input/en-US/index.md, docs/pages/components/password-input/fragments/icons.md, docs/pages/components/password-input/index.tsx, docs/pages/components/password-input/zh-CN/index.md, docs/pages/components/textarea/index.tsx, src/PasswordInput/PasswordInput.tsx, src/PasswordInput/test/PasswordInputSpec.tsx
This pull request includes several changes to the documentation and implementation of the `PasswordInput` component, as well as minor updates to other components. The most important changes focus on the addition of new features to the `PasswordInput` component, including support for start and end icons, and the removal of unnecessary TypeScript comments.
* Added support for `startIcon` and `endIcon` props to the `PasswordInput` component, allowing users to set icons at the beginning and end of the input field. [[1]](diffhunk://#diff-3ae1e970149672db2e859fefdbc33b8cf2042cdddd670acb7bcaa5b2e5329483R17-R22) [[2]](diffhunk://#diff-3ae1e970149672db2e859fefdbc33b8cf2042cdddd670acb7bcaa5b2e5329483R46-R47) [[3]](diffhunk://#diff-3ae1e970149672db2e859fefdbc33b8cf2042cdddd670acb7bcaa5b2e5329483R64-R …
=> feat(PasswordInput): add startIcon and endIcon props

src/CustomProvider/CustomContext.tsx, src/CustomProvider/CustomProvider.tsx, src/CustomProvider/FormattedDate.tsx, src/CustomProvider/FormattedNumber.tsx, src/CustomProvider/index.tsx, src/CustomProvider/useCustom.ts, src/Image/hooks/useImage.ts, src/internals/CloseButton/CloseButton.tsx, src/internals/Picker/ListCheckItem.tsx, src/internals/Picker/ListItem.tsx, src/internals/Picker/ListItemGroup.tsx, src/internals/Picker/Listbox.tsx, src/internals/Picker/PickerIndicator.tsx, src/internals/Picker/PickerToggle.tsx, src/internals/Picker/hooks/usePickerRef.ts, src/internals/hooks/useClassNames.ts, src/useToaster/useToaster.ts
fix: https://github.com/rsuite/rsuite/discussions/4168
=> fix(vite): resolve circular dependency between chunks

docs/pages/components/navbar/en-US/index.md, docs/pages/components/navbar/examples/responsive.tsx, docs/pages/components/navbar/fragments/with-drawer.md, docs/pages/components/navbar/zh-CN/index.md, src/Navbar/NavbarToggle.tsx, src/Navbar/test/NavbarToggleSpec.tsx, src/internals/Burger/Burger.tsx, src/internals/Burger/index.tsx, src/internals/Burger/styles/index.less, src/internals/Burger/test/BurgerSpec.tsx, src/styles/index.less
This pull request introduces a new `Burger` component to replace the `IconButton` used in the `NavbarToggle` component, along with corresponding updates to documentation, tests, and styles. The changes improve the flexibility and customization of the navigation toggle button. Below are the most important changes grouped by theme:
* Replaced the `IconButton` in `NavbarToggle` with the new `Burger` component, allowing for better customization of the toggle button's appearance and behavior. The `NavbarToggle` now supports additional props like `lineThickness` and `color` for the burger lines (`src/Navbar/NavbarToggle.tsx`).
* Introduced the `Burger` component, which includes customizable styles, open/closed states, and support for custom elements via the `as` prop …
=> feat(Navbar.Toggle): add a new Burger component, applied to Navbar.Toggle

docs/pages/components/navbar/en-US/index.md, docs/pages/components/navbar/examples/responsive.tsx, docs/pages/components/navbar/fragments/appearance.md, docs/pages/components/navbar/zh-CN/index.md, docs/pages/components/stat/en-US/index.md, docs/pages/components/stat/examples/index.tsx, docs/pages/components/stat/examples/responsive.tsx, docs/pages/components/stat/index.tsx, docs/pages/components/stat/zh-CN/index.md
This pull request introduces updates to the documentation and examples for the `Navbar` and `Stat` components, focusing on improving responsiveness, enhancing example organization, and adding new features like simulation and formatting options.
=> docs: update examples of responsive components

src/locales/nl_NL.ts
See: https://github.com/rsuite/rsuite/issues/4255
=> fix: fixed some minor issue with dutch locale

docs/pages/components/message/en-US/index.md, docs/pages/components/message/zh-CN/index.md, docs/pages/components/notification/en-US/index.md, docs/pages/components/notification/zh-CN/index.md, docs/pages/components/toaster/en-US/index.md, docs/pages/components/toaster/zh-CN/index.md, src/useToaster/test/useToaster.spec.tsx, src/useToaster/useToaster.ts
- Add warning message when useToaster is used without a CustomProvider
- Add test case to verify the warning behavior
=> fix(useToaster): add warning when used outside of CustomProvider

src/locales/index.ts, src/locales/th_TH.ts
=> feat: [feature/th_TH-locale] add Thai [th_TH] locale

src/locales/gu_IN.ts, src/locales/th_TH.ts, src/locales/uk_UA.ts
- Fix date-fns locale imports to use named imports
- Add missing Dialog component translations for gu_IN, th_TH, and uk_UA
=> fix(locales): update date-fns imports and add Dialog translations

docs/components/scripts.ts, docs/styles/_carbonads.scss
- Add loading placeholder animation for Carbon Ads
- Improve dark mode support for better theme integration
- Update styles to use RSuite design tokens
- Fix positioning and layout issues
=> docs: enhance Carbon Ads with loading states and dark mode

src/CustomProvider/useCustom.ts, src/TimePicker/test/TimePickerSpec.tsx, src/TimeRangePicker/test/TimeRangePickerSpec.tsx
fix: https://github.com/rsuite/rsuite/discussions/4332
=> fix: allow TimePicker and TimeRangePicker locale prop to override global locale

docs/pages/components/whisper/en-US/index.md, docs/pages/components/whisper/en-US/props.md, docs/pages/components/whisper/fragments/basic.md, docs/pages/components/whisper/fragments/overlay.md, docs/pages/components/whisper/index.tsx, docs/pages/components/whisper/zh-CN/index.md, docs/pages/components/whisper/zh-CN/props.md
This pull request updates the documentation and examples for the `Whisper` component to improve clarity and usability. The changes include restructuring sections, enhancing examples, and refining the API documentation for better developer experience.
* **Updated section titles and descriptions**: Replaced "Overlay" with "Basic Usage" in the English and Chinese documentation, and added clearer descriptions for default supported speaker components (`Tooltip` and `Popover`). [[1]](diffhunk://#diff-01e794d86b001d85b8b3b7e8be819d9261265aeffb02f3df95ae688ccefed402L11-R19) [[2]](diffhunk://#diff-d4eaf924b293e514b91ee3cd65afbfa76594a087702688541d648bc9304dd20eR11-R20)
* **Enhanced API documentation**: Expanded the explanation of `Whisper` methods, including `open`, `close`, and `updatePosition`, …
=> docs(Whisper): update documentation and add basic examples

README.md, README_zh.md
This pull request adds a new badge to both the English and Chinese README files to promote the "Ask DeepWiki" feature. This badge provides a quick link for users to access DeepWiki resources related to the project.
Documentation updates:
* Added the "Ask DeepWiki" badge and link to the English `README.md` file.
* Added the "Ask DeepWiki" badge and link to the Chinese `README_zh.md` file.
=> docs(readme): update README.md and README_zh.md
