rsuite/rsuite

src/AutoComplete.js
test/AutoCompleteSpec.js

| name | type(default) | description |
| ----- | ----- | ----- |
| selectOnEnter |bool(true) | whether to select the focused item on Enter key pressed |

feat(AutoComplete): add 'selectOnEnter' prop

---

package.json

> 2018-6-10
- **Feature**:  Support `bodyRef` on `<Table>` ([#23])
- **Bugfix**: When the height of the content is updated, reset the scroll bar position ([#22])
[23]: https://github.com/rsuite/rsuite-table/pull/23
[22]: https://github.com/rsuite/rsuite-table/pull/22

Update rsuite-table to v3.0.2

---

styles/mixins/hacks.less
styles/table.less

1. In safari, after multiple clicks , the loader still has not disappeared.
2. Loader should above the scrollbar.

update:Some table loader styles bug

---

styles/date-picker.less

The date range selector end date is a problem that flashes wildly as the mouse moves.

bugfixed:Date range picker styles.

---

styles/button.less
styles/dropdown.less
styles/mixins/button.less

1. When `<Dropdown/>` is disabled , click it still trigger ripple animation and cursor is default.
1. Remove dropdown disabled styles to `dropdown.less`

Change button disabled styles

---

src/FormControl.js
test/FormSpec.js

为了避免每次FormControl render时向内部组件传入新的handleFieldChange与handleFieldBlur方法，将formValue作为 FormControl 的props传入。

add form control wrapper

---

src/utils/defaultProps.js

fix: https://github.com/reactjs/react-lifecycles-compat/issues/32

Bugfix: IE error, object doesn't support property or method 'getDerivedStateFromProps'

---

src/Calendar/MonthDropdown.js

Webpack(configuration cra/razzle/next, SSR) does not transpile files in node_modules by babel, only application folder.
`/es/` folder contains ES modules and throws error, when you try build your application. We need import commonjs file, it does not require babel for build process.
Build on SSR shows error:

[FIX] Build error: import from es module to commonjs react-virtualized

---

src/Cascader/Dropdown.js
src/Cascader/DropdownMenu.js
src/MultiCascader/Dropdown.js
src/MultiCascader/DropdownMenu.js
types/Cascader.d.ts
types/MultiCascader.d.ts

Cascader's `renderMenu` function is missing parameters
Fix: https://github.com/rsuite/rsuite/issues/390

Fixed a Typescript definition error

---

package-lock.json
package.json
types/Table.d.ts
types/TableColumn.d.ts

- Support `renderEmpty` and `renderLoading` on `<Table>`
- Support `verticalAlign` on `<Table.Column>`
- Fix: Unable to preventDefault inside passive event listener due to target being treated as passive

Update rsuite-table to 3.5.0

---

src/MultiCascader/utils.js
test/MultiCascader/utilsSpec.js

Right now `MultiCascader` is throwing exceptions if it's rendered with a `value` containing references to a non-existent elements, eg:
```jsx
<MultiCascader 
cascade                
data={[{value: 5, label: 'any'}]}
value={[1]}
/>
```
This change ignores not found items.

MultiCascader: don't throw on a non-present selected value

---

scripts/gulpfile.js

Window uses '\' as path separator while mac & linux use '/', so for now users cannot develop this project on windows.

Fix path separator for windows users.

---

src/Calendar/Calendar.tsx
src/Calendar/Table.tsx
src/Calendar/TableHeaderRow.tsx
src/Calendar/TableRow.tsx
src/Calendar/View.tsx
src/Calendar/style/index.less
src/Calendar/test/CalendarTableHeaderRowSpec.js
src/Calendar/test/CalendarTableRowSpec.js
src/DatePicker/DatePicker.d.ts
src/DatePicker/DatePicker.tsx
src/DateRangePicker/Calendar/Calendar.tsx
src/DateRangePicker/Calendar/Table.tsx
src/DateRangePicker/Calendar/TableRow.tsx
src/DateRangePicker/Calendar/View.tsx
src/DateRangePicker/DatePicker.tsx
src/DateRangePicker/DateRangePicker.d.ts
src/DateRangePicker/DateRangePicker.tsx
src/style/variables.less

The same as #523 but on top of the Typescript version.
Note: I can't verify `<DateRangePicker />` since the `next` version of docs even without my changes is not working for it (it's crashing and messages are pretty useless) and unfortunately I can't invest more time into debugging it right now.

Implement an option for showing week numbers in the Datepickers

---

src/Calendar/TimeDropdown.tsx
src/Calendar/styles/common.less
src/DatePicker/styles/common.less

Right now it's crashing the build when used with `babel-preset-rsuite` like:
```
error  in ./node_modules/rsuite/lib/DatePicker/styles/index.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
// In picker menu
.@{ns}picker-menu .@{clpns} {
^
Variable @clpns is undefined
in [cut]/node_modules/rsuite/lib/DatePicker/styles/common.less (line 85, column 19)
at runLoaders ([cut]/node_modules/webpack/lib/NormalModule.js:302:20)
at [cut]/node_modules/loader-runner/lib/LoaderRunner.js:367:11
at [cut]/node_modules/loader-runner/lib/LoaderRunner.js:233:18
at context.callback ([cut]/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
at process._tickCallback …
```

DatePicker: add missing less definition

---

src/Progress/ProgressLine.tsx

I also make use of `trailWidth` and `trailColor` props.

Use `strokeWidth` as fallback for `trailWidth`

---

src/Loader.js

Several months ago was added some piece of code that brakes center alignment of Loader within its container. Removal of that inline styles fixes that issue.

Fixed alignment of Loader within its container

---

src/List/styles/common.less

Use [*Grab cursors*](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) for draggable elements, which, in this case, are sortable `<List.Item>`s.
Specification of some `cursor`s for drag & drop:
| CSS Value | Description |
| -------------- | --------------- |
| `move` | Something is to be moved. |
| `grab` | Something can be grabbed (dragged to be moved). |
| `grabbing` | Something is being grabbed (dragged to be moved). |
As *Grab cursors* are [not supported until latest browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#Browser_compatibility), keep `move` for compatibility.

Use grab cursors for sortable List.Item

---

types/Form.d.ts

Declare `Form` as a class instead of const. Add method definitions.

Update Form's definition, fix #626

---

src/CheckTreePicker/CheckTreePicker.tsx
src/TreePicker/TreePicker.tsx
src/utils/treeUtils.ts

Fix: CheckTreePicker and TreePicker focusNextItem Error when setting root node disabled

Fix: CheckTreePicker and TreePicker keydown error

---

src/Breadcrumb/BreadcrumbItem.d.ts
src/Breadcrumb/BreadcrumbItem.tsx
src/Breadcrumb/test/BreadcrumbItemSpec.js
src/Dropdown/DropdownMenuItem.d.ts
src/Dropdown/DropdownMenuItem.tsx
src/Dropdown/test/DropdownMenuItemSpec.js
src/Nav/NavItem.d.ts
src/Nav/NavItem.tsx
src/Nav/test/NavItemSpec.js
src/Pagination/PaginationButton.d.ts
src/Pagination/PaginationButton.tsx
src/Pagination/test/PaginationButtonSpec.js
src/SafeAnchor/SafeAnchor.d.ts
src/SafeAnchor/SafeAnchor.tsx
test/testUtils.js

Fix: https://github.com/rsuite/rsuite/issues/711
```js
import Link from "next/link";
<Nav>
<Nav.Item
renderItem={item => {
return <Link href="/home">{item}</Link>;
}}
>
link
</Nav.Item>
</Nav>
```

Add support for `renderItem` on the navigation component

---

src/Picker/styles/common.less

Fixed multiple picker count label vertical align issue when set `size=lg`.

---

src/styles/iconfont.less

Replaced iconfont.less file with https://github.com/rsuite/rsuite-icon-font/commit/0e26857cc8bba25a87951db4f337bcb67f7efa81 dist file.

Replaced iconfont.less file with rsuite-icon-font dist file.

---

docs/pages/components/container/en/index.md

From "COntainer" to "Container"

Fix character casing in the Sidebar definition

---

docs/pages/guide/intl/en/index.md
docs/pages/guide/intl/index.md

markdown的链接 指向了default.js，但是这个文件已经叫default.ts 了

docs(guide/intl): fix wrong link linking to default.js which has been renamed to default.ts

---

src/DateRangePicker/DateRangePicker.d.ts

typing for daterange picker are inconsistent between DisabledDateFunction and DateRangePickerProps and doc

[DateRangePicker] Update broken types and add enum for target

---

docs/components/Logo/Logo.tsx

Gray out RSuite logos on Homepage and TopNav on April 4, 2020, when China holds a national mourning for victims of the pandemic and heros who sacrificed for fighting the COVID-19.

docs: Gray rsuite logos on 2020/4/4

---

src/SelectPicker/SelectPicker.d.ts
src/Tree/TreeBase.d.ts

在上一个commit中，`SelectPicker.d.ts` 和 `TreeBase.d.ts` 的searchBy参数 变成了必填项

fix(Picker): make `searchBy` param optional in ts definition file

---

src/styles/variables.less

On electron it will add default scheme `file://` to `//cdn.jsdelivr.net/npm/rsuite/dist/styles/fonts`,and it will load failed. (#198 #967 )
So added default scheme `https://` to `@icon-font-path`

Change @icon-font-path

---

docs/pages/guide/intl/en/index.md
docs/pages/guide/intl/index.md
src/@types/common.d.ts
src/Calendar/CalendarPanel.tsx
src/Calendar/Header.tsx
src/Calendar/TableRow.tsx
src/Carousel/test/CarouselStylesSpec.js
src/Cascader/Cascader.tsx
src/CheckPicker/CheckPicker.tsx
src/DatePicker/DatePicker.tsx
src/DateRangePicker/Calendar/TableRow.tsx
src/DateRangePicker/DateRangePicker.d.ts
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/utils.ts
src/IntlProvider/FormattedDate.tsx
src/IntlProvider/IntlContext.ts
src/IntlProvider/IntlProvider.d.ts
src/IntlProvider/IntlProvider.tsx
src/IntlProvider/test/FormattedDateSpec.js
src/IntlProvider/withLocale.tsx
src/Uploader/Uploader.tsx
src/utils/createContext.ts

```tsx
import format from 'date-fns/format';
import ru from 'date-fns/locale/ru';
function formatDate(data, formatStr) {
return format(data, formatStr, {
locale: ru
});
}
```
```tsx
<IntlProvider formatDate={formatDate} >
<App />
</IntlProvider>
```
Fix: https://github.com/rsuite/rsuite/issues/1034

feat(IntlProvider): Support `formatDate` on `<IntlProvider>`

---

src/CheckTreePicker/CheckTreePicker.tsx

CheckTreePicker abnormal performance when data and unCheckableItemValues change at the same time

Fix CheckTreePicker Bug

---

docs/pages/guide/intl/en/index.md
src/IntlProvider/locales/es_AR.d.ts
src/IntlProvider/locales/es_AR.ts
src/IntlProvider/locales/es_ES.d.ts
src/IntlProvider/locales/es_ES.ts
src/IntlProvider/locales/index.d.ts
src/IntlProvider/locales/index.ts

Added translations for Spanish (Argentina `es_AR` & Spain `es_ES`)

feat: added translations for Spanish (Argentina & Spain)

---

docs/pages/components/auto-complete/en/index.md
docs/pages/components/auto-complete/index.md
src/AutoComplete/AutoComplete.d.ts
src/AutoComplete/AutoComplete.tsx
src/AutoComplete/test/AutoCompleteSpec.js

Currently, <code>AutoComplete</code> will do this check `item.label.toLocaleLowerCase().indexOf(keyword) >= 0` to determine whether item in data array will be displayed.
I add `filterBy` param so we can use this param to determine whether to display an item in data array.
It this param present, the component will not use the default `shouldDisplay` logic any more. It's up to developer to control that logic.

feat(AutoComplete): Support `filterBy` param

---

src/Breadcrumb/index.d.ts
src/Dropdown/index.d.ts
src/List/index.d.ts
src/Nav/index.d.ts
src/Placeholder/index.d.ts
src/Progress/index.d.ts
src/Table/TableColumnGroup.d.ts
src/Table/index.d.ts
src/Timeline/index.d.ts
src/index.d.ts

Export component props declarations for easier access.
Before:
```typescript
import { Button } from 'rsuite';
import { ButtonProps } from 'rsuite/lib/Button/Button';
```
After:
```typescript
import { Button, ButtonProps } from 'rsuite';
// import { ButtonProps } from 'rsuite/lib/Button/Button'; this still works
```

Export component props from rsuite

---

src/FormControl/FormControl.d.ts

当为 `<FormControl>` 编写自定义的 accepter 组件时，`FormControlProps` 可能被错误地用来为其 props 添加额外的字段。
```tsx
interface MyInputProps extends FormControlProps {
myProp: string;
}
function MyInput({ value, onChange }: MyInputProps) {
// do something with value and onChange
}
<FormControl accepter={MyInput} myProp="abc" />
```
而 `FormControlProps` 实际上是 `<FormControl>` 组件**自身**的 props 声明。如果需要一个 interface 来辅助编写 accepter 组件，应当另外声明如：
```ts
interface FormControlAccepterProps<ValueType = any> {
value?: ValueType;
onChange?(value: ValueType): void;
}
```
在 `FormControlAccepterProps` 的用法上，我有一些尚未确定的考虑，希望可以听下其他人的意见。
我认为 accepter 组件的 props 本身不应 `extends FormControlAccepterProps`，而是组件接收 `Props & FormControlAccepterProps` 作为参数。
```tsx
interface MyInputProps {
myProp: string;
}
function MyInput({ value, onChange }: …
```

Split FormControlAccepterProps from FormControlProps

---

src/Uploader/UploadTrigger.tsx

Fixed file input repeatedly triggering onChange event after value change in IE11 (https://github.com/facebook/react/issues/8793)
fix #1141

fix(uploader): fix Uploader repeatedly triggering onChange event in IE11

---

src/PanelGroup/styles/common.less

在 `<PanelGroup>` 中使用 `<Panel>` 组件充当 "Card" 时，边框缺失。
```tsx
<PanelGroup>
<Panel header="Products">
{products.map((product, index) => (
<Panel key={index} bordered> // borders missing
</Panel>
)}
</Panel>
// <Panel> ...
</PanelGroup>
```
对 `<PanelGroup>` 下的 `<Panel>` 进行 `border: none` 处理时，应当仅选中其直接子元素的 `<Panel>`。

fix(Panel): Missing panel border inside PanelGroup

---

src/Steps/Steps.tsx

`<Steps>` counts a `<Fragment>` in its children as one item, and applies styles incorrectly. 
```tsx
<Steps>
{stages.map((stage, index) => (
<Steps.Item key={index} title={stage.name} />
)}
<Steps.Item icon={<Icon icon="plus-circle" />} />
</Steps>
```

fix(Steps): Children with Fragments

---

src/Cascader/Cascader.tsx
src/Cascader/test/CascaderSpec.js
src/CheckPicker/CheckPicker.tsx
src/CheckPicker/test/CheckPickerSpec.js
src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.js
src/InputPicker/InputPicker.tsx
src/InputPicker/test/InputPickerSpec.js
src/MultiCascader/MultiCascader.tsx
src/MultiCascader/test/MultiCascaderSpec.js
src/SelectPicker/SelectPicker.tsx
src/TagPicker/test/TagPickerSpec.js
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreePickerSpec.js

When renderValue returns null or undefined, it is considered that there is no value.

fix(picker): adjust the verification rules for renderValue

---

.github/workflows/nodejs-ci.yml
src/Picker/DropdownMenuGroup.tsx
src/Picker/styles/mixin.less

SelectPicker has the same problem.

fix(check-picker): fixed the group icon not showing in CheckPicker

---

src/Overlay/Overlay.tsx

```container``` should contain an HTML Element as stated in the interface. 
This ```PropType``` is incorrect and causes notices. Updated to ```any``` like in ```next```-branch.

Prevent notice for overlay

---

src/Cascader/Cascader.tsx
src/Cascader/test/CascaderSpec.js
src/CheckPicker/CheckPicker.tsx
src/CheckPicker/test/CheckPickerSpec.js
src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.js
src/DatePicker/DatePicker.tsx
src/DatePicker/test/DatePickerSpec.js
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.js
src/MultiCascader/MultiCascader.tsx
src/MultiCascader/test/MultiCascaderSpec.js
src/SelectPicker/SelectPicker.tsx
src/SelectPicker/test/SelectPickerSpec.js
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreePickerSpec.js

Add `aria-disabled=true` to pickers' toggles when they are disabled.

[v4] aria-disabled for picker toggles

---

src/Modal/BaseModal.tsx
src/Modal/test/ModalSpec.js

`Modal` was rendering duplicated `role=dialog` elements.
This PR removes the role on the outer div.

fix(modal): remove duplicated dialog role

---

docs/pages/components/cascader/en-US/index.md
docs/pages/components/cascader/zh-CN/index.md
docs/pages/components/multi-cascader/en-US/index.md
docs/pages/components/multi-cascader/zh-CN/index.md

Removed onGroupTitleClick in the docs of Cascader and MultiCascader

docs(cascader): removed onGroupTitleClick on Cascader and MultiCascader

---

docs/pages/components/popover/en-US/overlay.md
docs/pages/components/popover/zh-CN/overlay.md
src/Overlay/OverlayTrigger.tsx
src/Whisper/test/WhisperSpec.js

The `onClose` method can be called inside the speaker to close the Overlay, when the value of the speaker is a function.
```tsx
const Overlay = React.forwardRef(({ style, onClose, ...rest }, ref) => {
const styles = {
...style,
background: '#fff',
width: 200,
padding: 10,
borderRadius: 4,
position: 'absolute',
border: '1px solid #ddd',
boxShadow: '0 3px 6px -2px rgba(0, 0, 0, 0.6)'
};
return (
<div {...rest} style={styles} ref={ref}>
Overlay
<hr />
<button onClick={onClose}>close</button>
</div>
);
});
const App = () => (
<Whisper
trigger="click"
speaker={(props, ref) => {
const { className, left, top, onClose } = props;
return <Overlay style={{ left, top }} onClose={onClose} className={className} ref={ref} />;
}}
>
<Button>Test</Button>
</Whisper>
);
```
close #1458

feat(whisper): support `onClose` on the `speaker` prop of Whisper

---

docs/pages/guide/use-with-create-react-app/en-US/index.md

The Yarn command is
```bash
yarn create react-app test-app
```

Typo in yarn command in documentation

---

src/Avatar/Avatar.tsx

change prop `sizes` and prop `srcSet` to optional.

fix(Avatar): fix prop types

---

docs/pages/guide/use-with-create-react-app/en-US/index.md

`yarn create-react-app test-app` is obsolete. 
`yarn create react-app test-app` is the way to go!

Fix `create-react-app` command with yarn

---

src/InputPicker/InputPicker.tsx
src/InputPicker/test/InputPickerSpec.js
src/SelectPicker/SelectPicker.tsx

This feature will help when trying to do something with a value not previously on the data list. Use case involves, fetching an array of data as data list and adding a created value to the database so that the user does not have to create it again.
Created from ISSUE #1567 
The onCreate prop is a function that fires when the `creatable` `inputPicker` has a new created value that is not in the list. The function passes values as the onSelect prop does:
`onCreate={(value, item, event) => null}`
```
<InputPicker
creatable
onCreate={(value, item, event) => addToDatabase(value)} />
```

Added onCreate prop for creatable inputPicker

---

src/Cascader/Cascader.tsx
src/Cascader/test/CascaderSpec.js

Fixing childrenKey property of the Cascader component does not work when searching  and Increase the corresponding unit test

fix(cascader): fixing childrenKey property not work when searching(#1568)

---

src/Nav/Nav.tsx
src/Nav/NavItem.tsx
src/Nav/test/NavItemSpec.js
src/utils/appendTooltip.tsx

You can customize the rendering position of the tooltip on NavItem. When set to false, it will not render.
```tsx
<Sidenav>
<Sidenav.Body>
<Nav>
<Nav.Item tooltip={false}> Dashboard </Nav.Item>
<Nav.Item tooltip="top" > Dashboard </Nav.Item>
...
</Nav>
</Sidenav.Body>
</Sidenav>
```

feat(nav-item): support `tooltip` on NavItem

---

package-lock.json
package.json

build(deps): bump element-resieze-event from 3.0.3 to 3.0.6

---

src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.js
src/TreePicker/test/TreePickerSpec.js
src/utils/treeUtils.ts

Fix CheckTreePicker and TreePicker some controlled props is not working when props change `undefined` to `array`
About CheckTreePicker controlled props
* value
* uncheckableItemValues
* expandItemValues
About TreePicker controlled props
* expandItemValues

Fix CheckTreePicker and TreePicker value controlled

---

babel.config.js
karma.conf.js

Test scripts themselves were taken into count in coverage calculation, resulting in a misleading coverage output. Remove them by configuring karma and babel as [`babel-plugin-istanbul` documents](https://github.com/istanbuljs/babel-plugin-istanbul#ignoring-files).
Before: https://codecov.io/gh/rsuite/rsuite/tree/9f23d9c26f092cd49c73c89dfe4dd394716c2863
After: https://codecov.io/gh/rsuite/rsuite/tree/fda8746b67d01a17f78719a206cd0611dab11b63
As this PR modified the coverage collecting scope, you may merge this PR regardless of possible coverage reduction.
Reference:
- https://github.com/ryanclark/karma-webpack/issues/21#issuecomment-249701814
- https://github.com/istanbuljs/babel-plugin-istanbul#ignoring-files
- https://github.com/karma-runner/karma-coverage#basic

chore(coverage): remove test scripts from coverage calculation

---

.github/workflows/nodejs-ci.yml

Now you can view coverage reports for different browsers accordingly. 
Example:
https://codecov.io/gh/rsuite/rsuite/src/b0718240d7f15061ce65c01dc265e28e2b416e6a/src/Placeholder/PlaceholderGraph.tsx

ci(codecov): mark reports with browser name as flags

---

src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.js
src/CheckTreePicker/utils.ts
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreePickerSpec.js
src/utils/treeUtils.ts

* fix(tree): can't search in virtualized mode
* fix(tree): exclude searchBar backspace event from onPickerKeyDown

fix: CheckTreePicker and TreePicker search problems

---

src/Sidenav/SidenavItem.tsx
src/Sidenav/test/SidenavSpec.js

Top-level `<Nav.Item>` inside `<Sidenav>` was not triggering `onSelect` of `<Nav>` component.
https://user-images.githubusercontent.com/8225666/128141655-4401a2ce-b045-4038-9e23-d3ca0b22b58b.mp4

fix(sidenav): trigger `<Nav onSelect>` on click `<Nav.Item>`

---

src/Dropdown/DropdownMenu.tsx

Prevent warning when setting `activeKey` prop of `<Dropdown.Menu>`
Warning: React does not recognize the `activeKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activekey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

fix(dropdown-menu): remove unrecognizable activeKey from dom

---

docs/pages/components/table/en-US/index.md
docs/pages/components/table/zh-CN/index.md
docs/pages/guide/v5-features/en-US/index.md
docs/pages/guide/v5-features/zh-CN/index.md
package-lock.json
package.json
src/Table/styles/index.less

- https://github.com/rsuite/rsuite-table/pull/232
- https://github.com/rsuite/rsuite-table/pull/234
- https://github.com/rsuite/rsuite-table/pull/235
- https://github.com/rsuite/rsuite-table/pull/236
- https://github.com/rsuite/rsuite-table/pull/237
- https://github.com/rsuite/rsuite-table/pull/238
Use react hooks to refactor the Table and improve the performance when the table scrolls. [The `onDataUpdated` and `bodyRef` props are deprecated](https://github.com/rsuite/rsuite-table/pull/232).
For some components to be rendered inside the table, the body container of the table can be obtained through `bodyRef` before. Now we can get the container directly through the `ref` of `Table`.
```js
// v4
const ref = uesRef();
return (
<>
<Table
bodyRef={body => {
ref.current = body;
}}
/> …
```

build(deps): bump rsuite-table from 5.0.0-alpha.5 to 5.0.0-alpha.8

---

docs/next-env.d.ts
docs/pages/components/button/fragments/icon-button.md
docs/pages/components/dropdown/en-US/index.md
docs/pages/components/dropdown/fragments/custom-toggle.md
docs/pages/components/dropdown/zh-CN/index.md
docs/pages/guide/v5-features/en-US/index.md
docs/pages/guide/v5-features/zh-CN/index.md
src/Dropdown/Dropdown.tsx
src/Dropdown/DropdownToggle.tsx
src/Dropdown/styles/index.less
src/Dropdown/styles/mixin.less
src/Dropdown/test/DropdownSpec.js
src/Dropdown/test/DropdownToggleSpec.js

```tsx
const renderIconButton = (props, ref) => {
return (
<IconButton {...props} ref={ref} icon={<PlusIcon />} circle color="blue" appearance="primary" />
);
};
const App = () => (
<Dropdown renderToggle={renderIconButton}>
<Dropdown.Item icon={<PageIcon />}>New File</Dropdown.Item>
<Dropdown.Item icon={<FolderFillIcon />}>New File with Current Profile</Dropdown.Item>
<Dropdown.Item icon={<FileDownloadIcon />}>Download As...</Dropdown.Item>
<Dropdown.Item icon={<DetailIcon />}>Export PDF</Dropdown.Item>
</Dropdown>
);
```
The `renderTitle` has been deprecated and replaced by `renderToggle: (props, ref) => ReactNode`.
```tsx
//v4
return (
<Dropdown
renderTitle={() => <IconButton appearance="primary" icon={<Icon icon="plus" />} circle />}
>
...
</Dropdown>
);
//v5
return (
<Dropdown …
```

feat(dropdown): support `renderToggle` on `<Dropdown>`

---

package-lock.json
package.json

- https://github.com/rsuite/schema-typed/pull/36
- https://github.com/rsuite/schema-typed/pull/35

build(deps): bump schema-typed from 2.0.0 to 2.0.1

---

src/CheckTree/index.tsx
src/CheckTree/test/CheckTreeSpec.js
src/CheckTreePicker/CheckTreePicker.tsx
src/Picker/utils.ts
src/Tree/Tree.tsx
src/Tree/TreeContext.ts
src/Tree/test/TreeSpec.js
src/TreePicker/TreeNode.tsx
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreeNodeSpec.js
src/TreePicker/test/TreePickerSpec.js
src/TreePicker/test/TreePickerStylesSpec.js

- Removed `inline` prop on Tree related components. Through context management.
- Removed the hard-coded id attribute on the drag element https://github.com/rsuite/rsuite/pull/1883/files#diff-e7f6213f721793e010931abb7589019403121edde27e935bf3fe07af27031037L762
- Fixed the inability to get element on `Tree` and `CheckTree` through `ref`.

test(tree): add tests for Tree and CheckTree

---

src/TagInput/index.tsx
src/TagInput/test/TagInputSpec.js

There are often spaces in tags consisting of multiple words. 
So the default value of trigger is changed to `Enter`, and the `Space` is removed.

fix(tag-input): adjust default value of the trigger to `Enter`

---

docs/pages/components/carousel/en-US/index.md
docs/pages/components/carousel/zh-CN/index.md
src/Carousel/Carousel.tsx
src/Carousel/test/CarouselSpec.js

| Property         | Type `(Default)`                                       | Description                                    |
| ---------------- | ------------------------------------------------------ | ---------------------------------------------- |
| onSelect         | (index: number, event?: React.ChangeEvent) => void     | Callback fired when the active item changes    |
| onSlideEnd       | (index: number, event?: React.TransitionEvent) => void | Callback fired when a slide transition ends    |
| onSlideStart     | (index: number, event?: React.ChangeEvent) => void     | Callback fired when a slide transition starts  |

feat(carousel): support `onSelect`, `onSlideEnd`, `onSlideStart` on `<Carousel>`

---

docs/pages/components/form/en-US/index.md
docs/pages/components/form/zh-CN/index.md

Hi, I've found some typos when I make some experiments with your library.
Lemme know if additional stuff needs to be done.
And thanks for the job 👏

docs(v5): fix typo and add missing Form.ErrorMessage in title

---

src/Sidenav/SidenavItem.tsx
src/Sidenav/styles/index.less
src/Sidenav/test/SidenavSpec.js

`<Nav.Item>` inside collapsed `<Sidenav>` was not able to be activated by clicking on it.

fix(sidenav): fix nav item not activated in collapsed sidenav

---

src/RangeSlider/RangeSlider.tsx
src/Slider/Graduated.tsx
src/Slider/Handle.tsx
src/Slider/ProgressBar.tsx
src/Slider/Slider.tsx
src/Slider/styles/index.less

The vertical Sliders used to be up-side-down
Before
After

fix(Slider,RangeSlider): reverse marks order in vertical orientation

---

.github/workflows/nodejs-ci.yml

Respecting https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1

ci(codecov): use codecov-action v2

---

src/@types/common.ts
src/Input/Input.tsx

`<Input onChange>` only emits `value` as `string`.

fix(Input): correct value argument type for onChange callback

---

docs/less/code-view.less
docs/public/less/palette.less
src/Toggle/Toggle.tsx
src/Toggle/styles/index.less
src/Toggle/styles/mixin.less
src/Toggle/test/ToggleSpec.js
src/Toggle/test/ToggleStylesSpec.js

- Add an underlying `<input type="checkbox">` in `<Toggle>` component.
- Passes `ChangeEvent` from the input to `onChange` callback on `<Toggle>`

refactor(Toggle): add underlying input element

---

docs/pages/components/check-picker/en-US/index.md
docs/pages/components/check-picker/zh-CN/index.md
docs/pages/components/input-picker/en-US/index.md
docs/pages/components/input-picker/zh-CN/index.md
docs/pages/components/select-picker/en-US/index.md
docs/pages/components/select-picker/zh-CN/index.md
docs/pages/components/tag-picker/en-US/index.md
docs/pages/components/tag-picker/zh-CN/index.md

`maxHeight` prop that controls menu's max height in a picker has been renamed to `menuMaxHeight` in v5, but the docs was not updated for that.
See discussion here https://github.com/rsuite/rsuite/issues/2088#issuecomment-958845003

docs(Picker): maxHeight renamed as menuMaxHeight

---

docs/pages/components/table/en-US/index.md
docs/pages/components/table/zh-CN/index.md

https://github.com/rsuite/rsuite/blob/main/docs/pages/guide/v5-features/en-US/index.md#improvements-to-table

docs(table): remove `bodyRef` in props

---

docs/pages/_common/types/data-item-type.md

Hey, just found this typo while checking the docs!

docs: fix typo on the word Cascader

---

src/Sidenav/styles/index.less

fix(Sidenav): remove underline on hovered SidenavItem

---

package-lock.json
package.json

* **Table:** fix scroll bar not re-rendering after table resize ([#267](https://github.com/rsuite/rsuite-table/issues/267)) ([185f759](https://github.com/rsuite/rsuite-table/commit/185f759536b2686472995acb72e838827716ec21))
* **Column:** added support for nested values of dataKey on Column ([#268](https://github.com/rsuite/rsuite-table/issues/268)) ([50ec875](https://github.com/rsuite/rsuite-table/commit/50ec875891fa33fc677a7c9e2e07a4af060773a5))
* **TreeTable:** improve the performance of tree table ([#266](https://github.com/rsuite/rsuite-table/issues/266)) ([25eeee6](https://github.com/rsuite/rsuite-table/commit/25eeee62c2c5539e956d4bcf3643b951002ae36f))

build(deps): bump rsuite-table from 5.1.0 to 5.2.0

---

src/InputPicker/InputPicker.tsx
src/TagPicker/test/TagPickerSpec.js

fix(TagPicker): fix placeholder misalignment in plaintext mode

---

package-lock.json
package.json

* **scrollbar:** enhanced verification of the number of columns ([#275](https://github.com/rsuite/rsuite-table/issues/275)) ([a666996](https://github.com/rsuite/rsuite-table/commit/a666996dbf68b1a12ad565911345af8b55a9398c))
* **scrollbar:** fix scroll left reset ([#273](https://github.com/rsuite/rsuite-table/issues/273)) ([dab0f27](https://github.com/rsuite/rsuite-table/commit/dab0f2796c3168dc8fc0bc480b15f63cd04fe5af))
* **tree:** fix unrecalculated row height after tree node is expanded ([#277](https://github.com/rsuite/rsuite-table/issues/277)) ([3788875](https://github.com/rsuite/rsuite-table/commit/378887509981db5cfc3a98e47c2751cc0559f3f8))
* **wordWrap:** fix can't word wrap in tree table ([#274](https://github.com/rsuite/rsuite-table/issues/274)) …

build(deps): bump rsuite-table from 5.2.0 to 5.2.1

---

src/Uploader/Uploader.tsx

- ~Fix wrong parameter name in function `handleAjaxUploadError`~
- When we control the component `Uploader` state via props `fileList`, fileMap won't be updated if uploaded failed since nextFile.progress is always undefined. It cause the function `getFileList` always return incorrect info across in many caller functions.

fix(component): uploader fileMap is not updated when status is error

---

src/Carousel/Carousel.tsx

Hey, I'm trying to use the Carousel component (https://rsuitejs.com/components/carousel/) in our project but, it requires an `onSelect` props. I don't think this property needs to be required. Right?

fix(Carousel): make onSelect prop optional

---

src/Table/styles/index.less

fix: https://github.com/rsuite/rsuite-table/issues/276
ref: https://github.com/rsuite/rsuite-table/commit/d0c7f34f16a6433cd089921fbd4cc522db29cea8#diff-901047440991f732080fa2e54e7166ff0fdb5cb1860ca1c2fb46c8b7403e4f15L20-L23

fix(Table): fix the column of grouping cannot be centered

---

docs/next.config.js
package.json

Configure Vercel project to use its Next.js preset. An experimental is created here https://vercel.com/rsuite/rsuite-nextjs .

chore: remove build:docs script

---

docs/pages/components/date-range-picker/en-US/index.md
docs/pages/components/date-range-picker/fragments/format-date-time.md
docs/pages/components/date-range-picker/zh-CN/index.md
src/DateRangePicker/Calendar.tsx
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.js

Fix #2166, support `showMeridian` on `<DateRangePicker>`
```tsx
<DateRangePicker format="yyyy-MM-dd hh:mm aa" showMeridian />
```

fix(DateRangePicker): fix DateRangePicker cannot switch am/pm

---

docs/pages/components/tree/fragments/basic.md
docs/pages/components/tree/index.tsx
src/CheckTree/test/CheckTreeSpec.js
src/CheckTreePicker/CheckTreePicker.tsx
src/Picker/VirtualizedList.tsx
src/Picker/utils.ts
src/Tree/test/TreeSpec.js
src/Tree/test/TreeStylesSpec.js
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreePickerSpec.js

fix: https://github.com/rsuite/rsuite/issues/1994
fix: https://github.com/rsuite/rsuite/issues/2173
```tsx
const treeRef = React.useRef();
return (
<Tree data={data} ref={treeRef}  virtualized />
);
// https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#scrolltorow-index-number
treeRef.current.list.scrollToRow(index);
```
```ts
interface Instance {
root?: Element;
// https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#public-methods
list?: ListInstance;
}
```
```ts
interface Instance {
root?: Element;
// https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#public-methods
list?: ListInstance;
overlay?: Element;
target?: Element;
updatePosition?: () => void;
open?: () => void;
close?: () => void;
}
```

fix(tree): expose methods for tree that can scroll the list

---

src/Breadcrumb/Breadcrumb.tsx
src/Breadcrumb/test/BreadcrumbSpec.js

Getting warning when generating `<Breadcrumb.Item>`s with array map method
```jsx
<Breadcrumb>
{items.map((item, index) => (
<Breadcrumb.Item key={index} href={item.href} active={!item.href} as={Link}>
{item.text}
</Breadcrumb.Item>
)}
</Breadcrumb>
```

fix(Breadcrumb): avoid separator key conflict with item key

---

docs/less/pages/components/avatar.less
docs/next.config.js
docs/pages/components/avatar/en-US/index.md
docs/pages/components/avatar/fragments/badge.md
docs/pages/components/avatar/fragments/basic.md
docs/pages/components/avatar/fragments/icon.md
docs/pages/components/avatar/fragments/image.md
docs/pages/components/avatar/fragments/import.md
docs/pages/components/avatar/fragments/size.md
docs/pages/components/avatar/fragments/stack.md
docs/pages/components/avatar/fragments/text.md
docs/pages/components/avatar/index.tsx
docs/pages/components/avatar/zh-CN/index.md
docs/tsconfig.local.json
docs/utils/component.config.json
src/Avatar/Avatar.tsx
src/Avatar/styles/index.less
src/AvatarGroup/AvatarGroup.tsx
src/AvatarGroup/index.tsx
src/AvatarGroup/styles/index.less
src/AvatarGroup/test/AvatarGroupSpec.js
src/index.tsx
src/styles/index.less

https://rsuite-nextjs-git-feat-avatargroup-rsuite.vercel.app/components/avatar/
```jsx
<AvatarGroup stack>
<Avatar circle src="https://avatars.githubusercontent.com/u/12592949" alt="@superman66" />
<Avatar circle src="https://avatars.githubusercontent.com/u/8225666" alt="@SevenOutman" />
<Avatar circle src="https://avatars.githubusercontent.com/u/15609339" alt="@hiyangguo" />
<Avatar circle src="https://avatars.githubusercontent.com/u/14308293" alt="@MarvelSQ" />
<Avatar circle src="https://avatars.githubusercontent.com/u/1203827" alt="@simonguo" />
</AvatarGroup>
```

feat(AvatarGroup): add support for AvatarGroup

---

docs/package-lock.json
docs/package.json

Suppress #2187 because next 12.0.5 introduced bugs, which are then addressed in 12.0.6
https://github.com/vercel/next.js/releases/tag/v12.0.6

build(deps): bump next 12.0.6

---

src/FormControl/FormControl.tsx
src/FormControl/test/FormControlSpec.js

In the current implementation, if a user explicitly sets a default value to a `FormControl`, it never gets applied as it is overwritten by the `Form` context `defaultValues`. In some scenarios, either for convention of the project, structure/reusable components and other situations, it is desirable that the component can be set with default value regardless of the `Form` configuration.
We're allowing to set the `defaultValue` prop in the component and it gets used preferentially over the Form configuration if set.

feat(FormControl): allow explicit default value

---

src/toaster/test/toasterSpec.js

Flaky coverage on setTimeout callbacks as shown here https://app.codecov.io/gh/rsuite/rsuite/compare/2165/changes#D1L77

test(toaster): fix unstable coverage for setTimeout cases

---

docs/package-lock.json
docs/package.json
package-lock.json
package.json
src/@types/common.ts
src/Picker/propTypes.ts
src/Picker/utils.ts
src/SelectPicker/SelectPicker.tsx
src/SelectPicker/test/SelectPicker.test.tsx

The value type used to be fixed as `number | string` on `<SelectPicker>`.
Now `value` and `onChange(value)` types are inferred from `data` prop.

fix(SelectPicker): fix onChange argument type

---

src/CheckPicker/CheckPicker.tsx
src/CheckPicker/test/CheckPicker.test.tsx
src/SelectPicker/SelectPicker.tsx
src/SelectPicker/index.tsx

`value` and `onChange(value)` type are now inferred from `data` item's `value` property.

perf(CheckPicker): infer value and onChange types from data prop

---

docs/pages/components/tree/en-US/index.md
docs/pages/components/tree/zh-CN/index.md
src/CheckTree/index.tsx
src/Tree/Tree.tsx
src/Tree/TreeContext.ts
src/TreePicker/TreeNode.tsx
src/TreePicker/TreePicker.tsx
src/TreePicker/styles/index.less

1. Remove custom dragNode element when drag node
2. Remove `renderDragNode` props
3. Update `Tree` docs

fix(tree): remove dragNode Element when drag node (#2185)

---

src/Dropdown/styles/index.less
src/Dropdown/test/DropdownStylesSpec.js

fix(Dropdown): reduce padding in noCaret variant

---

src/Sidenav/styles/index.less

Fix #2183
Before
https://user-images.githubusercontent.com/8225666/146748198-dd62732d-3baa-4ed1-a638-a509c843269a.mov
After
https://user-images.githubusercontent.com/8225666/146748245-12359d12-1ca7-44b3-9bbb-dd1fcb7c72b8.mov

fix(Sidenav): prevent text wrapping when collapsing

---

src/Sidenav/test/SidenavSpec.js

Suppress warnings when testing deprecated APIs.

test(Sidenav): silent depreated prop warnings

---

src/CheckPicker/CheckPicker.tsx
src/CheckPicker/test/CheckPicker.test.tsx
src/SelectPicker/SelectPicker.tsx
src/SelectPicker/test/SelectPicker.test.tsx

fix PickerProps missing `ref`
```tsx
const ref = React.createRef<PickerInstance>();
<SelectPicker ref={ref} data={[]} />
```

fix(Picker): add ref to PickerComponentProps

---

src/Button/styles/index.less
src/Dropdown/styles/index.less
src/Dropdown/styles/mixin.less
src/Navbar/styles/index.less
src/Sidenav/styles/index.less
src/styles/color-modes/dark.less
src/styles/color-modes/high-contrast.less
src/styles/color-modes/light.less
src/styles/mixins/utilities.less

Outline does not occupy space.
Sidenav and Navbar are usually placed by the edge of the page, causing an outset focus ring to be clipped.
Sidenav currently
Sidenav in this edit
Navbar currently
Navbar in this edit
No longer display focus ring when activated by mouse click.

refactor: focus rings

---

docs/pages/components/table/en-US/index.md
docs/pages/components/table/zh-CN/index.md
package-lock.json
package.json

* **Table:** support renderRow on <Table> ([#287](https://github.com/rsuite/rsuite-table/issues/287)) ([732a35e](https://github.com/rsuite/rsuite-table/commit/732a35e5567048bdf6cc1a21d6887f0481913b46))

build(deps): bump rsuite-table from 5.2.2 to 5.3.0

---

docs/components/TopLevelNav/TopLevelNav.tsx
docs/components/TopLevelNav/styles.less

before
after
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `TopLevelNav`.
```

docs(brand): fix brand misplacement on mobile

---

src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/styles/index.less
src/CheckTreePicker/test/CheckTreePickerStylesSpec.js
src/CheckTreePicker/utils.ts

Fix CheckTreePicker style incorrect when data has only one level structure.

fix(CheckTreePicker): fix root node style incorrect

---

package-lock.json
package.json

- **Table:** fix rowSpan is invalid in ie brower ([#293](https://github.com/rsuite/rsuite-table/issues/293)) ([ea49e51](https://github.com/rsuite/rsuite-table/commit/ea49e513746fb4b44077d3baafbd27886e744aab))

build(deps): bump rsuite-table from 5.3.0 to 5.3.1

---

src/Calendar/test/CalendarSpec.js

The original test script which attempted to click "Today" button would only pass in Dec 2021 .

test(Calendar): fix flaky test case for onSelect prop

---

src/CheckTreePicker/styles/index.less
src/Picker/styles/mixin.less
src/Sidenav/styles/index.less
src/TreePicker/styles/index.less
stylelint.config.js

Simplify over-complex compound selectors 
- CheckTree/CheckTreePicker
- Tree/TreePicker
- InputPicker/TagPicker
- Sidenav
| Before | After |
| ------ | ----- |
| `.rs-check-tree-without-children .rs-check-tree-node-label .rs-check-item .rs-checkbox-checker > label .rs-checkbox-wrapper` | `.rs-check-tree-without-children .rs-check-item .rs-checkbox-checker .rs-checkbox-wrapper` |
| `.rs-check-tree-node-all-uncheckable > .rs-check-tree-node-label .rs-check-item .rs-checkbox-checker > label` | `.rs-check-tree-node-all-uncheckable > .rs-check-item . rs-checkbox-checker > label` |
| `.rs-tree-node>.rs-tree-node-label>.rs-tree-node-label-content` | `.rs-tree-node-label-content` |
| `.rs-tree-node.rs-tree-node-active>.rs-tree-node-label>.rs-tree-node-label-content` | `.rs-tree-node-active …

perf(styles): simplify compound selectors over 4 levels

---

docs/pages/components/slider/en-US/index.md
docs/pages/components/slider/fragments/constraint.md
docs/pages/components/slider/zh-CN/index.md
src/RangeSlider/RangeSlider.tsx
src/RangeSlider/test/RangeSliderSpec.js

When `constraint` prop is specified, RangeSlider checks if next value matches the constraint before calling `onChange`. If the value does not match the given constraint, RangeSlider remains current value and does not call `onChange`.
```ts
interface RangeSliderProps {
constraint?: (value: [number, number]) => boolean;
}
```
Return a boolean to indicate whether next value (passed as the `value` argument) matches the constraint.
The RangeSlider below cannot set a starting value greater than 10 nor an ending value smaller than 90.
```jsx
<RangeSlider 
defaultValue={[0, 100]}
constraint={([start, end]) => start <= 10 && end >= 90}
/>
```

feat(RangeSlider): add `constraint` prop

---

package-lock.json
package.json

* **ssr:** fix `window` is not defined for Table Columns ([#294](https://github.com/rsuite/rsuite-table/issues/294)) ([42e1189](https://github.com/rsuite/rsuite-table/commit/42e1189671bfe1687c7894df7ba5e67aa8a0bc24))

build(deps): bump rsuite-table from 5.3.1 to 5.3.2

---

src/CheckTreePicker/styles/index.less
src/CheckTreePicker/test/CheckTreePickerStylesSpec.js

According to the design resources, correct CheckTreePicker label padding space.

fix(CheckTreePicker): fix CheckTreePicker label style

---

src/Carousel/styles/index.less

Hey, I spotted a small CSS issue with the carousel.
**Problem:**
When you have many images, some buttons can be unreachable.
We have this problem in our application. The carousel is in a card that takes 30% of the screen width. When the carousel has a "bar shape", we can't have more than 8 images.
**Solution**: 
with this CSS property, it's automatically nicer.
**How to reproduce:**
1. Open `docs/pages/components/carousel/fragments/basic.md`
2. Duplicate the image many times.

fix(Carousel): add a flex-wrap property on toolbar buttons

---

src/Cascader/Cascader.tsx
src/Cascader/test/CascaderSpec.js

with `parentSelectable`, show match parent node in search result
```tsx
<Cascader
data={[
{
label: 'a'
value: 'a',
children: [
{
label: 'a-1',
value: 'a-1'
},
{
label: 'a-2',
value: 'a-2'
}
]
}
]}
parentSelectable
/>
```
- a
- a / a-1
- a / a-2
---------

feat(Cascader): add parent node in serach result while parentSelectable

---

docs/pages/components/tag/en-US/index.md
docs/pages/components/tag/zh-CN/index.md

Hi, 
the props `size` is missing from the docs. 
Let me know what text you want to see in the zh-CN version and I'll update the PR!

docs(Tag): add missing tag size props

---

docs/pages/components/carousel/en-US/index.md
docs/pages/components/carousel/fragments/position.md
docs/pages/components/carousel/zh-CN/index.md
src/Carousel/Carousel.tsx
src/Carousel/test/CarouselSpec.js

**Changes:**
This PR exposes the active index to the user so he can either initialize with a different index or to change it externally. It keeps all the behaviors already in place.
**Rationale:**
Sometimes the user want to initialize a different initial position, for example loading last status of his navigation, or change the active element externally, for example having an expanded view of a thumbnail that has navigation between elements and needs to keep the carousel in sync.

feat(Carousel): Expose active index

---

docs/package-lock.json
docs/package.json
package-lock.json
package.json

* **ssr:** fix server-side rendering warning ([#310](https://github.com/rsuite/rsuite-table/issues/310)) ([e188ef7](https://github.com/rsuite/rsuite-table/commit/e188ef71f814f718e97b29320d377e8250f323b5))
* **ts:** fix errors checked in typescript strict mode ([#305](https://github.com/rsuite/rsuite-table/issues/305)) ([ba059bd](https://github.com/rsuite/rsuite-table/commit/ba059bd4dc9bc09af99659416407ae42e99bb0b0))
* **useScrollListener:** can't perform a React state update on an unmounted component ([#306](https://github.com/rsuite/rsuite-table/issues/306)) ([f2104f1](https://github.com/rsuite/rsuite-table/commit/f2104f111103d4229a2f7800a0f11641b0641703))

build: bump rsuite-table from 5.3.2 to 5.3.3

---

src/toaster/test/toasterSpec.js
src/toaster/toaster.tsx

**Problem**: see #2336.
**Root cause**: during the TS -> JS compilation, the non-null assertion operator got translated from `container.current!.push` to `container.current.push`. It crash when `container.current` is null.
**How to test**:
1. open docs/pages/components/notification/index.tsx
2. replace the content with the following:
<details>
<summary>(Click to expand)</summary>
```ts
import React, { useEffect } from 'react';
import { Button, Notification, toaster } from 'rsuite';
export default function Page() {
function notify() {
toaster.push(<Notification>Hi toaster!</Notification>);
}
useEffect(() => {
notify();
}, []);
return (
<div>
Hello
<Button onClick={notify}>React Suite</Button>
</div>
);
}
```
</details>

fix(Toaster): code breaks when toaster is in a useEffect

---

docs/pages/guide/composition/en-US/index.md

Small typo that could cause issues when people copy and paste from the guide.

Typo: Changed onFoucs to onFocus

---

src/DatePicker/DatePicker.tsx
src/DatePicker/test/DatePickerSpec.js
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.js
src/Picker/index.ts

fix  #2356 
```tsx
import { DateRangePicker } from 'rsuite';
import TimeIcon from '@rsuite/icons/Time';
return (
<DateRangePicker caretAs={TimeIcon} />
)
```

fix(caretAs): fix DatePicker and DateRangePicker cannot replace caret

---

src/Sidenav/styles/index.less

fix(Sidenav): remove underline from focused sidenav item

---

src/InputNumber/InputNumber.tsx
src/InputNumber/test/InputNumberSpec.js

<kbd>Tab</kbd> sequence before
https://user-images.githubusercontent.com/8225666/158298382-e3b24fdf-9fb5-4a91-8c93-2e27743991ab.mov
<kbd>Tab</kbd> sequence after
https://user-images.githubusercontent.com/8225666/158298387-d88ddf30-89b0-4983-ba84-70ccc8500952.mov

fix(InputNumber): make plus/minus buttons un-focusable

---

src/SelectPicker/SelectPicker.d.ts
src/SelectPicker/SelectPicker.tsx
src/SelectPicker/test/SelectPickerSpec.js

Fix selectPicker when search is controlled and exit Dropdown without resetting external search
But there are other problems:
<br/>
1. When search and data are controlled => Input searchword => The selected value will be disappear 
&nbsp;&nbsp;&nbsp;&nbsp;<img width="313" alt="image" src="https://user-images.githubusercontent.com/53305259/159238914-ec0940f8-20f7-4f38-81ff-189b567f70af.png">
&nbsp;&nbsp;&nbsp;&nbsp;<img width="354" alt="image" src="https://user-images.githubusercontent.com/53305259/159238951-14d187a0-0339-40dd-b62f-fc334475725d.png">
&nbsp;&nbsp;&nbsp;&nbsp;I think the cause of this problem is the data is controlled, when searchWord was changed the data will be change ,then,the value is not in the data 
&nbsp;&nbsp;&nbsp;&nbsp;So, Maybe we  can keep a value item inside. …

fix: fix selectPicker when search is controlled and exit Dropdown without resetting external search

---

src/Dropdown/DropdownMenu.tsx
src/Dropdown/test/DropdownMenuSpec.js

The issue is `onSelect` is triggered twice.
```tsx
export default function Dropdown() {
const handleSelect = (eventKey: any) => {
console.log(eventKey);
};
return (
<>
<Dropdown.Menu onSelect={handleSelect}>
<Dropdown.Item eventKey={3}>Download As...</Dropdown.Item>
<Dropdown.Item eventKey={4}>Export PDF</Dropdown.Item>
<Dropdown.Item eventKey={5}>Export HTML</Dropdown.Item>
<Dropdown.Item eventKey={6}>Settings</Dropdown.Item>
<Dropdown.Item eventKey={7}>About</Dropdown.Item>
</Dropdown.Menu>
</>
);
}
```
Or Check the following Code Sandbox 
https://codesandbox.io/s/react-typescript-forked-iybjwt?file=/src/App.tsx
Click on any item on the dropdown then check the console log

Fixed Triggering onSelect twice on Dropdown Menu

---

docs/pages/components/checkbox/fragments/checkbox-group.md
docs/pages/components/checkbox/fragments/checkbox-groupinline.md
src/CheckPicker/test/CheckPickerSpec.js
src/Checkbox/Checkbox.tsx
src/Checkbox/test/CheckboxSpec.js
src/CheckboxGroup/test/CheckboxGroupSpec.js

> ## 🚨 HOTFIX
> 
> It's suggested that a new version is released as soon as this fix is merged.
Checkbox onChange callback is called with a wrong `checked` argument since #2419. See https://github.com/rsuite/rsuite/pull/2419/files#diff-bc30c797bcd9835ab75d581b4e2584161a4f00e7350bc299b943fe02283dcc16R133
The flaky test cases that were not able to find this issue are also updated.

fix(Checkbox): correct checked state in onChange callback

---

src/Toggle/Toggle.tsx
src/Toggle/test/ToggleSpec.js

fix(Toggle): add missing properties to onChange event target

---

src/Cascader/Cascader.tsx
src/Cascader/test/Cascader.test.tsx

`value` and `onChange(value)` type are now inferred from `data` item's `value` property.

fix(Cascader): infer value and onChange types from data

---

src/Dropdown/test/DropdownMenuSpec.js
src/Menu/MenuItem.tsx

Before
https://user-images.githubusercontent.com/8225666/162677534-90c1b924-419e-4e9a-9aa8-513b5fbf10c9.mov
After
https://user-images.githubusercontent.com/8225666/162677558-fc6b43bd-5900-4522-8580-ee9a24c814da.mov

fix(Dropdown.Menu): de-highlight item when mouse leaving

---

src/InputNumber/InputNumber.tsx
src/InputNumber/test/InputNumberSpec.js

- Rename `handlePlus`/`handleMinus` callbacks to `handleStepUp`/`handleStepDown` in favor of [HTMLInputElement native methods](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/stepUp)
- Remove `disabledUpButton`/`disabledDownButton` states which can be derived from props directly
- Other variable naming improvements
- Test script improvements

refactor(InputNumber): remove unnecessary states

---

docs/pages/components/dropdown/en-US/index.md
docs/pages/components/dropdown/zh-CN/index.md
src/Dropdown/Dropdown.tsx
src/Dropdown/test/DropdownSpec.js
src/Menu/Menu.tsx
src/Menu/test/MenuSpec.js

Adding controlled open state for `<Dropdown>`

feat(Dropdown): add `open` and `defaultOpen` props

---

src/ButtonToolbar/styles/index.less
src/ButtonToolbar/test/ButtonToolbarStyleSpec.js

According to design material, the gap between items in ButtonToolbar should have been 10px.

fix(ButtonToolbar): change item gap to 10px

---

src/Dropdown/test/DropdownMenuSpec.js
src/Menu/Menubar.tsx
src/utils/dom.ts

```jsx
<Dropdown.Menu>
<Dropdown.Item panel>
<Input />
</Dropdown.Item>
<Dropdown.Item>Item 1</Dropdown.Item>
</Dropdown.Menu>
```
Before
https://user-images.githubusercontent.com/8225666/165904206-33bc5db8-7355-4524-a13c-3554c7987e94.mov
After
https://user-images.githubusercontent.com/8225666/165904214-17b0898c-1996-4814-ab5e-77f5eb6e9fb9.mov

fix(Dropdown.Menu): fix unexpected highlight item when focus moving in

---

src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.js

Exposing the already existent renderTitle for calendars in DateRangePicker to allow custom titles.

feat(DateRangePicker): expose calendars renderTitle

---

src/Cascader/DropdownMenu.tsx

Apply [tree view pattern](https://www.w3.org/TR/wai-aria-practices-1.2/#TreeView) to Cascader's popup. For state as shown below
a11y before
a11y after

perf(Cascader): apply tree view pattern

---

src/Sidenav/SidenavToggle.tsx

When the `Sidenav` is expanded, the icon should be the left arrow, meaning that clicking on it will close the Sidenav, whereas in reality the icon is the right arrow in the expanded state, which makes it difficult for the user to understand the meaning of the icon in this scenario.
Here is `SidenavToggle` usage code.
The figure below should show the **left** arrow (in the expanded state)
The figure below should show the **right** arrow (in the unexpanded state)
There are sample: https://codesandbox.io/s/vibrant-snyder-kx3fnp?file=/src/index.tsx

SidenavToggle icon doesn't match its expand status

---

src/Sidenav/styles/index.less

fix(Sidenav): correct subtle Sidenav item hover styles

---

src/Sidenav/SidenavToggle.tsx
src/Sidenav/test/SidenavToggleSpec.js

Deprecate the standalone `expanded` prop on `<Sidenav.Toggle>`, instead inherit `expanded` prop from `Sidenav`.
Before
```jsx
<Sidenav expanded>
<Sidenav.Toggle expanded />
</Sidenav>
```
After
```jsx
<Sidenav expanded>
<Sidenav.Toggle />
</Sidenav>
```

refactor(Sidenav): deprecate expanded prop of Sidenav.Toggle

---

src/CheckTreePicker/test/CheckTreePickerSpec.js
src/CheckTreePicker/test/mocks.js
src/utils/treeUtils.ts

When node in data changes position, it's equivalent to changing the data. And selected this node again. Will getting duplicated key error in selected list.
Fix #2486

fix(CheckTreePicker): fix duplicated key when data changed (#2486)

---

src/styles/color-modes/light.less

perf(Dropdown): improve contrast of active Dropdown item background color

---

src/Sidenav/styles/index.less

fix(Sidenav): remove subtle item bg when focused by mouse

---

src/Button/styles/index.less

fix(Button): remove underline when hovered

---

docs/pages/components/message/fragments/import.md
docs/pages/components/message/fragments/with-toaster.md
docs/pages/components/message/index.tsx
docs/pages/components/notification/fragments/import.md
docs/pages/components/notification/fragments/with-toaster.md
docs/pages/components/notification/index.tsx
docs/pages/components/notification/zh-CN/toaster.md
src/CustomProvider/CustomProvider.tsx
src/index.tsx
src/toaster/ToastContainer.tsx
src/toaster/index.tsx
src/toaster/test/useToasterSpec.js
src/toaster/toaster.tsx
src/toaster/useToaster.ts
src/utils/useCustom.ts

The implementation principle of `toaster` is to render `Message` and `Notification` to a separate DOM tree through `ReactDOM.render`.
Doing so will cause a problem, components inside `Message` and `Notification` will not be able to obtain the context value provided by `CustomProvider`, including the implementation of localization functions will become very complicated.
To solve this problem, use `ReactDOM.createPortal` instead of `ReactDOM.render` to share context. So the `useToaster` hook was added to replace toaster.
----
Before
```tsx
import { toaster } from 'rsuite';
toaster.push(<Notification>message</Notification>, {
placement: 'topEnd'
});
```
After
```tsx
import { useToaster } from 'rsuite';
const toaster = useToaster();
toaster.push(<Notification>message</Notification>, { …
```

feat(toaster): add support for useToaster

---

src/Dropdown/styles/index.less
src/styles/variables.less

fix(Dropdown): fix vertical alignment of submenus

---

docs/pages/components/nav/en-US/index.md
docs/pages/components/nav/zh-CN/index.md
docs/pages/components/navbar/fragments/basic.md
src/Dropdown/styles/index.less
src/Nav/NavDropdownMenu.tsx
src/Nav/test/Nav.test.tsx
src/Navbar/NavbarDropdownMenu.tsx

Close #2267
Add `openDirection` prop for specifying the opening direction of a submenu.
`openDirection="end"` (default), submenu opens towards the tail of reading direction (right by default, left in RTL)
`openDirection="start"`, submenu opens towards the head of reading direction (left by default, right in RTL)

feat(Nav.Menu): add `openDirection` prop

---

src/Table/Table.tsx

This PR is an improvement over the exported types for the Table Cell props. 
Current issue is that when a consumer wants to create their own custom cells all sense of typing is lost because of very unrestricted types. With this type we keep the possibility of open types (so keeping backward compatibility) but add the possibility of being more restrictive and have better typing .

refactor(Table): improve cellprops type for better extended usage

---

karma.conf.js
src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.js

example: https://stackblitz.com/edit/react-c42wf5?file=package.json,src%2Findex.js
When click the close icon of label1, and then click the close icon of label2, It will be open all.
I think it has always existed.Then this [pr](https://github.com/rsuite/rsuite/pull/2372) exposed it.

fix:  when data changes Cannot close

---

src/Overlay/Overlay.tsx
src/Overlay/OverlayTrigger.tsx
src/Overlay/Position.tsx
src/Overlay/positionUtils.ts
src/Picker/PickerToggleTrigger.tsx
src/Whisper/test/Whisper.test.tsx

Let users know what props will be passed in when using `speaker` function

fix(Whisper): specify speaker function argument types

---

src/InputGroup/InputGroupAddon.tsx
src/InputGroup/test/InputGroup.test.tsx

Allow `<InputGroup.Addon>` to receive additional props passed down to `as` element so that users could use it as label for an input

fix(InputGroup.Addon): extend props from as element

---

src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.js

fix https://github.com/rsuite/rsuite/issues/2553

fix(DateRangePicker): fix Ok button not clickable

---

package-lock.json
package.json

* **ObjectType:** specifies type of property `object` in the `ObjectType` check result ([#46](https://github.com/rsuite/schema-typed/issues/46)) ([0571e09](https://github.com/rsuite/schema-typed/commit/0571e097217b0c999acaf9e5780bdd289aa46a46))

build(deps): bump schema-typed from 2.0.2 to 2.0.3

---

docs/package-lock.json
docs/pages/components/check-picker/en-US/index.md
docs/pages/components/check-picker/fragments/with-label.md
docs/pages/components/check-picker/zh-CN/index.md
docs/pages/components/select-picker/en-US/index.md
docs/pages/components/select-picker/fragments/with-label.md
docs/pages/components/select-picker/zh-CN/index.md
src/CheckPicker/test/CheckPickerSpec.js
src/Picker/PickerToggle.tsx
src/Picker/styles/index.less
src/SelectPicker/test/SelectPickerSpec.js

Add `label` prop to allow users to display a label before picker placeholder and selected values.

feat(SelectPicker,CheckPicker): add label prop

---

src/CheckPicker/CheckPicker.tsx
src/CheckPicker/test/CheckPicker.test.tsx
src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePicker.test.tsx
src/InputPicker/InputPicker.tsx
src/InputPicker/test/InputPicker.test.tsx
src/SelectPicker/SelectPicker.tsx
src/SelectPicker/test/SelectPicker.test.tsx
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreePicker.test.tsx

The `caretAs` prop is missing on the `SelectPickerProps`, because of this when you use the `SelectPicker` component in a TS project, it gives an error that `caretAs` is not a valid prop.
The docs specify the `SelectPicker` component admits the prop in question.
https://rsuitejs.com/components/select-picker/#props

fix(SelectPicker): add caretAs prop to SelectPickerProps interface

---

src/Cascader/test/CascaderSpec.js
src/Cascader/utils.ts
src/CheckTreePicker/test/CheckTreePickerSpec.js
src/CheckTreePicker/utils.ts
src/MultiCascader/test/MultiCascaderSpec.js
src/MultiCascader/utils.ts
src/TreePicker/test/TreePickerSpec.js
src/utils/attachParent.ts
src/utils/treeUtils.ts

during render, each data item will be add a `parent` props, which has a children collection includes current item, cause a circular reference
```ts
const parent = {
name: 'parent',
children: [{
name: 'child-1',
},{
name: 'child-2',
}]
}
parent.children.forEach(child => {
child.parent = parent;
})
```
[JSON.stringify][1] only serialized enumerable properties. using [Object.defineProperty][2] mark `parent` as `enumerable: false`.
```js
const parent = {
name: 'parent',
children: [{
name: 'child-1',
},{
name: 'child-2',
}]
}
parent.children.forEach(child => {
Object.defineProperty(child, 'parent', {
value: parent,
writable: false,
enumerable: false,
configurable: true
})
})
```
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description …

fix(treelike): fix data item stringify throw error

---

src/Panel/Panel.tsx
src/Panel/test/PanelSpec.js

When passing an element as Panel's `header`, the caret icon disappears in a collapsible panel.
```jsx
<Panel header={<span>Panel title</span>} bordered collapsible>
Panel content
</Panel>
```
Same JSX results in
Note the caret icon displayed on the right-hand side.

fix(Panel): allow custom header in collapsible panels

---

src/DateRangePicker/Calendar.tsx
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/utilsSpec.js
src/DateRangePicker/utils.ts

There is currently a limitation in the calendar. The start date and the end date cannot be the same month, which will result in no way to turn to the next month when selecting the start date, and the month of the end date must be changed. This experience can be confusing to users, so this restriction is lifted.
When the start month and end month are the same month, the other calendar will automatically update to the adjacent month.
Before
https://user-images.githubusercontent.com/1203827/181158188-17508a12-7645-4f24-b3b7-077e25c3ea81.mp4
After
https://user-images.githubusercontent.com/1203827/181158369-52ce1be1-4918-42f6-ba87-521dbe07f8d0.mp4

fix(DateRangePicker): improved experience for date range selection

---

src/DatePicker/DatePicker.tsx
src/DatePicker/test/DatePickerSpec.js
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.js
src/Overlay/OverlayTrigger.tsx
src/Picker/PickerToggle.tsx
src/Picker/styles/index.less

fix not opening calendar picker when focused
- Contains components: DatePicker, DateRangePicker
- Browser:  Firefox
The onFocus event will be triggered twice on click.
fix not switching the previous element when pressing `Shift` + `Tab`

fix(DatePicker): fix issues with focus event

---

docs/pages/components/auto-complete/en-US/index.md
docs/pages/components/auto-complete/fragments/basic.md
docs/pages/components/auto-complete/fragments/controlled.md
docs/pages/components/auto-complete/fragments/disabled.md
docs/pages/components/auto-complete/fragments/email.md
docs/pages/components/auto-complete/fragments/input-group.md
docs/pages/components/auto-complete/fragments/render-item.md
docs/pages/components/auto-complete/zh-CN/index.md
src/AutoComplete/AutoComplete.tsx
src/AutoComplete/test/AutoCompleteSpec.js

fix(AutoComplete): fix `listbox` not keeping the same width as `input`

---

docs/pages/components/date-picker/fragments/basic.md
docs/pages/components/date-picker/fragments/format.md
docs/pages/components/date-picker/index.tsx
docs/pages/components/date-range-picker/fragments/format-date-time.md
src/Calendar/test/useCalendarDateSpec.js
src/Calendar/useCalendarDate.ts
src/DatePicker/DatePicker.tsx
src/DatePicker/test/DatePickerSpec.js
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.js
src/utils/dateUtils.ts

fix: https://github.com/rsuite/rsuite/discussions/2597#discussioncomment-3177984

fix(DateRangePicker): fix default time not working

---

src/Button/styles/index.less

Currently, Button doesn't use @cursor-disabled variable in disabled state. It uses hardcoded value 'not-allowed'. This PR adds an ability to customise cursor in disabled state for Button component.
BTW, there are lot of components with the same issue. 
```bash
% grep -R 'cursor: not' src/                
src//RadioGroup/styles/index.less:    cursor: not-allowed;
src//Uploader/styles/index.less:      //cursor: not-allowed;
src//Uploader/styles/index.less:        cursor: not-allowed !important;
src//Uploader/styles/index.less:    cursor: not-allowed;
src//Uploader/styles/index.less:      cursor: not-allowed;
src//Uploader/styles/index.less:    cursor: not-allowed;
src//Rate/styles/index.less:    cursor: not-allowed;
src//Calendar/styles/index.less:      cursor: not-allowed; …
```

fix(Button): use @cursor-disabled intead of hardcoded cursor

---

src/FormControl/FormControl.tsx
src/FormControl/test/FormControlSpec.js

Pass `className` prop to accepter component instead of applying it on FormControl wrapper element. This used to work in v4 but seemed to be accidentally broken in v5.
v4
v5

fix(Form.Control): apply className to accepter component

---

docs/pages/_common/types/range.md
docs/pages/components/date-range-picker/fragments/custom-shortcut-options.md
docs/pages/components/date-range-picker/index.tsx
src/DatePicker/PredefinedRanges.tsx
src/DatePicker/Toolbar.tsx
src/DatePicker/styles/index.less
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/styles/index.less
src/DateRangePicker/test/DateRangePickerSpec.js
src/DateRangePicker/types.ts

```diff
<DateRangePicker
ranges={[
{
label: 'Today',
value: [new Date(), new Date()],
+     // Sets the position where the predefined range is displayed, the default is bottom.
+     // Only supported on DateRangePicker。
+     placement: 'left'
}
]}
/>;
```
> https://rsuite-nextjs-git-feat-daterangepicker-rsuite.vercel.app/components/date-range-picker/#predefined-date-ranges

feat(DateRangePicker): supports placing predefined ranges on the left

---

docs/pages/components/popover/en-US/index.md
docs/pages/components/popover/zh-CN/index.md
docs/pages/components/tooltip/en-US/index.md
docs/pages/components/tooltip/zh-CN/index.md
docs/pages/components/whisper/en-US/index.md
docs/pages/components/whisper/en-US/props.md
docs/pages/components/whisper/zh-CN/index.md
docs/pages/components/whisper/zh-CN/props.md

docs(Tooltip,Popover): fixed TS declarations not being clickable

---

docs/pages/components/input/fragments/masked-input.md
src/InputGroup/styles/index.less

fix(InputGroup): fix icons not being vertically centered within the input

---

src/CheckTreePicker/styles/index.less
src/CheckTreePicker/test/CheckTreePickerStylesSpec.js

**Problem**
when first level of data is in the uncheckable state, the padding-left value of the node label is incorrect.
**Expected**
the padding-left value should be correct.

fix(CheckTreePicker): fix uncheckable style errors

---

docs/pages/components/list/en-US/index.md
docs/pages/components/list/fragments/sort-fixed.md
docs/pages/components/list/zh-CN/index.md
src/List/helper/useSortHelper.ts

in the previous list, elements can be sorted by `collection`. but the same collection cannot be separated. which mean you can only group member along with each other.
this PR only changes the ListItem animation style, fulfilling cross collection sort has to change the `onSort` callback
```js
const handleSort = ({ collection, oldIndex, newIndex }) =>
setData(prvData => {
const moveData = prvData[oldIndex];
const siblingData = prvData.filter(
(item, index) => item.collection === collection && index !== oldIndex
);
const newData = [...prvData].map((item, index) => {
if (item.collection == collection) {
if (index === newIndex) {
return moveData;
}
return siblingData.shift();
}
return item;
});
return newData;
}, []);
```
- group A(1)
- group A(2)
- group B(1)
- group B(2)
- group A(1)
- group …

feat(List): allow sort with non-adjacent collection

---

src/Dropdown/DropdownMenu.tsx
src/Dropdown/test/DropdownMenuSpec.js

Custom `className` was overriding rsuite classNames.
```jsx
<Dropdown.Menu className="custom" />
```
Before
After

fix(Dropdown.Menu): fix custom className overriding rsuite classNames

---

src/List/helper/useSortHelper.ts

set list item `helper / holder` classname as const. stop using classList from dom.
```js
const helperElementClass = 'rs-list-item-helper';
const holderElementClass = 'rs-list-item-holder';
```
close #2696

fix(List): fix sort style with custom className

---

src/Nav/styles/index.less
src/Nav/test/NavStylesSpec.js

fix(Nav): fix incorrect height of <Nav.Menu>, fix #2678

---

docs/pages/components/stack/fragments/space.md

in `spacing` example
Slider initial value(`undefined`) is different with useState(`6`)
```js
const [size, setSize] = useState(6);
<Slider style={{ width: 300 }} onChange={value => setSize(value)} />
```

docs(Stack): fix spacing doc initial value

---

docs/pages/components/button/en-US/index.md
docs/pages/components/button/zh-CN/index.md
src/Button/test/ButtonSpec.js

Add "Accessing DOM" section for `Button` documentation. https://rsuite-nextjs-git-test-button-ref-rsuite.vercel.app/components/button/#accessing-dom

Add test case and documentation for `ref` attribute of `Button`

---

src/Stack/Stack.tsx
src/utils/BrowserDetection.ts

`spacing` under **chrome 71**
flexbox-gap compat
- Chrome 84+
- Safari 14.1+
> compatibility table https://caniuse.com/flexbox-gap
add `isSupportFlexGap` for Stack to check browser support

fix(Stack): fix spacing compat for chrome under 84

---

docs/pages/components/stack/en-US/index.md
docs/pages/components/stack/fragments/adjust-single-item.md
src/Stack/Stack.tsx
src/Stack/StackItem.tsx
src/Stack/test/StackItemSpec.js

add `Stack.Item` to set single child position
|props |value |
|--|:--|
|alignSelf|'flex-start', 'flex-end' , 'center' , 'baseline','stretch'|
|flex|`string`|
|grow|`number`|
|shrink|`number`|
|basis|`string`|
|order|`string`|
```js
<Stack>
<div>...</div>
<Stack.Item grow={1}>test</Stack>
</Stack>
```

feat(Stack): add `Item` to adjust single child

---

docs/pages/components/form/en-US/index.md

Chinese appears in English documents
See: https://rsuitejs.com/components/form/#code-lt-form-gt-code

docs(Form): remove typo

---

src/Stack/Stack.tsx
src/Stack/test/StackSpec.js

use `React.Children.toArray` remove empty children like `null`, `undefined` & `boolean` value.
close #2731

fix(Stack): filter children that should not be rendered

---

docs/pages/components/check-tree-picker/en-US/extra-footer.md
docs/pages/components/check-tree-picker/index.tsx
docs/pages/components/check-tree-picker/zh-CN/extra-footer.md
docs/pages/components/tree-picker/en-US/extra-footer.md
docs/pages/components/tree-picker/index.tsx
docs/pages/components/tree-picker/zh-CN/extra-footer.md
src/CheckTreePicker/CheckTreePicker.tsx
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreePickerSpec.js
src/utils/treeUtils.ts

There are two problems when setting the `virtualized` prop:
* `TreePicker`, `CheckTreePicker` doesn't  display the content of `renderExtraFooter()`. Closes #2759 
* `TreePicker` doesn't display all nodes when setting the `defaultExpandAll` prop

Fix TreePicker and CheckTreePicker problems when setting the virtualized prop

---

src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.js

The reason for this Problem is the same as #2621.
But this Pull Request is forgotten to handle the virtualized mode. 
Closes #2782

fix(CheckTreePicker): fix children node can't uncheck when setting virtualized (#2782)

---

src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.js
src/CheckTreePicker/utils.ts
src/Tree/test/TreeSpec.js
src/TreePicker/test/TreePickerSpec.js
src/utils/treeUtils.ts

There are two improvements
**1. Remove `shallowEqual` function**
After rsuite v5, the value type only supports `string | number`, so it's not need to use `shallowEqual`
**2. Reduce unnecessary traverse**
1. Change `refKey` to formatted value: `String_value` or `Numer_value`. The purpose is to get the node directly from the value key without traverse all data
2. Reduce `getSelectedItems()` loops.
3. Using `useMemo()`  to memorize data

perf(CheckTreePicker): improve performance when using large data 

---

src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.js
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreePickerSpec.js

When CheckTreePicker, TreePicker setting `cleanable=false` or `disabled=true` prop, the backspace operation still works.
It's not expected behavior.

fix(TreePicker, CheckTreePicker): ignore backspace when setting cleanable=false or disabled=true

---

src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.js
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreePickerSpec.js

If the value is controlled, the developer should handle all the `value`. 
When clicking the clean icon, the checktreepicker will remove all values internally, whether value controlled or not.
When clicking the clean icon, if the value is controlled, CheckTreePicker shouldn't remove all values.
Closes #2784

fix(TreePicker,CheckTreePicker): fix value being cleared internally when value is controlled

---

src/CheckPicker/test/CheckPickerStylesSpec.js
src/Windowing/AutoSizer.tsx

The width of the virtualized list did not change with the width of the container.

fix(AutoSizer): fix virtualized list width not being updated

---

docs/pages/components/check-picker/en-US/index.md
docs/pages/components/check-picker/fragments/loading.md
docs/pages/components/check-picker/zh-CN/index.md
docs/pages/components/select-picker/en-US/index.md
docs/pages/components/select-picker/fragments/loading.md
docs/pages/components/select-picker/zh-CN/index.md
src/CheckPicker/test/CheckPickerSpec.js
src/Picker/PickerToggle.tsx
src/Picker/PickerToggleTrigger.tsx
src/Picker/styles/index.less
src/Picker/test/PickerToggleSpec.js
src/SelectPicker/SelectPicker.tsx
src/SelectPicker/test/SelectPickerSpec.js

Add this `loading` prop for indicating that a picker is preparing data and not ready for use.
https://rsuite-nextjs-git-feature-selectpicker-loading-rsuite.vercel.app/components/select-picker/#loading-state
```jsx
<SelectPicker data={data} loading />
<SelectPicker label="User" data={data} loading />
```

feat(SelectPicker,CheckPicker): add `loading` prop

---

src/Picker/PickerToggle.tsx

fix(pickers): fix text overflow issue on option values

---

scripts/proxyDirectories.js

when i change project dir and build, i get the /lib/projectname-Button/
because my project dir contains '-'

fix(gulp): dir contains '-' or '_ ' not replaced

---

src/Form/Form.tsx
src/FormControl/test/FormControlSpec.js

Look at this [example](https://stackblitz.com/edit/react-mpmto6?file=src%2FApp.jsx,package.json,src%2Findex.js), Change the `username` input, and then close the toggle.
When the children component unmounts, Its called function is an old rending frame, so if two fields have linkage logic when one field changes, and then the other field unmounts, it will override.

fix: when shouldResetWithUnmount should remove value and error

---

README.md
README_zh.md
docs/pages/guide/usage/en-US/index.md
docs/pages/guide/usage/zh-CN/index.md

```diff
- ReactDOM.render(<App />, document.getElementById('root'));
```
`ReactDOM.render` can only run on versions prior to react 18. It was removed to avoid ambiguity in the documentation guide.

docs(usage): remove `ReactDOM.render` for react 18

---

docs/pages/components/date-range-picker/fragments/controlled.md
docs/pages/components/date-range-picker/fragments/editable.md
docs/pages/components/date-range-picker/fragments/format-date-time.md
docs/pages/components/date-range-picker/fragments/one-tap.md
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.js

When a date range is selected on a calendar, the end time still uses the time on the first calendar. But the end time should always use the time on the second calendar.
fix: https://codesandbox.io/s/stoic-sun-fgw8er

fix(DateRangePicker): fix end time not using time on second calendar

---

src/Table/styles/index.less

An unreasonable transition will make it appear stuttering during the interactive experience.
https://user-images.githubusercontent.com/1203827/199634230-977f7cac-c59d-423b-a596-e76252fcd225.mp4
https://user-images.githubusercontent.com/1203827/199634227-6dd88e70-194a-4bbb-ac24-5f29edede726.mp4

fix(Table): remove transition on hover of table row

---

docs/pages/components/table/en-US/index.md
docs/pages/components/table/fragments/full-text.md
docs/pages/components/table/zh-CN/index.md
docs/utils/mock.ts
package-lock.json
package.json
src/Table/styles/index.less
src/styles/variables.less

Display the hidden text in its entirety when hovering over the cell.
https://user-images.githubusercontent.com/1203827/199677220-f1f2f5d8-544c-40cf-b4ac-91434f4c7317.mp4
```tsx
<Column width={130} fullText>
<HeaderCell>Name</HeaderCell>
<Cell dataKey="name" />
</Column>
```
- https://github.com/rsuite/rsuite/pull/2858
- build(deps): bump rsuite-table from 5.7.2 to 5.8.0

feat(Table): support for show full text when hovering over a cell

---

karma.conf.js
src/InputNumber/InputNumber.tsx
src/InputNumber/test/InputNumberSpec.tsx

Cannot block the default onWheel event when `scrollable = false`. This will cause the value to be updated. The issue occurs with the latest versions of chrome and edge browsers. 
fix https://github.com/rsuite/rsuite/issues/2903.

fix(InputNumber): fix `scrollable` not working

---

src/DateRangePicker/test/utilsSpec.tsx

When run in December, the `getMonth(rangeDate[1]) - getMonth(rangeDate[0])` would equal `-11` instead of `1`, causing the tests to fail.

test(DateRangePicker): fix flaky test cases

---

src/Cascader/test/CascaderSpec.tsx
src/CheckPicker/test/CheckPickerSpec.tsx
src/Picker/utils.ts

When we operate the options through the up and down keys of the keyboard, the options that are not in the visible area should automatically scroll to the visible area, so that we can see the content of the options. 
- Autocomplete, fix https://github.com/rsuite/rsuite/issues/2872
- SelectPicker
- CheckPicker
- InputPicker
- TagPicker 
- Cascader
- MutiCascader
https://user-images.githubusercontent.com/1203827/205265558-6865af20-75e7-479d-a0c2-abb084d18e28.mp4
https://user-images.githubusercontent.com/1203827/205265990-d2cf3f0f-f676-4579-b26a-d69b286ff87f.mp4

fix(pickers): the focused item should be within the container's viewport

---

src/FormHelpText/styles/index.less
src/FormHelpText/test/FormHelpTextStylesSpec.tsx

Form.HelpText should have had a fontSize of `12px`, according to design materials. https://www.figma.com/file/uEq9QBplcKUYZrcWWA3RK2/NXT-UI?node-id=0%3A9099&t=H5h3Dd3AnJVgbAbz-4

fix(Form.HelpText): change font size to 12px

---

src/Tooltip/styles/index.less

fix(Tooltip): should use the default text alignment

---

src/Nav/NavDropdownMenu.tsx
src/Nav/test/NavMenuSpec.tsx

当 `<Nav.Menu>` 组件被嵌套时，会返回 `NavDropdownMenu` 组件，但是 `NavDropdownMenu` 并没有支持通过 `noCaret `属性配置小箭头图标的隐藏，因此此处通过为 `NavDropdownMenu` 组件接收 `noCaret` 属性并根据该属性控制是否显示小箭头图标。
问题来源:  [#2959](https://github.com/rsuite/rsuite/issues/2959)
修改前后示例：
**修改前**
**修改后**

fix(NavMenu): fix `noCaret` has No Effect on a Sub-menu

---

src/Modal/styles/index.less
src/styles/variables.less

1. The close button should have been aligned with the title by their top edges, according to [design materials](https://www.figma.com/file/uEq9QBplcKUYZrcWWA3RK2/NXT-UI?node-id=0%3A1348&t=H5h3Dd3AnJVgbAbz-4).
2. Add a hover color

fix(Modal): fix close button alignment and color

---

src/AutoComplete/test/utilsSpec.ts
src/AutoComplete/utils.ts
src/Cascader/Cascader.tsx
src/Cascader/utils.ts
src/CheckPicker/CheckPicker.tsx
src/MultiCascader/utils.ts
src/Picker/utils.ts
src/TreePicker/TreePicker.tsx
src/utils/test/treeUtilsSpec.ts
src/utils/treeUtils.ts

The problem with `ItemDataType` is that the `{ label; value; children; }` structure can be inaccurate, respecting `labelKey`/`valueKey`/`childrenKey` arguments.
There is currently an abuse of `ItemDataType` across Picker components, making it hard to apply fixes and refactoring in those components. The first step of removing inappropriate usage of `ItemDataType` is to make picker utils generic - they are bound to `ItemDataType` and used all across picker components.

refactor(utils): make Picker utils generic

---

src/Button/test/ButtonStylesSpec.tsx
src/ButtonToolbar/ButtonToolbar.tsx
src/ButtonToolbar/styles/index.less
src/ButtonToolbar/test/ButtonToolbar.text.tsx
src/ButtonToolbar/test/ButtonToolbarSpec.tsx
src/ButtonToolbar/test/ButtonToolbarStyleSpec.tsx
src/Stack/Stack.tsx
src/Stack/test/StackSpec.tsx

refactor(ButtonToolbar): use `Stack` as a container to adapt mobile

---

src/Dropdown/Dropdown.tsx
src/Dropdown/DropdownItem.tsx
src/Dropdown/DropdownSeparator.tsx
src/Dropdown/test/DropdownItemSpec.tsx
src/Dropdown/test/DropdownSeparatorSpec.tsx
src/Dropdown/test/DropdownSpec.tsx
src/utils/deprecatePropType.ts

Deprecate `divider` prop of Dropdown.Item component in favor of a dedicated Dropdown.Separator component.
Before
```jsx
<Dropdown>
<Dropdown.Item divider />
</Dropdown>
```
After
```jsx
<Dropdown>
<Dropdown.Separator />
</Dropdown>
```
- It's difficult to separate unused props passed to Dropdown.Item when `divider` flag is set, thus a dedicated component is needed
- The naming of "divider" is changed to "separator", respecting [ARIA APG menu pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menu)
Documentation will be updated in a separate PR after this change is released, in order to avoid breaking the production build.

feat(Dropdown): add Dropdown.Separator component

---

src/Calendar/MonthDropdown.tsx
src/DatePicker/DatePicker.tsx
src/DatePicker/test/DatePickerSpec.tsx

[This example on rsuitejs.com](https://rsuitejs.com/components/date-picker/#disabled-and-read-only) shows that current month (2022-12) is selectable, but when it's selected the OK button is disabled. 
```jsx
<DatePicker
format="yyyy-MM"
disabledDate={date => isBefore(date, new Date())}
/>
```
The select date button is disabled only when every date in that month is disabled, but the OK button is disabled when the selected date is disabled.

fix(DatePicker): fix inconsistency between month selectable state and ok button clickable state

---

src/Sidenav/ExpandedSidenavDropdownMenu.tsx
src/Sidenav/styles/index.less
src/Sidenav/test/SidenavSpec.tsx

~~~jsx
<Sidenav defaultOpenKeys={['1', '1-1' ]}>
<Sidenav.Body>
<Nav>
<Nav.Menu eventKey="1" title="menu1">
<Nav.Menu eventKey="1-1" title="menu2">
<Nav.Menu eventKey="1-1-1" title="menu3" />
</Nav.Menu>
</Nav.Menu>
</Nav>
</Sidenav.Body>
</Sidenav>
~~~
当 `Sidenav` 中的 `<Nav.Menu>` 嵌套至第三层或更多层时，从第三层开始，其箭头图标的方向不会随着其内部内容的折叠或展开状态而改变。
当  `<Nav.Menu>`  第三层的内部内容的状态为展开且对第二层进行折叠时，第三层的箭头图标会随着第二层的箭头图标进行更改。
https://user-images.githubusercontent.com/112228030/209444808-8d867122-bec1-47b9-99c8-a13aee04b6f1.mov
https://user-images.githubusercontent.com/112228030/209445105-006bd62f-22c4-46a9-9e35-a8609a64af7f.mov
close #2985

fix(Sidenav): fix Sidenav multilevel Nav.Menu arrow icon exception

---

src/Tree/test/TreeSpec.tsx
src/TreePicker/TreeNode.tsx
src/TreePicker/TreePicker.tsx
src/TreePicker/styles/index.less
src/utils/treeUtils.ts

This PR fixes an issue where the Tree drag style is not expected as designed.
**Problem:**
**Design:**
The issue was caused by https://github.com/rsuite/rsuite/pull/2237.
To avoid the drag preview appearing on the page, I add the style `z-index:-1` for the preview node, to ensure that it does not affect the page display. And the test case has been added.
With this fix, the Tree component should be able to function correctly and have a more aesthetically pleasing appearance when dragging.
Preview Link: https://rsuite-nextjs-git-fix-tree-drag-preview-rsuite.vercel.app/components/tree/#draggable

fix(Tree): fix Tree drag preview style error

---

src/Picker/styles/index.less
src/Picker/styles/mixin.less
src/Sidebar/test/SidebarStylesSpec.tsx
src/styles/variables.less

The meaning of animation transition is to make the interactive experience better, but if the transition duration is too long, it will feel unsmooth.

fix(CSS transitions): improved duration of transitions

---

docs/pages/components/breadcrumb/en-US/index.md
docs/pages/components/breadcrumb/zh-CN/index.md
src/Breadcrumb/BreadcrumbItem.tsx
src/Breadcrumb/test/BreadcrumbItemSpec.tsx

fix: https://github.com/rsuite/rsuite/issues/2976

fix(Breadcrumb): fix breadcrumbs being rendered as `<span>` by default

---

src/Picker/PickerToggle.tsx
src/Picker/styles/index.less
src/Picker/styles/mixin.less
src/Picker/test/PickerToggleSpec.tsx

Talking with designer @LeightonYao, it was decided to move the clear button on the picker to the right and hide the arrow icon.
- Cascader
- CheckPicker
- CheckTreePicker
- DatePicker
- DateRangePicker
- InputPicker
- MultiCascader
- SelectPicker
- TagPicker
- TagInput
- TreePicker

refactor(pickers): adjust the position of the clear button

---

docs/pages/components/custom-provider/en-US/index.md
docs/pages/components/custom-provider/zh-CN/index.md
src/CustomProvider/CustomProvider.tsx
src/CustomProvider/test/CustomProviderSpec.tsx
src/Picker/PickerToggleTrigger.tsx
src/Ripple/Ripple.tsx
src/utils/useCustom.ts

Many developers in the community want to disable the ripple effect, so add a configuration that can disable ripples on `CustomProvider`.
```tsx
<CustomProvider disableRipple>
<Button>no ripple effect</Button>
</CustomProvider>
```
Affected components include: `Button`, `Nav.Item`, `Pagination`

feat(CustomProvider): add support for disableRipple on `<CustomProvider>`

---

src/Calendar/useCalendarDate.ts
src/DatePicker/DatePicker.tsx
src/DatePicker/test/DatePickerSpec.tsx

fix: https://github.com/rsuite/rsuite/issues/3043 
> https://codesandbox.io/s/dreamy-water-vwvyul
https://user-images.githubusercontent.com/1203827/215687601-f32995f8-6a17-49d1-81d8-44182aeeb840.mp4
https://user-images.githubusercontent.com/1203827/215687634-da7dad7b-0f44-432b-9f44-8e9db07d1521.mp4

fix(DatePicker): fix uncontrolled default date on calendar

---

src/Form/Form.tsx
src/FormControl/test/FormControlSpec.tsx

When several components unmount at the same time.
React will call them one by one, and the later ones will overwrite the earlier ones.

fix(form.control): shouldResetWithUnmount isn't working

---

docs/pages/components/button/en-US/index.md
docs/pages/components/button/fragments/custom.md
docs/pages/components/button/zh-CN/index.md
src/Button/Button.tsx
src/Button/styles/index.less
src/Button/test/ButtonSpec.tsx
src/styles/variables.less

Add `startIcon` and `endIcon` props to specify an icon element placed before/after text content in a Button.
Design material: https://www.figma.com/file/uEq9QBplcKUYZrcWWA3RK2/NXT-UI?node-id=0%3A2050&t=V95uYVLyuHWmOIYM-4
You have to handle alignment if putting icon element as `children`, otherwise you get misaligned icons as shown below.
(This is an example from rsuitejs.com)
`start/end` indicates whether the icon is placed _before_/_after_ the text, which is not bound to be left/right if taking RTL situations into account.

feat(Button): add startIcon and endIcon props

---

docs/pages/components/whisper/en-US/props.md
docs/pages/components/whisper/zh-CN/props.md
src/Overlay/test/OverlayTriggerSpec.tsx

close: https://github.com/rsuite/rsuite/issues/3062
```tsx
<Whisper
open={open}  // Controlled Whisper
speaker={<Popover>...</Popover>}
>
Content
</Whisper>
```

docs(Whisper): support defaultOpen and open on `<Whisper>`

---

docs/pages/components/message/fragments/with-toaster.md
docs/pages/components/notification/en-US/toaster.md
docs/pages/components/notification/zh-CN/toaster.md
src/Message/Message.tsx
src/Message/test/MessageSpec.tsx
src/Notification/Notification.tsx
src/Notification/test/NotificationSpec.tsx
src/toaster/ToastContainer.tsx
src/toaster/ToastContext.ts
src/toaster/test/useToasterSpec.tsx
src/toaster/toaster.tsx
src/toaster/useToaster.ts

fix: https://github.com/rsuite/rsuite/issues/3056
```tsx
toaster.push(<Message duration={2000}>message</Message>);
```
```tsx
toaster.push(<Message>message</Message>, {
duration: 2000
});
```

fix(Message,Notification): duration property migrated to `toaster.push` option

---

src/locales/hu_HU.ts
src/locales/index.ts

Added the Hungarian locale (hu_HU)

feat: added Hungarian locale (hu_HU)

---

src/DateRangePicker/test/DateRangePickerSpec.tsx
src/Picker/PickerToggleTrigger.tsx

fix picker components with `PickerToggleTrigger`, with {onEnter,onExited,...} props set, the inner life cycle couldn't fire.
Fixes #3073

fix(DateRangePicker): fix lifecycle for Picker Toggle

---

docs/pages/guide/i18n/en-US/index.md
docs/pages/guide/i18n/zh-CN/index.md

docs(i18n): add guidance on support Hungarian

---

src/Button/styles/index.less

Button content alignment was broken since `display` is updated to `inline-flex` in #3067. This affects Buttons with explicitly specified width. 
A repro can be found in Sidenav example on docs site https://rsuitejs.com/components/sidenav/#appearance

fix(Button): fix Button content not center-aligned

---

docs/pages/components/whisper/en-US/props.md
docs/pages/components/whisper/zh-CN/props.md

-reordered (corrected) the position of text in documentation [LinkToDoumentation](https://rsuitejs.com/components/tooltip/#code-lt-whisper-gt-code)

Issue : Update props.md

---

package-lock.json
package.json

* addAsyncRule to allow sync and async rules to run ([#63](https://github.com/rsuite/schema-typed/issues/63)) ([574f9ad](https://github.com/rsuite/schema-typed/commit/574f9ad973af97b8c1bae44c3fcfa3dad608c4d6))
* promises where not allowed by type ([#61](https://github.com/rsuite/schema-typed/issues/61)) ([9cc665c](https://github.com/rsuite/schema-typed/commit/9cc665c4f72b5a22942d351c961263c179888a7a))

build(deps): bump schema-typed from 2.0.3 to 2.1.0

---

src/AutoComplete/AutoComplete.tsx
src/AutoComplete/test/AutoCompleteSpec.tsx

Can I add `autoComplete` to FormControlBaseProps?
I have noticed that many components use FormControlBaseProps, but I think this will not affect, coz all are `Input`
Link #3105

feat(common): add autoComplete for FormControlBaseProps

---

package-lock.json
package.json
src/Table/Table.tsx
src/Table/index.tsx
src/Table/test/Table.test.tsx

* **Table:** fix missing `ref` in type definition ([#411](https://github.com/rsuite/rsuite-table/issues/411)) ([28338ee](https://github.com/rsuite/rsuite-table/commit/28338ee30ad3a75d0c95fc216aab67116c5bd9c6))
* **Table:** fix column misalignment after data update ([#409](https://github.com/rsuite/rsuite-table/issues/409)) ([e3bdb00](https://github.com/rsuite/rsuite-table/commit/e3bdb00a8a237139c5eb955c4acc13fc1a72a4f6))
* **Table:** support generic props ([#410](https://github.com/rsuite/rsuite-table/issues/410)) ([d774c74](https://github.com/rsuite/rsuite-table/commit/d774c74d7b40d29693f0086a3fe592ada51a4b4c))

build(deps): bump rsuite-table from 5.9.0 to 5.10.1

---

src/FormControl/FormControl.tsx
src/FormControl/test/FormControlSpec.tsx

Overriding `checked` prop of Toggle as a Form.Control accepter was broken since #3048
```jsx
<Form.Control
name="…"
accepter={Toggle}
checked={myValue} // not working
/>
```
See https://github.com/rsuite/rsuite/pull/3048#issuecomment-1469181356

fix(Form.Control): fix not able to override checked prop

---

package-lock.json
package.json

* **build:** fix unpublished source code ([#67](https://github.com/rsuite/schema-typed/issues/67)) ([c21ae0a](https://github.com/rsuite/schema-typed/commit/c21ae0a94578907e3fdd0467e5d1a1e3ec7c4d85))
- chore: change the compilation target of TypeScript from esnext to es2019

build(deps): bump schema-typed from 2.1.0 to 2.1.2

---

src/Affix/Affix.tsx
src/Affix/test/AffixSpec.tsx

Since the ad slot is dynamically inserted, the position of the button changes. The top value of the button is not recalculated after the position change, resulting in the following bug.
https://user-images.githubusercontent.com/1203827/225947257-17aaf228-fede-43ce-8594-ef4db5e01269.mp4

fix(Affix): fix misalignment due to DOM content updates

---

src/Overlay/Modal.tsx
src/Overlay/OverlayTrigger.tsx
src/Overlay/test/OverlayTriggerSpec.tsx
src/utils/usePortal.tsx

- Picker: use `useMemo` to update container before Portal recreate
#3125

fix(Picker): fix async container update cause offset error

---

docs/pages/components/date-range-picker/en-US/index.md

Hi there! I've just fixed the syntax error, please check it out

fix(docs): fix syntax error in date range picker docs

---

scripts/gulpfile.js
test/validateBuilds.js

Add CSS copy with `@enable-css-reset` disabled.
Added bundle files:
- dist/rsuite-no-reset.css
- dist/rsuite-no-reset.min.css
- dist/rsuite-no-reset-rtl.css
- dist/rsuite-no-reset-rtl.min.css
Resolve https://github.com/rsuite/rsuite/issues/1953#issuecomment-1467134045

build: build css with @enable-css-reset=false

---

src/toaster/styles/index.less

fix(toaster): fix style when message at the left

---

src/Calendar/Calendar.tsx
src/Calendar/CalendarHeader.tsx
src/Calendar/test/CalendarContainerSpec.tsx
src/Calendar/test/CalendarSpec.tsx

When clicking on the previous month or next month or directly selecting the month, the onMonthChange event will be triggered and the Date object of the current month will be returned.
```tsx
<Calendar
onMonthChange={(date: Date) => {
console.log(Date);
}}
/>;
```

feat(Calendar): add support for `onMonthChange` on `<Calendar>`

---

docs/next.config.js

Resolve 404 issue on `/design/:theme` paths
https://rsuite-nextjs-git-build-docs-nextjs-redirects-rsuite.vercel.app/design/default
https://rsuite-nextjs-git-build-docs-nextjs-redirects-rsuite.vercel.app/design/dark

build(website): replace nextjs rewrites with redirects

---

docs/pages/components/date-picker/en-US/index.md
docs/pages/components/date-picker/zh-CN/index.md
docs/pages/components/date-range-picker/en-US/index.md
docs/pages/components/date-range-picker/zh-CN/index.md
src/Calendar/CalendarContainer.tsx
src/Calendar/MonthDropdown.tsx
src/Calendar/test/CalendarMonthDropdownSpec.tsx
src/DatePicker/DatePicker.tsx
src/DateRangePicker/Calendar.tsx
src/DateRangePicker/DateRangePicker.tsx

Added `limitStartYear` prop to `DatePicker` and `DateRangePicker`. Usage:
Display current year only:
```
<DateRangePicker
limitEndYear={1}
limitStartYear={1}
...
>
```
Display years between previous and next year:
```
<DateRangePicker
limitEndYear={2}
limitStartYear={2}
...
>
```
This looks like: 
If unset, the start year still defaults to 1900
close #3145

Daterangepicker limit start year

---

webpack.config.js

Fix #3143
`lodash-webpack-plugin` requires proper configuration if currying features are used (used in `utils/prefix.ts`.
Ref: https://github.com/lodash/lodash-webpack-plugin#feature-sets

fix(build): fix broken lodash currying in CDN bundles

---

package-lock.json
package.json

* fix(ColumnGroup): fix `renderSortIcon` is not working in grouped columns by @simonguo in https://github.com/rsuite/rsuite-table/pull/426
> https://github.com/rsuite/rsuite-table/releases/tag/5.10.4

build(deps): bump rsuite-table from 5.10.3 to 5.10.4

---

src/Carousel/Carousel.tsx
src/Carousel/test/CarouselSpec.tsx

fix: https://github.com/rsuite/rsuite/issues/3175

fix(Carousel): fix index not being reset when children change

---

package-lock.json
package.json

Resolve peer dependency conflict with prettier 2.8.8

build(deps-dev): update prettier-plugin-sort-markdown-table

---

src/SelectPicker/test/SelectPickerSpec.tsx
src/Windowing/List.tsx
src/Windowing/test/ListSpec.tsx

SelectPicker with `virtualized={true}` throws when opening the menu, if `listProps.itemSize` is a number
https://codesandbox.io/s/rsuite-selectpicker-listprops-itemsize-cqk09c?file=/index.js

fix(SelectPicker): prevent error when listProps.itemSize is a number

---

src/DatePicker/styles/index.less

DatePicker and DateRangePicker were missing Stack styles. Therefore, the pickers were broken when using modularized import.
```
import "rsuite/DateRangePicker/styles/index.less";
```
Before:
After:

fix(DatePicker): added stack styles to datepicker styles

---

package-lock.json
package.json

`npm run tdd` is failing on Node.js 18
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in node_modules/chai/package.json
It's caused by [an issue in `chai`](https://github.com/chaijs/chai/pull/1427) which is [fixed in 4.3.5](https://github.com/chaijs/chai/commit/022c2faefc9a86b478392594c9015c3b942892e2).

build(deps-dev): update chai >= 4.3.5

---

src/List/test/ListSpec.tsx
src/Timeline/Timeline.tsx
src/Timeline/TimelineItem.tsx
src/Timeline/styles/index.less
src/Timeline/test/TimelineItemSpec.tsx
src/Timeline/test/TimelineSpec.tsx

Specify which Timeline.Item should be marked active (with the blue dot).
Example
```jsx
<Timeline isItemActive={index => index === 1}>
<Timeline.Item>First item</Timeline.Item>
<Timeline.Item>Second item</Timeline.Item>
<Timeline.Item>Third item</Timeline.Item>
</Timeline>
```
The `isItemActive` function takes two arguments and returns a boolean value
```typescript
type TimelineProps = {
/**
* @param index           The index of the item
* @param totalItemsCount The total count of all items
* 
* @returns Whether this item should be marked as active
*/
isItemActive?: (index: number, totalItemsCount: number) => boolean;
}
```
Two preset values are provided for convenience.
- `Timeline.ACTIVE_FIRST` Mark the first item as active
- `Timeline.ACTIVE_LAST` Mark the last item as active (the …

feat(Timeline): add isItemActive prop

---

src/InputPicker/InputPicker.tsx

Expected
Actual (before fix)
Fixed

fix(InputPicker): add missing top padding of listbox

---

src/Checkbox/styles/mixin.less
src/CheckboxGroup/styles/index.less
src/CheckboxGroup/test/CheckboxGroupStylesSpec.tsx
src/RadioGroup/styles/index.less

fix(Radio,Checkbox): remove leading space for Radio/Checkbox in groups

---

package-lock.json
package.json

* **Table:** fix rowHeight is invalid when virtualized ([#437](https://github.com/rsuite/rsuite-table/issues/437)) ([fdacff0](https://github.com/rsuite/rsuite-table/commit/fdacff0a6e3088e92e0ac15ce7a9f46132338097))
> fix: https://github.com/rsuite/rsuite/issues/3226

build(deps): bump rsuite-table from 5.10.5 to 5.10.6

---

src/Tag/test/TagSpec.tsx
src/Tag/test/TagStylesSpec.tsx
src/TagGroup/test/TagGroupSpec.tsx
src/TagGroup/test/TagGroupStylesSpec.tsx

drop use of getDOMNode util
This update involves changes to two components: Tag and TagGroup.

test(Tag/TagGroup): drop use of getDOMNode util

---

.github/workflows/nodejs-ci.yml
package.json

React Testing Library's dependency `aria-query` released an update with breaking change, leading to the broken tests in our CI checks https://github.com/rsuite/rsuite/pull/3246#pullrequestreview-1480904847.
`@testing-library/dom` has published [a fixed release](https://github.com/testing-library/dom-testing-library/releases/tag/v9.3.1) with `aria-query` pinned to a working version 5.1.3, but `@testing-library/react` hasn't released a fix so far. To address this issue in our CI checks, explicitly pin `aria-query` to 5.1.3 with [`overrides` property in `package.json`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json?v=true#overrides). This feature is supported since npm 8 so also update the Node.js version in CI workflow.
Related issues
- …

build: pin aria-query 5.1.3

---

src/Cascader/Cascader.tsx
src/Cascader/test/CascaderSpec.tsx

close #3242
add `onSelect` call in `handleMenuPressEnter`

Fix Cascader: onSelect not trigger when press Enter

---

src/Container/test/ContainerSpec.tsx

What I did: removing the `getDOMNode` and using the `render` in `@testing-library/react`
This update involves 1 component change: `Container`

Test: (Container)removing the getDOMNode and using the render

---

src/Col/test/ColSpec.tsx

What I did: removing the `getDOMNode` and using the `render` in `@testing-library/react`
This update involves 1 component change: `Col`

Test: (Col)removing the getDOMNode and using the render

---

src/Content/test/ContentSpec.tsx
src/CustomProvider/test/CustomProviderSpec.tsx
src/CustomProvider/test/FormattedDateSpec.tsx

What I did: removing the `getDOMNode` and using the `render` in `@testing-library/react`
This update involves 2 component changes: `Container` and `Content`

Test: (CustomProvider & Content)removing the getDOMNode and using the render

---

src/DatePicker/test/DatePickerSpec.tsx
src/DatePicker/test/ToolbarSpec.tsx

What I did: removing the `getDOMNode` and using the `render` in `@testing-library/react`
This update involves 1 component change: `DatePicker`

Test: (DatePicker)removing the getDOMNode and using the render

---

src/SafeAnchor/test/SafeAnchorSpec.tsx

What I did: removing the getDOMNode and using the render() from @testing-library/react
This update involves 1 component change: `SafeAnchor`

test(SafeAnchor): removing the getDOMNode and using the render()

---

docs/pages/components/radio/fragments/radio-group-inline-picker.md
src/RadioGroup/styles/index.less

- Horizontal spacing between radios was 30px, which should have been 20px - this issue was introduced in [v5.34.1](https://github.com/rsuite/rsuite/releases/tag/v5.34.1) by [#3215](https://github.com/rsuite/rsuite/pull/3215)
- Total height of the RadioGroup was 38px, which should have been 36px - this also led to vertical mis-alignment of the radio text
- Leading/trailing padding of the RadioGroup was 10px, which should have been 12px
https://rsuite-nextjs-git-fix-radiogroup-picker-style-rsuite.vercel.app/components/radio/#radio-group-picker
Before
After
Design

fix(RadioGroup): fix style in picker appearance

---

src/Picker/PickerToggle.tsx
src/Picker/test/PickerToggleSpec.tsx
src/Picker/utils.ts
src/SelectPicker/test/SelectPickerSpec.tsx

Close #3137 
`name` prop passed to SelectPicker component used to be missing from the underlying `<input>` element.

fix(Picker): pass name prop to underlying input element

---

src/Uploader/Uploader.tsx
src/Uploader/test/Uploader.test.tsx
src/utils/ajaxUpload.ts

`status` was typed `any` which prevents user from reading its properties with correct type declaration

fix(Uploader): correct type for status argument of onError callback

---

docs/pages/components/input-picker/en-US/index.md
docs/pages/components/input-picker/zh-CN/index.md
src/InputPicker/InputPicker.tsx
src/InputPicker/test/InputPickerSpec.tsx

Specify when to display/hide "Create option" action with given search keyword in a creatable InputPicker.
Example: A creatable InputPicker, but only display "Create option" action when no item's `name` matches searchKeyword
```jsx
<InputPicker
data={data}
creatable
shouldDisplayCreateOption={(searchKeyword, filteredData) =>
filteredData.every(item => item.name !== searchKeyword)
)}
/>
```
The `shouldDisplayCreateOption` function takes two arguments and returns a boolean value
```typescript
type InputPickerProps = {
/**
* @param searchKeyword  Value of the textbox
* @param filteredData   The items filtered by the searchKeyword
*
* @returns Whether to display "Create option" action
*/
shouldDisplayCreateOption?: (
searchKeyword: string,
filteredData: InputItemDataType[]
) => boolean;
}
``` …

feat(InputPicker): add shouldDisplayCreateOption prop

---

src/SelectPicker/styles/index.less

fix(SelectPicker): wrong padding for grouped options

---

src/CheckPicker/styles/index.less
src/Picker/styles/index.less

fix(CheckPicker): wrong padding of grouped options

---

src/Overlay/OverlayTrigger.tsx

```
node_modules/rsuite/esm/Overlay/OverlayTrigger.d.ts:6:18 - error TS2430: Interface 'OverlayTriggerProps' incorrectly extends interface 'StandardProps'.
Types of property 'children' are incompatible.
Type 'ReactElement<any, string | JSXElementConstructor<any>> | ((props: any, ref: any) => ReactElement<any, string | JSXElementConstructor<any>>)' is not assignable to type 'ReactNode'.
Type '(props: any, ref: any) => ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
6 export interface OverlayTriggerProps extends StandardProps, AnimationEventProps {
~~~~~~~~~~~~~~~~~~~
```

Fix type extension

---

src/CheckPicker/CheckPicker.tsx
src/InputPicker/InputPicker.tsx
src/Picker/test/useSearchSpec.ts
src/Picker/utils.ts
src/SelectPicker/SelectPicker.tsx

- Update `useSearch` to not only work with object arrays
- Remove `updateFilteredData` call from outside of `useSearch` and remove `updateFilteredData` method from return value
- Remove `setSearchKeyword` method from return value and replaced with `resetSearch` method, as it's always called with `''`.
- Add tests for `useSearch`

refactor(useSearch): improve state flow

---

src/RadioGroup/styles/index.less

Fix issue mentioned in https://github.com/rsuite/rsuite/pull/3274#discussion_r1271910072
Before ([CodeSandbox](https://codesandbox.io/s/goofy-black-yrctjd?file=/src/index.js))
After ([CodeSandbox](https://codesandbox.io/s/rsuite-tp-ci-forked-spdnhw))

fix(RadioGroup): unexpected wrapped text in picker appearance

---

src/Tree/test/TreeSpec.tsx
src/TreePicker/test/TreeNodeSpec.tsx
src/TreePicker/test/TreePickerSpec.tsx
src/Uploader/test/UploadFileItemSpec.tsx
src/Uploader/test/UploadTriggerSpec.tsx
src/Uploader/test/UploaderSpec.tsx
src/Whisper/test/WhisperSpec.tsx

This update involves 4 component changes: Tree, Treepicker, Uploader, Whisper

Test: (Tree, Treepicker, Uploader, Whisper): Removing the getDOMNode and using render

---

src/CheckPicker/test/CheckPickerSpec.tsx
src/InputPicker/test/InputPickerSpec.tsx
src/Picker/utils.ts
src/SelectPicker/test/SelectPickerSpec.tsx

Fix #3318
SelectPicker displays options according to `filteredData` returned from `useSearch`. It used to manually update `filteredData` via `updateFilteredData` method when `data` prop updates, which was not a proper state flow and was removed in #3301. However `filteredData` is not directly derived from `data` prop either, but manually updated in `handleSearch` (and then-removed `updateFilteredData` which was supposed to be called by SelectPicker). This edit makes `filteredData` directly derived from `data` and `searchKeyword`.

fix(SelectPicker): fix display options not updating when data prop is updated

---

src/InputPicker/InputPicker.tsx

Fix: #3245
InputPicker with virtualization item selects only after double clicks.
Calling set Open(false) in onBlur is incorrect because InputPicker onBlur is also called when clicking on InputPicker items. Closing InputPicker works without this function, when clicking outside the component.
For reproduce:
```
import React from "react";
import ReactDOM from "react-dom";
import { InputPicker, Loader } from 'rsuite';
import "rsuite/dist/rsuite.min.css";
import "./styles.css";
const fetchData = (start, length) => {
return Array.from({ length }).map((_, index) => {
return {
label: `Item ${start + index}`,
value: `Item ${start + index}`
};
});
};
const FixedLoader = () => (
<Loader
content="Loading..."
style={{
display: 'flex',
justifyContent: 'center',
position: 'absolute',
bottom: '0', …
```

Fix InputPicker select bug

---

src/Overlay/OverlayTrigger.tsx

https://github.com/rsuite/rsuite/assets/53305259/850ce8a5-7884-4a9a-bb60-fe11fe48302a
Sometimes Chrome will trigger `mouseover`  => `mouseout`  =>  `mouseover`, Because there's a hidden bug in `OverlayTrigger `,  and then it will cause strange problems similar to the one mentioned above.

fix(OverlayTrigger): fix handleClose will trigger twice

---

src/Calendar/styles/index.less
src/Calendar/test/CalendarStyleSpec.tsx
src/DatePicker/styles/index.less
src/DateRangePicker/test/DateRangePickerStylesSpec.tsx

The month buttons should have 2px horizontal gap but overlapped.
Before
After
It was dotted but should be dashed per design.
Before
After
The week number column should be 30px wide but shrank.
Before
After
The overlapping of month selection buttons was related to design issues. The width of the calendar panel was 246px, which could not contain the month selection buttons with appropriate gap. It's increased to 264px now. As a result, the horizontal gap between date buttons on the calendar panel (without week numbers) is increased from 2px to 4px, and horizontal padding of the calendar panel (without week numbers) is increased from 12px to 15px.
Design before vs. after
The week number column shrank because it's not given a correct width value (assigned `width: 1%`). As the calendar is …

fix(DatePicker,DateRangePicker): fix calendar styles per design

---

docs/pages/components/input/fragments/input-group-inside.md
src/InputGroup/styles/index.less

This edit fix 2 spacing issues with `<InputGroup inside>` addons
- The addon overlaps with input text when its content is long
- Gap between the addon content and input text was 13px, which should be 12px per design
Before
After
```jsx
<InputGroup inside>
<InputGroup.Addon>https://</InputGroup.Addon>
<Input defaultValue="www." />
</InputGroup>
```
As a side effect, this edit also fixes the doubled focus ring when InputGroup has focus
Before
After
The InputGroup with inside addons used to be implemented by setting `position: absolute` on the addon, making the Input the same size of the InputGroup, then increase the horizontal padding of Input to make room for the addon.
This caused the overlapping because when addon content increases the padding of Input doesn't change.
It's fixed by …

fix(InputGroup): fix inside addon overlapping input text

---

src/Picker/styles/mixin.less

The caret color should be `@B600` per design, but was implemented as `@B800`.
Design
Before fix
After fix

fix(Picker): change color of caret on option group title

---

src/Dropdown/styles/mixin.less

InputPicker has `cursor: text` style specified for its toggle, but was overridden by `.rs-picker-default .rs-picker-toggle` styles, which turns out to be redundant.
After fix
The `cursor: pointer` in `.rs-picker-default .rs-picker-toggle` selector is introduced via a `.dropdown-toggle()` mixin, which is used on the Dropdown's toggle and Picker's toggles - where they already have `cursor: pointer` inherited from `.rs-btn`. So it's safe to remove `cursor: pointer` from `.dropdown-toggle()`.
---
Fix #3328

fix(InputPicker): cursor should be text

---

src/Calendar/Calendar.tsx
src/Calendar/TableRow.tsx
src/Calendar/test/CalendarSpec.tsx
src/utils/test/useElementResizeSpec.ts

`onMonthChange` didn't fire when the display month changes due to:
- Clicking dates in a different month
- Clicking "Today" button when display month is not current month
Call `onMonthChange` callback whenever the selected date changes, if it's in a different month from current selected date.
---
Fix #3272

fix(Calendar): fix onMonthChange not fired when clicking on dates

---

src/Nav/styles/index.less

Icon in Nav.Item was not vertically centered.
Before
After
Apply `display: flex/inline-flex` with `align-items: center` on Nav.Item.

fix(Nav.Item): fix vertical mis-alignment of icon

---

.github/workflows/nodejs-ci.yml

The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/cache@v1, codecov/codecov-action@v2. For more info: 
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

ci: upgrade deprecated actions

---

docs/pages/components/calendar/en-US/index.md
docs/pages/components/calendar/fragments/custom-cell.md
docs/pages/components/calendar/zh-CN/index.md

Preview at https://rsuite-nextjs-git-docs-calendar-cellclassname-rsuite.vercel.app/components/calendar/#custom-cell-styles

docs(Calendar): add example for cellClassName usage

---

src/Picker/styles/mixin.less
src/SelectPicker/Listbox.tsx
src/SelectPicker/ListboxOption.tsx
src/SelectPicker/ListboxOptionGroup.tsx
src/SelectPicker/SelectPicker.tsx
src/SelectPicker/styles/index.less
src/Windowing/List.tsx
src/styles/mixins/listbox.less
src/utils/getDataGroupBy.ts

Before: grouped option elements are siblings of group element
a11y inspector:
After: grouped option elements are within group element
a11y inspector:

refactor(SelectPicker): move grouped options into group element

---

src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.tsx
src/CheckTreePicker/utils.ts
src/utils/treeUtils.ts

The searchKeyword prop of the CheckTree component is not updating as expected. 
close #3196 
The problem is rooted in the logic responsible for updating the searchKeyword within the CheckTree component.
In this pull request, I address the issue by reviewing and adjusting the code related to the searchKeyword functionality in the CheckTree component. This ensures that the searchKeyword state is updated appropriately and reflects user input accurately.
I reviewed the relevant code sections responsible for handling the searchKeyword and made the necessary modifications to enable its proper updating. This included checking for event listeners, data binding, and any conditional statements that might be affecting the searchKeyword state.
I thoroughly tested the changes by simulating various …

fix(CheckTree): searchKeyword is not updated as expected

---

package-lock.json
package.json

* **Next.js:** add 'use client' to all components ([#456](https://github.com/rsuite/rsuite-table/issues/456)) ([ed49fe1](https://github.com/rsuite/rsuite-table/commit/ed49fe1a76a23878bcad62f4f521ffc95cf4b8e9))
* **HeaderCell:** fix type extension ([#448](https://github.com/rsuite/rsuite-table/issues/448)) ([a8c9246](https://github.com/rsuite/rsuite-table/commit/a8c9246c362ef43545ecc021f273de58d05faedf))
* **Column:** fix column width reset after children update ([#447](https://github.com/rsuite/rsuite-table/pull/447))

build(deps): bump rsuite-table from 5.11.0 to 5.12.0

---

docs/pages/guide/v5-features/en-US/index.md
docs/pages/guide/v5-features/zh-CN/index.md

I noticed a small typo in the documentation at v5-features documentation(https://github.com/rsuite/rsuite/blob/main/docs/pages/guide/v5-features/). This pull request fixes the typo by replacing 'rsutie' with 'rsuite'. This change improves the readability and correctness of the documentation.

fix: Typo in docs

---

docs/pages/components/button/en-US/index.md

This pull request fixed docs of  button markdown syntax errors.
https://rsuitejs.com/components/button/#appearance
https://rsuite-nextjs-git-docs-fix-markdown-syntax-errors-rsuite.vercel.app/components/button/#appearance

docs(button): fix markdown syntax errors

---

src/Navbar/styles/index.less

> https://rsuitejs.com//design/default/index.html#s30

fix(Navbar): fix background color of the subtle navigation items incorrect

---

package-lock.json
package.json

* **Table:** add an option to define rowExpandedHeight as function [#465](https://github.com/rsuite/rsuite-table/pull/465)
* **Table:** fix table scroll width not excluding scroll bar width ([#461](https://github.com/rsuite/rsuite-table/issues/461)) ([88b0575](https://github.com/rsuite/rsuite-table/commit/88b0575954460539e7d5f29ee06d9251f89e8d23))
* **TreeTable:** fix incorrect scrolling position of tree nodes after collapse ([#462](https://github.com/rsuite/rsuite-table/issues/462)) ([0e0c8dc](https://github.com/rsuite/rsuite-table/commit/0e0c8dc6357846997533f82aeea6da64d315034a))
* **Table:** support table scrolling through keyboard arrow keys ([#463](https://github.com/rsuite/rsuite-table/issues/463)) ([bf451a8](https://github.com/rsuite/rsuite-table/commit/bf451a8c65ab24a3812fd16e1f176 …

build(deps): bump rsuite-table from 5.12.0 to 5.14.0

---

package-lock.json
package.json
scripts/gulpfile.js
test/validateBuilds.js

This PR adds the "use-client" directive to esm and cjs exported from rsuite, and a test case to check it.

feat: add a script to prepend the use client directive

---

package-lock.json
package.json

* **Table:** fix table cell text cannot be copied ([8a9f06b](https://github.com/rsuite/rsuite-table/commit/8a9f06bf34c83ba6c48c5da2c0988c83faea2d5c))
* add a script to prepend the use client directive ([#466](https://github.com/rsuite/rsuite-table/issues/466)) ([24369c5](https://github.com/rsuite/rsuite-table/commit/24369c583786fea1757131b417ce25aa3bc3a4f8))

build(deps): bump rsuite-table from 5.14.0 to 5.15.0

---

docs/pages/components/tag-input/en-US/index.md
docs/pages/components/tag-input/zh-CN/index.md
docs/pages/components/tag-picker/en-US/index.md
docs/pages/components/tag-picker/zh-CN/index.md
src/InputPicker/InputPicker.tsx
src/TagInput/index.tsx
src/TagInput/test/TagInputSpec.tsx
src/TagPicker/index.tsx
src/TagPicker/test/TagPickerSpec.tsx

```ts
/** Callback fired when a tag is removed. */
onTagRemove?: (tag: string, event: React.MouseEvent) => void;
```
> https://github.com/rsuite/rsuite/issues/3410

feat(TagPicker,TagInput): add support for onTagRemove

---

src/Form/Form.tsx
src/Form/FormContext.tsx
src/FormControl/FormControl.tsx
src/FormControl/test/FormControlSpec.tsx

fix: https://github.com/rsuite/rsuite/issues/3390
The reason is the external `formValue` was directly passed in context as the `formvalue`.
This will create a strong dependency on external `formValue`. if there's no external `formValue`. `Form.Control` component will always receive an empty `formValue`.
The solution is to pass `realFormValue` in the `Form` component as the `formValue`. 
However. there are some other further problems that are caused by this change: 
1. if neither `formDefautltValue` nor `formValue` props are passed in the `Form` component. React will throw an "uncontrolled to be controlled" error.  Although I think it's the right behaviour. But it's still a breaking change because both `formValue` and `formDefaultValue` weren't necessary before.
2. The second problem is …

fix(form): form doesn't pass correct formValue to context

---

src/styles/variables.less

The current font-size of the Drawer title is 16px, not expected as [Drawer Design](https://rsuitejs.com/design/default/index.html#s20).
In this pull request, I propose a fix to address this issue. Specifically, I've adjusted the style settings for the Drawer title to set the font-size to 18px, aligning it with the desired styling.
I conducted testing to verify that the font-size of the Drawer title is indeed set to 18px as intended.

fix(Drawer): change Drawer title font-size to 18px

---

src/Placeholder/styles/index.less
src/styles/color-modes/dark.less
src/styles/color-modes/high-contrast.less
src/styles/color-modes/light.less

The main purpose is to make the color used by each component depend on the CSS custom properties in the color palette, rather than directly hard-coding the color value. This allows us to easily change the theme through CSS custom properties in the application without modifying the color value in the component.

feat(CSS): use CSS custom properties instead of less variables

---

src/FormControl/FormControl.tsx
src/FormControl/test/FormControlSpec.tsx

fix #3453 
Components do not clear the value because when the `form`'s value becomes null, `formControl` passes undefined to the components. The `useControlled` hook will cache the old value and display it upon the second click of clear. Therefore, it is necessary to distinguish between null and undefined."

fix: formControll will pass undefined as value when value is null defaultValue is undefined

---

src/Cascader/Cascader.tsx
src/Cascader/test/CascaderSpec.tsx
src/MultiCascader/test/MultiCascaderSpec.tsx

When no option is found in Cascader, clicking the Enter key will select an incorrect value.
https://github.com/rsuite/rsuite/assets/1203827/865207dd-e43b-4749-a825-c1d7582a6d6d
> After fixed:  https://rsuite-nextjs-git-fix-cascader-selected-rsuite.vercel.app/components/cascader/

fix(Cascader): fix bug in value selection via Enter key

---

src/Cascader/Cascader.tsx
src/CheckPicker/test/CheckPickerSpec.tsx
src/InputPicker/InputPicker.tsx
src/InputPicker/test/InputPickerSpec.tsx
src/Picker/utils.ts
src/SelectPicker/test/SelectPickerSpec.tsx
src/TagPicker/test/TagPickerSpec.tsx

- Focus the selected element when selecting a value using the up and down keys on the keyboard.  fix: https://github.com/rsuite/rsuite/issues/3442
- Focus returns to trigger button after options list is closed.

fix: improve accessibility of picker related components

---

docs/pages/components/date-picker/fragments/basic.md
docs/pages/components/date-picker/fragments/disabled.md
src/Calendar/CalendarContainer.tsx
src/Calendar/MonthDropdown.tsx
src/Calendar/MonthDropdownItem.tsx
src/Calendar/TableCell.tsx
src/Calendar/TableHeaderRow.tsx
src/Calendar/TableRow.tsx
src/Calendar/test/CalendarMonthDropdownItemSpec.tsx
src/Calendar/test/CalendarMonthDropdownSpec.tsx
src/Calendar/test/CalendarTableCellSpec.tsx
src/Calendar/test/CalendarTableHeaderRowSpec.tsx
src/Calendar/test/CalendarTableRowSpec.tsx
src/Calendar/useCalendarDate.ts
src/Calendar/utils.ts
src/DatePicker/DatePicker.tsx
src/DatePicker/styles/index.less
src/DatePicker/test/DatePickerSpec.tsx
src/DateRangePicker/test/DateRangePickerSpec.tsx
src/Picker/PickerToggle.tsx

- Use the <kbd>↓</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>←</kbd> keys to switch focus on the calendar.

fix(DatePicker): improve DatePicker accessibility

---

src/Calendar/Table.tsx
src/Calendar/TableRow.tsx
src/Calendar/test/CalendarSpec.tsx
src/DatePicker/test/DatePickerSpec.tsx

fix: https://github.com/rsuite/rsuite/issues/3469

fix(Calendar): fix incorrect week numbers calculation

---

src/Nav/test/NavItemStylesSpec.tsx
src/Nav/test/NavStylesSpec.tsx

According to [discussions/3200](https://github.com/rsuite/rsuite/discussions/3200) removed legacy getDomeNode from tests of "Nav" conponent.
"Nav" has no "role" attribute, so used  data-testid="nav" for querying.
"Nav.Item" has role "button", but in this case better querying with "getByText".
"Nav.Dropdown" changed to "Nav.Menu"  ("Nav.Dropdown" is depricated);
"Nav. Dropdown.Item"  => "Nav.Item" ("Nav. Dropdown.Item" is depricated);

refactor(Nav): remove legacy getDOMNode from tests

---

src/Panel/test/PanelSpec.tsx
src/Panel/test/PanelStylesSpec.tsx

I had to add /* eslint-disable testing-library/no-node-access */ for a whole file because we have a few places where the linter doesn't like it when we query the DOM node this way: screen.getByText(text).parentNode. Unfortunately, as we don't have any 'role' or other appropriate data attribute, currently, I do not see other options. If you have any ideas, please share.

refactor(Panel): remove legacy getDOMNode from tests

---

src/Rate/test/RateSpec.tsx

I'm not sure that it is possible to avoid using "container" and node access for this tests. 
Had to add linter rules for the file, but it looks like that for other components the situation with querying will be the same - so  maybe it's not a bad idea to add this rules globally. 
/* eslint-disable testing-library/no-node-access, testing-library/no-container */
Screen without disabled linter rules:
also switched tests from "ReactTestUtils" to "userEvents" where it was possible.

refactor(Rate): remove legacy getDOMNode from tests

---

docs/pages/components/input/en-US/index.md
docs/pages/components/input/fragments/basic.md
docs/pages/components/input/zh-CN/index.md
src/Input/Input.tsx
src/Input/test/InputSpec.tsx

If you want to use the native DOM size attribute you can use the `htmlSize` prop. For it to work as expected you will also need to provide the `style={{ width: 'auto' }}` prop.
```jsx
<Input htmlSize={10} style={{ width: 'auto' }} />
```

feat(Input): add support for htmlSize prop

---

src/DateRangePicker/DateRangePicker.tsx

fix: https://github.com/rsuite/rsuite/issues/3522
fix: https://github.com/rsuite/rsuite/issues/3466

fix(DateRangePicker): fix layout misalignment due to missing min-width

---

docs/less/index.less
src/Cascader/styles/index.less
src/InputPicker/test/InputPickerStylesSpec.tsx
src/RangeSlider/test/RangeSliderSpec.tsx
src/Sidenav/styles/index.less
src/styles/normalize.less
webpack.karma.js

fix: https://github.com/rsuite/rsuite/issues/3513
fix: https://github.com/rsuite/rsuite/issues/1953
fix: https://github.com/rsuite/rsuite/issues/3367

fix(CSS Reset): fix `rsuite-no-reset.css` overrides the default styles of the app

---

docs/pages/guide/use-next-app/en-US/index.md
docs/pages/guide/use-next-app/zh-CN/index.md

This PR fixes `loyout` -> `layout`

fix: typo in Next.js guide

---

docs/package-lock.json
docs/package.json
docs/pages/components/form-validation/en-US/index.md
docs/pages/components/form-validation/fragments/form-nested-fields.md
docs/pages/components/form-validation/zh-CN/index.md
docs/pages/components/form/en-US/index.md
docs/pages/components/form/fragments/status.md
docs/pages/components/form/zh-CN/index.md
src/Form/Form.tsx
src/Form/FormContext.tsx
src/Form/styles/mixin.less
src/Form/test/FormSpec.tsx
src/FormControl/FormControl.tsx
src/FormControl/test/FormControlSpec.tsx
src/FormGroup/FormGroup.tsx

`nestedField` can make the form support nested data, default is false.
```tsx
const model = Schema.Model({
name: StringType().isRequired('This field is required.'),
address: ObjectType().shape({
city: StringType().isRequired('This field is required.'),
postCode: NumberType('Post Code must be a number').isRequired('This field is required.')
})
});
const formValue = {
name: 'Tom',
address: { city: 'ShangHai', postCode: '200000' }
};
<Form formValue={formValue} nestedField model={model} >
<FormControl name="name" />
<FormControl name="address.city" />
<FormControl name="address.postCode" />
</Form>
```

feat(Form): add support for `nestedField` prop on Form

---

docs/utils/component.config.json

docs: fix searching icon isn't working

---

src/Dropdown/DropdownItem.tsx
src/Dropdown/test/DropdownItemSpec.tsx
src/Nav/NavDropdownItem.tsx
src/Nav/NavItem.tsx
src/Nav/test/NavItemSpec.tsx
src/Nav/test/NavMenuSpec.tsx
src/Navbar/NavbarDropdownItem.tsx
src/Navbar/NavbarItem.tsx
src/Navbar/test/NavbarStylesSpec.tsx
src/Sidenav/ExpandedSidenavDropdownItem.tsx
src/Sidenav/SidenavDropdownItem.tsx
src/Sidenav/SidenavItem.tsx

In both NavItem and DropdownItem, the className attribute assigned to the icon prop will be overridden.
notice:  there's an extra test case change, but I think it was wrong before.

fix: NavItem and DropDownItem rendering icon without overriding className

---

src/utils/useUniqueId.ts

ref: https://github.com/webpack/webpack/issues/14814
summary: when using `'useId' + ''`, the bundler will optimize it to `'useId'`.  Then webpack will analyze if `useId` is in `React`.  As a result, it will throw a warning `useId isn't in React`. However `'useId'.toString` will not be optimized. Therefore it will prevent webpack throw this error

fix: use toString instead of an empty string

---

src/InputGroup/styles/index.less

fix(InputGroup): fix that the bg color of `InputGroup.Addon` is inconsistent with `Input`

---

src/CheckTreePicker/CheckTreeNode.tsx
src/CheckTreePicker/styles/index.less
src/CheckTreePicker/test/CheckTreePickerStylesSpec.tsx
src/Tree/test/TreeStylesSpec.tsx
src/TreePicker/styles/index.less
src/TreePicker/test/TreePickerStylesSpec.tsx
src/internals/Picker/ListCheckItem.tsx
src/internals/Picker/ListItem.tsx
src/internals/Picker/TreeView.tsx
src/internals/Picker/styles/index.less
src/styles/mixins/listbox.less

fix(tree): improve the hover and focus status of Tree nodes

---

docs/pages/components/message/en-US/index.md
docs/pages/components/message/fragments/bordered.md
docs/pages/components/message/fragments/centered.md
docs/pages/components/message/fragments/header.md
docs/pages/components/message/zh-CN/index.md
src/Message/Message.tsx
src/Message/stories/Message.stories.tsx
src/Message/styles/index.less
src/Message/styles/mixin.less
src/Message/test/MessageSpec.tsx
src/styles/color-modes/dark.less
src/styles/color-modes/light.less
src/utils/statusIcons.tsx

> https://rsuite-nextjs-git-feat-message-bordered-rsuite.vercel.app/components/message/#bordered

feat(Message): add support for `bordered` and `centered` props on Message

---

package-lock.json
package.json
src/Carousel/Carousel.tsx
src/DateRangePicker/DateRangePicker.tsx
src/Stack/Stack.tsx
src/Stack/test/StackSpec.tsx
src/Steps/Steps.tsx
src/Timeline/Timeline.tsx
src/utils/ReactChildren.tsx
src/utils/test/ReactChildrenSpec.tsx

#close #3606 
There are some other effects. 
There's no visible effect. But we need to replace `React.Children.count` with our own utility function  'ReactChildren.count'.

fix: supports Fragment children component

---

src/DatePicker/DatePicker.tsx

before
after
caused by https://github.com/rsuite/rsuite/pull/3607
The reason is that the `Stack` component supported `Fragment` child, it will be spread. So we need to replace `Fragment` with the `Stack.Item`

fix(DatePicker): fix style error of the bottom button in the datePicker

---

docs/pages/components/date-picker/en-US/index.md
docs/pages/components/date-picker/fragments/basic.md
docs/pages/components/date-picker/fragments/intl-zh-cn.md
docs/pages/components/date-picker/fragments/intl.md
docs/pages/components/date-picker/fragments/placeholder.md
docs/pages/components/date-picker/fragments/render-cell.md
docs/pages/components/date-picker/zh-CN/index.md
src/Calendar/CalendarContainer.tsx
src/Calendar/TableCell.tsx
src/Calendar/types.ts
src/DatePicker/DatePicker.tsx
src/DatePicker/test/DatePickerSpec.tsx

https://rsuite-nextjs-git-feat-date-pickerrendercell-rsuite.vercel.app/components/date-picker/#custom-calendar-cell
Resolved: https://github.com/rsuite/rsuite/issues/3536

feat(DatePicker): add support `renderCell` on `<DatePicker>`

---

src/Nav/styles/index.less

https://github.com/rsuite/rsuite/assets/53305259/e94b26aa-8a7a-4c13-8187-5f3acc7c42b7
https://github.com/rsuite/rsuite/assets/53305259/2966443c-16a1-4e3e-896e-c5731495b59c

fix(nav): default appearance doesn't show an active background when focused

---

src/styles/variables.less

In PR #3603, a z-index property was added to Message in full state, causing a breaking change.

fix(Message): fix the z-index issue of Message in full state

---

docs/pages/components/cascader/en-US/index.md

I noticed a small typo in the documentation at cascader documentation(https://rsuitejs.com/components/cascader/). This pull request fixes the typo by replacing 'Contorlled' with 'Controlled'. This change improves the readability and correctness of the documentation.

fix(cascader): typo in docs

---

docs/pages/components/checkbox/en-US/index.md
docs/pages/components/checkbox/fragments/basic.md
docs/pages/components/checkbox/fragments/checkbox-group-controlled.md
docs/pages/components/checkbox/fragments/checkbox-group.md
docs/pages/components/checkbox/fragments/checkbox-groupinline.md
docs/pages/components/checkbox/fragments/disabled.md
docs/pages/components/checkbox/fragments/indeterminate.md
docs/pages/components/checkbox/zh-CN/index.md
src/CheckPicker/styles/index.less
src/CheckTreePicker/styles/index.less
src/Checkbox/Checkbox.tsx
src/Checkbox/styles/index.less
src/Checkbox/test/CheckboxSpec.tsx
src/InputPicker/InputPicker.tsx
src/InputPicker/InputPickerContext.tsx
src/MultiCascader/TreeView.tsx
src/MultiCascader/test/MultiCascaderSpec.tsx
src/TagPicker/index.tsx
src/TagPicker/test/TagPickerSpec.tsx
src/internals/Picker/ListCheckItem.tsx
src/internals/Picker/styles/index.less
src/internals/Picker/test/ListCheckItemSpec.tsx

- Listen for click events on the correct element.
- Adjusted some unreasonable css definitions.
- Affected components include: CheckPicker, CheckTreePicker, TagPicker, MultiCascader.

fix(Checkbox): listen for click events on the correct element

---

src/TagGroup/styles/index.less

I'm not a css expert but in my project when the rollup task tries to minify the styles it displays this error.
```text
warnings when minifying css:
▲ [WARNING] Unexpected "{" [css-syntax-error]
.rs-tag-group>{margin-left:10px;margin-top:10px}
```
With the change the resultant css file (`lib/TagGroup/styles/index.css`) is:
```css
/* stylelint-disable */
*[class*='rs-'] {
-webkit-box-sizing: border-box;
box-sizing: border-box;
}
*[class*='rs-']::before,
*[class*='rs-']::after {
-webkit-box-sizing: border-box;
box-sizing: border-box;
}
.rs-tag-group {
margin: -10px 0 0 -10px;
}
.rs-tag-group > .rs-tag {
margin-top: 10px;
margin-left: 10px;
}
/*# sourceMappingURL=index.css.map */
```
While now is:
```css
/* stylelint-disable */
*[class*='rs-'] {
-webkit-box-sizing: border-box;
box-sizing: …
```

fix(TagGroup): fix css entry with nested children

---

docs/pages/components/checkbox/en-US/index.md
docs/pages/components/checkbox/fragments/colors.md
docs/pages/components/checkbox/zh-CN/index.md
src/Badge/test/BadgeSpec.tsx
src/Button/test/ButtonSpec.tsx
src/Checkbox/Checkbox.tsx
src/Checkbox/stories/Checkbox.stories.tsx
src/Checkbox/styles/index.less
src/Checkbox/test/CheckboxSpec.tsx
src/Rate/test/RateSpec.tsx
src/Tag/test/TagSpec.tsx
test/utils/testStandardProps.ts

https://rsuite-nextjs-git-feat-checkbox-rsuite.vercel.app/components/checkbox/#colors

feat(Checkbox): add support for `color` on `<Checkbox>`

---

src/Drawer/styles/index.less
src/Drawer/test/DrawerSpec.tsx
src/Drawer/test/DrawerStylesSpec.tsx
src/Modal/Modal.tsx
src/Modal/test/ModalSpec.tsx
src/internals/Overlay/Modal.tsx

fix:https://github.com/rsuite/rsuite/issues/3710

fix(Drawer): fix the focus cannot be moved to elements outside the Drawer when `backdrop=false`

---

docs/pages/components/multi-cascade-tree/en-US/index.md
docs/pages/components/multi-cascade-tree/zh-CN/index.md
docs/pages/components/multi-cascader/en-US/index.md
docs/pages/components/multi-cascader/zh-CN/index.md

1. fix wrong value types in MultiCascadeTree and MultiCascader
2. add missing `valueKey` option in Chinese

docs(MultiCascader, MultiCascadeTree): update incorrect props

---

package-lock.json
package.json
src/Form/Form.tsx
src/Form/test/FormSpec.tsx
src/Form/test/FormStylesSpec.tsx
src/FormControl/FormControl.tsx
src/FormControl/test/FormControlStylesSpec.tsx

* **ObjectType:** fix required message for properties not being replaced ([#79](https://github.com/rsuite/schema-typed/issues/79)) ([2aab276](https://github.com/rsuite/schema-typed/commit/2aab2768994b42d3572c2d90a926329912811c80))
* add support for `equalTo` and `proxy` ([#78](https://github.com/rsuite/schema-typed/issues/78)) ([d9f0e55](https://github.com/rsuite/schema-typed/commit/d9f0e555cf532731839584b0c036648001fe0503))
* add support for `label` method ([#77](https://github.com/rsuite/schema-typed/issues/77)) ([9ff16c3](https://github.com/rsuite/schema-typed/commit/9ff16c346d6f13caabd4910a7d920c1c11eced18))
* **Schema:** support nested object check with `checkForField` and `checkForFieldAsync` ([#76](https://github.com/rsuite/schema-typed/issues/76)) …

build: bump schema-typed from 2.1.3 to 2.2.1

---

package.json

React upgrade to 18.3.0 and later will not pass the test, so the version is temporarily locked to 18.2.0

ci(test): pin React version to 18.2.0

---

src/Toggle/styles/index.less

When the toggle is disabled it is still accepting pointer events.
https://github.com/rsuite/rsuite/assets/8769408/ca752fbe-b18c-465d-b3bc-d1b039c4c595
`cursor: not-allowed;`
`pointer-events: none;`

fix(toggle): block pointer events when disabled

---

src/Toggle/styles/index.less

The icon inside the toggle is not vertically centered.
If the PR gets accepted please use my GitHub email-id ([shrinidhiupadhyaya1195@gmail.com](mailto:shrinidhiupadhyaya1195@gmail.com)) instead of my other email-id for the Co-authored-by: message.

fix(toggle): center align inner text/icon

---

src/Slider/styles/index.less
src/Toggle/styles/index.less

When the slider is disabled it is still accepting pointer events.
`cursor: not-allowed;`
https://github.com/rsuite/rsuite/assets/8769408/59ebcaa2-3625-4e5a-a64f-e2c81f4eeb79
`pointer-events: none;`
https://github.com/rsuite/rsuite/assets/8769408/d7ee10d7-1e57-42d4-976f-325f655ba3ac

fix(slider): block pointer events when disabled

---

src/DatePicker/styles/index.less
src/DateRangePicker/styles/index.less

The cursor on hover of the icon is incorrect in `DatePicker` and  `DateRangePicker`
https://github.com/rsuite/rsuite/assets/8769408/a5d26617-1cf2-418d-a97f-bce4091733c8
https://github.com/rsuite/rsuite/assets/8769408/32ce69d9-5edf-42ee-86a3-990174e80445

fix(DatePicker, DateRangePicker): cursor pointer on icon hover

---

docs/pages/components/date-picker/en-US/index.md
docs/pages/components/date-picker/fragments/render-value.md
docs/pages/components/date-picker/index.tsx
docs/pages/components/date-picker/zh-CN/index.md
docs/pages/components/date-range-picker/en-US/index.md
docs/pages/components/date-range-picker/fragments/render-value.md
docs/pages/components/date-range-picker/index.tsx
docs/pages/components/date-range-picker/zh-CN/index.md
src/DatePicker/DatePicker.tsx
src/DatePicker/test/DatePickerSpec.tsx
src/DatePicker/types.ts
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.tsx

In #3515 #3525, in order to support entering dates via the keyboard, `renderValue` was deprecated. However, in actual business scenarios, `format` cannot completely replace `renderValue` to render values personalized, so `renderValue` will be re-enabled.
fix: https://github.com/rsuite/rsuite/issues/3794
fix: https://github.com/rsuite/rsuite/issues/3795

fix(DatePicker,DateRangePicker): fix the issue that `renderValue` does not work

---

src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/hooks/useDateDisabled.ts
src/DateRangePicker/types.ts

fix: https://github.com/rsuite/rsuite/issues/3764
The main reason for the performance problem is that the `isDateDisabled` method is called many times, and this method is called every time it is rendered. When a very large range of dates is entered in the input box, the `isDateDisabled` method is called many times, resulting in a performance problem. The improvement plan is to call the `isDateDisabled` method only when both of the following conditions are met:  
- The `shouldDisableDate` property is set.
- When the calendar panel popup is opened.
Also removed the logic of judging whether the Ok button is disabled through the `isDateDisabled` method. Because it is a redundant check, and the disabled date cannot be selected on the calendar panel.

perf(DateRangePicker): improve the performance when typing the date

---

docs/pages/components/form/fragments/status.md
src/AutoComplete/test/AutoCompleteStylesSpec.tsx
src/Button/styles/mixin.less
src/Checkbox/styles/index.less
src/DatePicker/DatePicker.tsx
src/DateRangePicker/DateRangePicker.tsx
src/InputGroup/styles/index.less
src/Nav/test/NavItemStylesSpec.tsx
src/Radio/styles/index.less
src/Rate/styles/index.less
src/SelectPicker/test/SelectPickerStylesSpec.tsx
src/Slider/styles/index.less
src/internals/Picker/PickerIndicator.tsx
src/internals/Picker/styles/index.less
src/styles/color-modes/dark.less
src/styles/color-modes/high-contrast.less
src/styles/color-modes/light.less

| Before | After |
|---| ---|
| ![image](https://github.com/rsuite/rsuite/assets/1203827/d63dc66f-4bf5-48b5-bdbf-b4e2ff7a3141) | ![image](https://github.com/rsuite/rsuite/assets/1203827/250619a8-bf68-49c1-bb3a-11cd1b16e52a) |
| Before | After |
|---| ---|
| ![image](https://github.com/rsuite/rsuite/assets/1203827/b36a10ad-0368-43be-8c14-cf83408c53ec) | ![image](https://github.com/rsuite/rsuite/assets/1203827/9bbc2b51-d1ef-46d2-aa64-589a1573f609) |
| Before | After |
|---| ---|
| ![image](https://github.com/rsuite/rsuite/assets/1203827/b6176d07-b7ec-4249-916f-d9fdc6994d81)| ![image](https://github.com/rsuite/rsuite/assets/1203827/00617b1c-7ecd-4e8b-97cf-3201ea6dd264)|

fix: fix the color contrast of form controls in disabled state

---

src/Steps/styles/index.less

The icon inside steps is not vertically centered.

fix(steps): center align inner icon/text

---

docs/pages/components/date-picker/fragments/render-value.md
docs/pages/components/date-range-picker/fragments/render-value.md
src/DateInput/test/testUtils.tsx
src/DatePicker/DatePicker.tsx
src/DatePicker/hooks/useCustomizedInput.ts
src/DatePicker/test/DatePickerSpec.tsx
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.tsx
test/utils/simulateEvent.ts

DatePicker
https://rsuite-nextjs-git-fix-date-range-picker-render-value-rsuite.vercel.app/components/date-picker/#custom-render-value
DateRangePicker
https://rsuite-nextjs-git-fix-date-range-picker-render-value-rsuite.vercel.app/components/date-range-picker/#custom-render-value

fix(DatePicker,DateRangePicker): fix `renderValue` and `editable` can't coexist

---

docs/pages/components/use-breakpoint-value/en-US/index.md
docs/pages/components/use-breakpoint-value/fragments/basic.md
docs/pages/components/use-breakpoint-value/fragments/stack.md
docs/pages/components/use-breakpoint-value/index.tsx
docs/pages/components/use-breakpoint-value/zh-CN/index.md
docs/pages/components/use-media-query/en-US/index.md
docs/pages/components/use-media-query/index.tsx
docs/pages/components/use-media-query/zh-CN/index.md
docs/utils/component.config.json
src/index.tsx
src/useBreakpointValue/index.ts
src/useBreakpointValue/test/useBreakpointValueSpec.ts
src/useBreakpointValue/useBreakpointValue.ts
src/useMediaQuery/index.ts
src/useMediaQuery/test/useMediaQuerySpec.ts
src/useMediaQuery/useMediaQuery.ts

```tsx
const fontSize = useBreakpointValue({ sm: "14px", lg: "24px" }, { defaultValue: "16px" });
const direction = useBreakpointValue({ sm: 'row' }, { defaultValue:'column' });
```
```ts
function useBreakpointValue<T>(
mediaQueries: Record<string | 'xxl' | 'xl' | 'lg' | 'md' | 'sm' | 'xs', T>,
options?: {
defaultValue?: T;
}
): T;
```

feat(useBreakpointValue): add a hook to get the value of the current breakpoint

---

src/Radio/styles/index.less

The cursor on the disabled Radio Control when hovered is incorrect.
https://github.com/rsuite/rsuite/assets/8769408/d100f01a-b790-4636-863c-ba3a06af020e
https://github.com/rsuite/rsuite/assets/8769408/033f16d4-5448-49c2-a737-a80441ef88d7

fix(radio): disabled radio control hover cursor

---

src/Uploader/styles/index.less

When `Uploader` component is disabled, the background color of the List component when hovered changes.
https://github.com/rsuite/rsuite/assets/8769408/7821a1bc-68de-4197-9c39-1fa77cd2bd49
https://github.com/rsuite/rsuite/assets/8769408/13b02ed0-2ec1-4ab9-bb0a-2dd18bf4400a

fix(uploader): background color on hover when disabled

---

docs/pages/components/toaster/en-US/index.md
docs/pages/components/toaster/zh-CN/index.md
src/Message/Message.tsx
src/Notification/Notification.tsx
src/internals/types/index.ts
src/toaster/ToastContainer.tsx
src/toaster/ToastContext.ts
src/toaster/hooks/useDelayedClosure.ts

close: https://github.com/rsuite/rsuite/issues/1531
```tsx
import { useToaster } from 'rsuite';
return () => {
const toaster = useToaster();
const handleClick = () => {
// Push the message to the toaster, the message will disappear after 2 seconds. 
// But the message will not disappear when the mouse hovers over the message.
toaster.push(<Message>message</Message>, { duration: 2000, mouseReset: true });
};
return <Button onClick={handleClick}>Push</Button>;
};
```

feat(useToaster): add support for `mouseReset` parameter in push method

---

src/Progress/styles/index.less

Horizontal Progress component has a `left-padding` of `12px`.
Vertical Progress component has `bottom-padding` of `8px`  but it needs to have a `bottom-padding` of `12px`, because it is vertically oriented.

fix(progress): consistent spacing between label/icon & progress line (Vertical)

---

docs/pages/components/drawer/fragments/basic.md
src/Drawer/Drawer.tsx
src/Drawer/test/DrawerSpec.tsx

fix(Drawer): remove the `max-height` that should not exist in Drawer.Body

---

src/internals/hooks/useCustom.ts
src/internals/hooks/useIsomorphicLayoutEffect.ts

This PR fixes isomorphism in Deno environments. `typeof window` turns out to be not sufficient in determining server/client in Deno, because `window` actually exists in Deno. The [workaround recommended by Remix](https://remix.run/docs/en/main/guides/gotchas#typeof-window-checks) is to replace `typeof window` with `typeof document`. 
Fixes #3864

fix(Deno): prevent ReferenceError in Deno environments

---

src/CheckTree/CheckTreeView.tsx
src/CheckTreePicker/CheckTreePicker.tsx
src/CheckTreePicker/test/CheckTreePickerSpec.tsx
src/Tree/TreeView.tsx
src/TreePicker/TreePicker.tsx
src/TreePicker/test/TreePickerSpec.tsx

fix: https://github.com/rsuite/rsuite/issues/3872

fix(TreePicker, CheckTreePicker): fix `locale` cannot override default localization configuration

---

docs/pages/components/loader/en-US/index.md
docs/pages/components/loader/fragments/speed.md
docs/pages/components/loader/zh-CN/index.md
src/Loader/Loader.tsx
src/Loader/styles/index.less
src/Loader/test/LoaderSpec.tsx
src/styles/variables.less

This PR introduces a new `loaderPlayState` prop for the Loader spinner component. The `loaderPlayState` prop accepts two values: `"running"` and `"paused"`, allowing users to control the play state of the loader animation.
1. **Pause and Resume:** In applications with complex loading sequences, it might be necessary to pause the loader animation while certain conditions are being met and resume it afterward.
2. **Accessibility:** Users might want to pause animations to reduce distractions or for accessibility reasons.
3. **User Experience:** Provide better user experience by controlling the visibility and behavior of the loader based on user interactions.
- Added a new `loaderPlayState` prop to the Loader component, which defaults to `"running"`.
- Updated the CSS/JS to handle the …

feat(Loader): add `paused` value to the `speed` property to control the animation pause

---

src/Nav/AdaptiveNavItem.tsx
src/Nav/Nav.tsx
src/Nav/build.json
src/Nav/test/AdaptiveNavItemSpec.tsx

This PR solves the problem that the NavItem component imported in the following way cannot be used in Navbar and Sidenav.
```js
import NavItem from 'rsuite/NavItem';
```

fix(NavItem): fix NavItem cannot be used in Navbar and Sidenav

---

docs/pages/components/button/fragments/block.md
docs/pages/components/button/index.tsx
src/Button/styles/index.less
src/Button/test/ButtonStylesSpec.tsx

```tsx
<Button block startIcon={<FaGithub />}>Github</Button>
```

fix(Button): fix the misalignment of icons and text in block buttons

---

docs/pages/components/form-validation/en-US/index.md
docs/pages/components/form-validation/fragments/form-check-proxy.md
docs/pages/components/form-validation/zh-CN/index.md
src/Form/Form.tsx
src/Form/FormContext.tsx
src/Form/hooks/useFormValidate.ts
src/FormControl/FormControl.tsx
src/FormControl/test/FormControlSpec.tsx

[Schema-typed](https://github.com/rsuite/schema-typed/releases) added the `proxy` feature to support interdependent validation. However, it doesn't work in `rsuite`.
This PR solved this problem. But there are still two points to notice.
1. Although `checkForField ` or `checkForFieldAsync` use `getCheckResult` of `model` to get all results, they still return the result of `model.checkForField` or `model.checkForFieldAsync` to maintain stability.
2. When using `nestedField` and `proxy` together, I can't detect if it has any error in the result of `getCheckResult`. Therefore I didn't support `proxy` when using `nestedField`

fix(Form): fix `proxy` function in `schema-typed` not work in form

---

src/Navbar/test/NavbarBodySpec.tsx
src/Navbar/test/NavbarHeaderSpec.tsx
src/Navbar/test/NavbarSpec.tsx
src/PanelGroup/test/PanelGroupSpec.tsx
src/PanelGroup/test/PanelGroupStylesSpec.tsx
src/Popover/test/PopoverSpec.tsx

This update involves 3 component changes: Navbar, PanelGroup, Popover

 Test: (Navbar, PanelGroup, Popover): Removing the getDOMNode and using render #3302 

---

docs/pages/components/input-number/en-US/index.md
docs/pages/components/input-number/fragments/decimal-separator.md
docs/pages/components/input-number/zh-CN/index.md
src/InputNumber/InputNumber.tsx
src/InputNumber/test/InputNumberSpec.tsx

To solve this requirement  https://github.com/rsuite/rsuite/issues/3899
In other languages and cultures, the decimal point may not be a ".". The main decimal point symbols used in countries and regions using Arabic numerals are "," and ".". Chinese-speaking areas and most English-speaking areas use ".", but most other European countries and their former colonies use ",".
Add a `decimalSeparator` property to officially designate different symbols as separators for different countries/regions.
```
<InputNumber decimalSeparator="," />
```

feat(InputNumber): add support for `decimalSeparator` prop

---

src/FormControl/test/FormControlSpec.tsx
src/IconButton/test/IconButtonSpec.tsx
src/IconButton/test/IconButtonStylesSpec.tsx
src/InputNumber/test/InputNumberSpec.tsx
src/InputNumber/test/InputNumberStylesSpec.tsx

This update involves 3 component changes: InputNumber, IconButton, FormControl
*I hope this time is ok

Test: (InputNumber, IconButton, FormControl): Removing the getDOMNode and using render

---

docs/pages/components/multi-cascade-tree/en-US/index.md
docs/pages/components/multi-cascade-tree/zh-CN/index.md
docs/pages/components/multi-cascader/en-US/index.md
docs/pages/components/multi-cascader/zh-CN/index.md
src/MultiCascadeTree/MultiCascadeTree.tsx
src/MultiCascadeTree/test/MultiCascadeTreeSpec.tsx
src/MultiCascader/MultiCascader.tsx
src/MultiCascader/test/MultiCascaderSpec.tsx

By default, when searching, if a keyword matches both the parent node and the child node at the same time, if the child node is selected, the parent node should be in a mixed state. Unless `cascade` is set to `false`, the selection status of the child node will not affect the selection status of the parent node.
close: https://github.com/rsuite/rsuite/pull/3922

fix(MultiCascadeTree,MultiCascader): fix parent node is not in a mixed state when searching

---

src/Modal/test/ModalBodySpec.tsx
src/Modal/test/ModalDialogSpec.tsx
src/Modal/test/ModalFooterSpec.tsx
src/Modal/test/ModalHeaderSpec.tsx
src/Modal/test/ModalSpec.tsx
src/Modal/test/ModalTitleSpec.tsx

What I did: refactored some tests to use testStandardProps
This PR involves just one component: Modal

test(Modal): refactor test cases using `testStandardProps`

---

src/Calendar/test/CalendarHeaderSpec.tsx
src/Calendar/test/CalendarTimeDropdownSpec.tsx

- Refactor using fireEvent instead of Simulate
- Use screen.getByText instead of querySelector

test(Calendar): refactor using fireEvent instead of Simulate

---

src/Button/Button.tsx
src/Button/test/ButtonSpec.tsx

- Refactor using fireEvent instead of Simulate
- Use screen.getByRole('button') instead of container.firstChild
- Use useMemo instead of useCallback

test(Button): refactor using fireEvent instead of Simulate

---

docs/pages/guide/i18n/fragments/example.md
docs/pages/guide/i18n/index.tsx
src/Calendar/TableRow.tsx
src/Calendar/test/CalendarContainerSpec.tsx
src/CustomProvider/CustomProvider.tsx
src/DatePicker/test/DatePickerSpec.tsx
src/internals/types/index.ts
src/locales/index.ts

In date-fns, the value of `firstWeekContainsDate` defines which day of the year must be included in the first week. For example:
- If set to 1, the first week must include January 1st.
- If set to 4, the first week must include January 4th.
https://en.wikipedia.org/wiki/Week#The_ISO_week_date_system
This setting is mainly used to determine the first week of the year based on different cultural or business needs. Some countries or regions have different regulations; for instance, the ISO 8601 standard specifies that the first week of the year is the one that contains January 4th.
This PR will use the default value of firstWeekContainsDate from the locale in date-fns to determine the start of the first week for the current locale.

fix(Calendar): fix the problem of displaying the first week of the year incorrectly

---

src/Breadcrumb/Breadcrumb.tsx
src/Breadcrumb/BreadcrumbItem.tsx
src/Breadcrumb/styles/index.less
src/Breadcrumb/test/BreadcrumbItemSpec.tsx
src/Breadcrumb/test/BreadcrumbItemStylesSpec.tsx

https://rsuite-nextjs-git-refactor-breadcrumb-rsuite.vercel.app/components/breadcrumb/
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

refactor(Breadcrumb): use a more reasonable DOM structure to improve accessibility

---

src/Form/hooks/useFormValidate.ts
src/Form/test/FormSpec.tsx
src/FormControl/test/FormControlSpec.tsx

`checkFieldForNextValue`,`checkFieldAsyncForNextValue`, and`checkFieldAsyncForNextValue` were directly using uncontrolled `formError`. When formError is uncontrolled, it references an empty formError prop, which causes errors in other fields to be cleared each time.

fix(Form): clear error caused by uncontrolled form state

---

src/CheckTree/test/CheckTreeSpec.tsx
src/Tree/hooks/useFlattenTree.ts

fix: https://github.com/rsuite/rsuite/issues/3973

fix(CheckTree): fix the incorrect check state after loading child nodes through `getChildren`

---

src/RadioGroup/test/RadioGroupSpec.tsx
src/RangeSlider/test/RangeSliderSpec.tsx
src/SelectPicker/test/SelectPickerSpec.tsx

What I did: removed use of getDOMNode
This PR involves the following components: RadioGroup, RangeSlider, SelectPicker

test(RadioGroup, RangeSlider, SelectPicker): refactor using `render` instead of `getDOMNode`

---

docs/less/code-view.less

docs(Dropdown): fix the problem that the example cannot be displayed completely

---

src/locales/hu_HU.ts

Other languages' locales have both 'remove' and 'clear' under the 'common' section, but the Hungarian locale did not. I have corrected this issue, and I kindly request that you review and merge the pull request.

fix(locale): fix missing 'remove' and 'clear' keys in Hungarian locale under the common section

---

src/FormControl/hooks/useField.ts

FormErrorMessage support React Element type
When the error type is ReactElement, the error message cannot be displayed normally.
This is usually encountered when using `react-intl`

feat(FormErrorMessage): support display react element

---

src/CheckTree/styles/index.less
src/Checkbox/styles/mixin.less
src/RadioTile/styles/index.less
src/Rate/styles/index.less
src/Slider/styles/index.less
src/TagPicker/styles/index.less
src/Tree/styles/index.less

Replaced `cursor: not-allowed` with `cursor: @cursor-disabled` across the following components to maintain code consistency
1. Checkbox
2. RadioTile
3. Rate
4. Slider
Also removed it in the following components as the cursor was already disabled.
1. CheckTree
2. TagPicker
3. Tree 
**Note:-** I have replaced it only in the components which i could test, `cursor: not-allowed` is still present in multiple components.

refactor: replaced `cursor: not-allowed` with `cursor: @cursor-disabled`

---

src/Sidebar/test/SidebarSpec.tsx
src/Sidenav/test/SidenavBodySpec.tsx
src/Sidenav/test/SidenavHeaderSpec.tsx
src/Sidenav/test/SidenavSpec.tsx

What I did: removed use of getDOMNode
This PR involves the following components: Sidebar, Sidenav

test(Sidebar, Sidenav): refactor using render instead of getDOMNode

---

src/Timeline/test/TimelineItemSpec.tsx
src/Timeline/test/TimelineSpec.tsx
src/Timeline/test/TimelineStylesSpec.tsx
src/Tooltip/test/TooltipSpec.tsx
src/toaster/test/ToastContainerSpec.tsx

This update involves 3 component changes: Timeline, Toaster, Tooltip

Test: (Timeline, Toaster, Tooltip): Removing the getDOMNode and using render

---

src/Table/Table.tsx
src/Table/test/TableSpec.tsx

fix the following code does not work
```tsx
<Table  locale={{ emptyMessage: 'No data' }} />
```
fix: https://github.com/rsuite/rsuite/issues/4042

fix(Table): fix the problem that the global locale configuration cannot be overridden

---

src/Container/test/ContainerStylesSpec.tsx
src/Input/test/InputStylesSpec.tsx
src/Navbar/test/NavbarStylesSpec.tsx

This update involves 3 component changes: Container, Input, Navbar

Test: (Container, Input, Navbar) removing get dom node

---

docs/pages/components/calendar/fragments/compact.md

fix: https://github.com/rsuite/rsuite/issues/4064

docs(Calendar): fix missing imports for Compact example in CodeSandbox

---

src/Cascader/test/CascaderStylesSpec.tsx
src/CheckPicker/test/CheckPickerStylesSpec.tsx
src/CheckTreePicker/test/CheckTreePickerStylesSpec.tsx
src/DatePicker/test/DatePickerStylesSpec.tsx
src/DateRangePicker/test/DateRangePickerStylesSpec.tsx
src/Form/styles/mixin.less
src/InputPicker/test/InputPickerStylesSpec.tsx
src/MultiCascader/test/MultiCascaderStylesSpec.tsx
src/SelectPicker/styles/index.less
src/SelectPicker/test/SelectPickerStylesSpec.tsx
src/TagPicker/test/TagPickerStylesSpec.tsx
src/Tree/styles/index.less
src/TreePicker/test/TreePickerStylesSpec.tsx
src/internals/Picker/styles/index.less
src/internals/Picker/styles/mixin.less
src/styles/mixins/utilities.less
src/styles/variables.less
test/utils/index.ts
test/utils/testPickers.tsx

This pull request includes several changes to improve the consistency and maintainability of the LESS stylesheets. The most important changes involve the introduction of a new mixin for mapping sizes, replacing deprecated variables, and updating import paths.
* [`src/styles/mixins/utilities.less`](diffhunk://#diff-2d1ecce75e5eca0a0a443e9ac3c610911902c26104d930351ff55bf75f0b03feR168-R192): Added `.map-size` mixin to map size names to suffixes, which helps in standardizing size-related variables.
* [`src/styles/variables.less`](diffhunk://#diff-4280652340dc0c8df16d261fba31010959b4bd152b4a219b487870b5e508142fL87): Removed deprecated variables and replaced them with their new equivalents, such as `@padding-base-vertical` with `@padding-y`, `@padding-large-vertical` with `@padding-y-lg`, and …

refactor: remove deprecated Less variables

---

docs/package-lock.json
docs/package.json

This pull request includes updates to the `lunar-typescript` package version in the project dependencies. The changes involve updating the version from `1.7.5` to `1.7.6` in the `package.json` and `package-lock.json` files.
Dependency updates:
* [`docs/package.json`](diffhunk://#diff-adfa337ce44dc2902621da20152a048dac41878cf3716dfc4cc56d03aa212a56L39-R39): Updated `lunar-typescript` version from `1.7.5` to `1.7.6`.
* [`docs/package-lock.json`](diffhunk://#diff-aced7929d69b779cb242efe99440d62fdf10cc24bb6ac6a958cb0870be3d41a0L32-R32): Updated `lunar-typescript` version from `1.7.5` to `1.7.6` and modified the resolved URL and integrity hash accordingly. [[1]](diffhunk://#diff-aced7929d69b779cb242efe99440d62fdf10cc24bb6ac6a958cb0870be3d41a0L32-R32) …

build(deps): bump lunar-typescript from 1.7.5 to 1.7.6 in docs

---

docs/.browserslistrc
docs/next.config.js
docs/package-lock.json
docs/package.json
gulpfile.js
package-lock.json
package.json
src/Calendar/styles/index.less
src/Form/styles/mixin.less
src/Popover/styles/mixins.less
src/Timeline/styles/index.less
src/Tooltip/styles/mixins.less
src/internals/Picker/styles/index.less
src/styles/mixins/hacks.less
src/styles/mixins/utilities.less

This pull request involves significant changes to the codebase, primarily focusing on removing support for IE11 and Edge-specific hacks, and cleaning up dependencies related to `postcss-custom-properties`.
* [`src/styles/mixins/hacks.less`](diffhunk://#diff-b69a3cdeba649dc598c95bb85b58142f2ebbf1e4f65c02cf222ee2dbf36a95dfL3-L43): Removed all IE11 and Edge-specific mixins, including `ie11-max-width`, `ie11-height`, `ie11-z-index`, `ie11-position`, `ie-box-shadow`, `ie11-edge-width`, and `ie11-edge-direction`. [[1]](diffhunk://#diff-b69a3cdeba649dc598c95bb85b58142f2ebbf1e4f65c02cf222ee2dbf36a95dfL3-L43) [[2]](diffhunk://#diff-b69a3cdeba649dc598c95bb85b58142f2ebbf1e4f65c02cf222ee2dbf36a95dfL74-L105)
* [`src/Calendar/styles/index.less`](diffhunk://#diff-351dc7887990f0c7ad6102c9a848b5fd24e8565de …

refactor(less): remove special handling code for IE11 support

---

package-lock.json
package.json

This pull request updates several dependencies in the `package.json` file to their latest versions.
Dependency updates:
* Updated `@babel/runtime` from `^7.20.1` to `^7.26.0`
* Updated `@babel/cli` from `^7.25.9` to `^7.26.4`
* Updated `@babel/core` from `^7.25.9` to `^7.26.0`
* Updated `@babel/preset-react` from `^7.25.9` to `^7.26.3`

build(deps): bump babel 7.26.*

---

gulpfile.js

This pull request includes a small change to the `gulpfile.js` file. The change updates the script path for `prepublishOnly` to use `_mocha` instead of `mocha`.
* [`gulpfile.js`](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L218-R218): Updated the `prepublishOnly` script path to use `_mocha` instead of `mocha`.

ci(mocha): fix test command error when release version

---

src/toaster/ToastContainer.tsx
src/toaster/render.ts
src/toaster/toaster.tsx

This pull request includes several changes to improve the handling of the `container` element in the toaster component, ensuring better compatibility with server-side rendering (SSR) and null safety.
Changes to improve SSR compatibility and null safety:
* [`src/toaster/ToastContainer.tsx`](diffhunk://#diff-fe85eeb309e268bd345a9aa793dae807020d7fd1472ed1c7351ed3f9f8c12c99R5-R14): Modified the `defaultToasterContainer` to return `null` when `canUseDOM` is false, improving SSR compatibility.
* [`src/toaster/ToastContainer.tsx`](diffhunk://#diff-fe85eeb309e268bd345a9aa793dae807020d7fd1472ed1c7351ed3f9f8c12c99L77-R81): Updated the `GetInstancePropsType` interface to allow `container` to be `HTMLElement | null`, enhancing null safety.
* …

fix(ToastContainer): fix the server-side rendering error

---

docs/pages/components/rate/en-US/index.md
docs/pages/components/rate/fragments/character.md
docs/pages/components/rate/fragments/color.md
docs/pages/components/rate/fragments/custom-character.md
docs/pages/components/rate/fragments/size.md
docs/pages/components/rate/fragments/vertical.md
docs/pages/components/rate/index.tsx
docs/pages/components/rate/zh-CN/index.md
src/Badge/Badge.tsx
src/Rate/Character.tsx
src/Rate/Rate.tsx
src/Rate/styles/index.less
src/Rate/test/RateSpec.tsx
src/internals/utils/colours.ts

- Add support for custom colors (hex and rgb) in Rate component
- Update color handling in colours.ts to preserve RGB format
- Add unit tests for custom colors
- Update documentation with custom color examples and descriptions

feat(Rate): add custom color support

---

docs/pages/components/button-group/fragments/icon-group.md
docs/pages/components/button-group/index.tsx
docs/pages/components/button/en-US/index.md
docs/pages/components/button/fragments/toggleable.md
docs/pages/components/button/index.tsx
docs/pages/components/button/zh-CN/index.md
docs/pages/components/icon-button/en-US/index.md
docs/pages/components/icon-button/fragments/toggleable.md
docs/pages/components/icon-button/index.tsx
docs/pages/components/icon-button/zh-CN/index.md
src/Button/Button.tsx
src/Button/stories/Button.stories.tsx
src/Button/styles/mixin.less
src/Button/test/ButtonSpec.tsx
src/Uploader/UploadTrigger.tsx
src/internals/utils/BrowserDetection.ts

https://rsuite-nextjs-git-feat-button-toggleable-rsuite.vercel.app/components/button/#toggleable
This pull request introduces the `toggleable` feature for buttons and icon buttons, allowing them to switch between active and inactive states. The changes include updates to the documentation, component files, and styles.
* Added the `toggleable` feature description and examples to the English and Chinese documentation for buttons and icon buttons. [[1]](diffhunk://#diff-c0d5bfb5111280b53840a5d5e9595623c8be37bf00be6e6ed6b6a38de901ad5aR61-R66) [[2]](diffhunk://#diff-c0d5bfb5111280b53840a5d5e9595623c8be37bf00be6e6ed6b6a38de901ad5aR98-R106) [[3]](diffhunk://#diff-51e3aac865a5225c761b7e5903316ff219e78c94736d429e8aed160b28563871R55-R60) [[4]](diffhunk://#diff-51e3aac865a5225c761b7e5903316ff219e78c9 …

feat(Button): add support for toggleable and onToggle

---

package-lock.json
package.json

This pull request includes a small change to the `package.json` file. The change updates the version of `gulp-sourcemaps` from `^2.6.4` to `^3.0.0`. 
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L146-R146): Updated `gulp-sourcemaps` to version `^3.0.0` to ensure compatibility with the latest features and improvements.

build(deps): bump gulp-sourcemaps from 2.6.4 to 3.0.0

---

src/styles/typography.less
src/styles/variables.less

~~It’s `-apple-system` with a beginning dash.~~
This does not work in Chrome.
```css
@font-face {
font-family: Apple-System;
src: local(-apple-system), local(BlinkMacSystemFont), local(system-ui);
}
```

Fix font-family

---

src/Tree/hooks/useFlattenTree.ts
src/Tree/test/useFlattenTreeSpec.ts

This pull request includes updates to the `useFlattenTree` hook to add duplicate value checking and corresponding tests to ensure the functionality works correctly. The changes focus on improving error handling and enhancing the robustness of the tree flattening logic.
Enhancements to `useFlattenTree` hook:
* [`src/Tree/hooks/useFlattenTree.ts`](diffhunk://#diff-3b484d2f78e934fd3597bc4e21eea71151a23aa9a39b4f7d4bc3ff10139734e6R70): Added a `seenValues` set to track and detect duplicate values in the tree data. If a duplicate value is found, an error message is logged. [[1]](diffhunk://#diff-3b484d2f78e934fd3597bc4e21eea71151a23aa9a39b4f7d4bc3ff10139734e6R70) [[2]](diffhunk://#diff-3b484d2f78e934fd3597bc4e21eea71151a23aa9a39b4f7d4bc3ff10139734e6L103-R112)
* …

fix(Tree): improve duplicate value detection in Tree data structure 

---

src/InputPicker/InputPicker.tsx
src/InputPicker/test/InputPickerSpec.tsx

This pull request includes changes to the `InputPicker` component and its corresponding tests to improve the handling of the clean button functionality. The most important changes include updating the `handleClean` function to prevent unintended clearing when the delete key is pressed with a search keyword and adding new tests to ensure the correct behavior of the clean button.
Improvements to the `InputPicker` component:
* [`src/InputPicker/InputPicker.tsx`](diffhunk://#diff-6378f82215e0509b44a3a4503c4177c9d87924bea9174d9f343c4cc3b228a498L420-R429): Modified the `handleClean` function to prevent clearing the input value when the delete key is pressed while there is a search keyword.
Enhancements to the test coverage:
* [`src/InputPicker/test/InputPickerSpec.tsx`](diffhunk://#diff-c684f73d …

fix(InputPicker): do not trigger clean when clicking delete with search keyword

---

src/Form/test/FormValidationSpec.tsx
src/FormControl/test/utilsSpec.ts
src/FormControl/utils.ts

fix: https://github.com/rsuite/rsuite/issues/4120
- Fixed nameToPath function to handle multiple nested levels
- Added test cases for deeply nested object validation
fix: https://github.com/rsuite/rsuite/issues/4123
- Fixed nameToPath function to correctly handle array paths
- Added unit tests for nameToPath function
- Added test case for deeply nested array validation

fix(form): support deeply nested object validation

---

docs/pages/components/date-range-picker/en-US/index.md
docs/pages/components/date-range-picker/zh-CN/index.md
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.tsx

This pull request introduces several enhancements and bug fixes for the `DateRangePicker` component. The key changes include adding a new `renderCell` prop for custom calendar cell rendering, updating documentation, and improving error handling in tests.
* [`src/DateRangePicker/DateRangePicker.tsx`](diffhunk://#diff-7f89a1ffee8cf9975c367c9826b37a1f35d7ca45e6b0b334386320badc61dc84R255-R261): Added `renderCell` prop to allow custom rendering of calendar cells. This new prop is documented as being available from version 5.77.0. [[1]](diffhunk://#diff-7f89a1ffee8cf9975c367c9826b37a1f35d7ca45e6b0b334386320badc61dc84R255-R261) [[2]](diffhunk://#diff-7f89a1ffee8cf9975c367c9826b37a1f35d7ca45e6b0b334386320badc61dc84R355) [[3]](diffhunk://#diff-7f89a1ffee8cf9975c367c9826b37a1f35d7ca45e6b0b334386320b …

feat(DateRangePicker): support custom render calendar cell content

---

docs/pages/_common/types/placement-corners.md
src/Badge/styles/index.less
src/Badge/test/BadgeStylesSpec.tsx

This pull request includes updates to the `Badge` component's styles and tests to ensure proper rendering and CSS variable usage. The most important changes include modifying the display property in the styles and adding new test cases to verify the correct CSS variables and display properties.
* [`src/Badge/styles/index.less`](diffhunk://#diff-9001c4db5dfddb8eb65766038835a1af9044d33cf7d686c49dc650f310eab6cdL21-R21): Changed the display property from `flex` to `inline-flex` for better alignment and rendering of badge content.
* [`src/Badge/test/BadgeStylesSpec.tsx`](diffhunk://#diff-5a38bbad8c3479f6ec2d2d165912c2f5ff5420571708ba98a39001494e2ca46fR49-R71): Added new test cases to verify the correct CSS variables (`--rs-badge-offset-x`, `--rs-badge-offset-y`, `--rs-badge-translate`) and to …

test(Badge): add style test cases for positioning and independent display

---

src/DatePicker/DatePicker.tsx
src/DateRangePicker/DateRangePicker.tsx
test/utils/testStandardProps.ts

This pull request includes several changes to improve the handling of `className` properties in the `DatePicker` and `DateRangePicker` components, as well as enhancing the test coverage for class name properties.
fix: https://github.com/rsuite/rsuite/issues/4131

fix: prevent duplicate className in DatePicker and DateRangePicker components

---

docs/pages/components/date-range-picker/fragments/custom-shortcut-options.md
src/DatePicker/types.ts
src/DateRangePicker/DateRangePicker.tsx
src/DateRangePicker/test/DateRangePickerSpec.tsx
src/DateRangePicker/types.ts

fix: https://github.com/rsuite/rsuite/issues/4138
```tsx
<DateRangePicker
ranges={[
{
label: 'Clear',
value: null
}
]}
/>
```
This pull request includes changes to enhance the handling of null values in the `DateRangePicker` component and its associated types.

fix(DateRangePicker): allow ranges option value to be null

---

docs/pages/components/dropdown/fragments/disabled.md
src/Dropdown/styles/index.less
src/Dropdown/test/DropdownMenuSpec.tsx
src/internals/Menu/Menubar.tsx

fix: https://github.com/rsuite/rsuite/issues/4133
- Added test case for disabled item focus behavior
- Updated disabled item styles
- Modified Menubar focus handling for disabled items
- Updated dropdown documentation examples

fix(Dropdown): prevent focus moving to first item when focusing on disabled item

---

src/Cascader/test/Cascader.test.tsx
src/CheckPicker/CheckPicker.tsx
src/CheckPicker/test/CheckPicker.test.tsx
src/InputPicker/InputPicker.tsx
src/InputPicker/test/InputPicker.test.tsx
src/MultiCascader/MultiCascader.tsx
src/MultiCascader/test/MultiCascader.test.tsx
src/SelectPicker/SelectPicker.tsx
src/SelectPicker/index.tsx
src/SelectPicker/test/SelectPicker.test.tsx
src/TagPicker/TagPicker.tsx
src/TagPicker/test/TagPicker.test.tsx

This pull request introduces several changes across multiple files to enhance the functionality of various picker components by adding support for custom rendering of selected items. The changes include the addition of `renderValue` properties, type adjustments, and test updates.
* [`src/CheckPicker/CheckPicker.tsx`](diffhunk://#diff-24415b62298f3c3b22e4dd6a7c6043b14459e23907b0086a567f4088fea97900L39-R57): Added `renderValue` property to `CheckPickerProps` for custom rendering of selected items. Adjusted types and updated the `handleSelect` and `handleItemSelect` methods to use generic `ItemDataType<T>`. [[1]](diffhunk://#diff-24415b62298f3c3b22e4dd6a7c6043b14459e23907b0086a567f4088fea97900L39-R57) [[2]](diffhunk://#diff-24415b62298f3c3b22e4dd6a7c6043b14459e23907b0086a567f4088fea97900L213- …

fix(pickers): improve pickers `renderValue` property type definition

---

src/Image/test/ImageSpec.tsx

Noticed that 1 test case in Image was failing.

fix: 1 test in ImageSpec

---

src/Uploader/UploadTrigger.tsx
src/Uploader/Uploader.tsx
src/Uploader/test/UploaderSpec.tsx

fix: https://github.com/rsuite/rsuite/issues/4174
- Change children prop type from ReactNode to ReactElement in Uploader and UploadTrigger
- Refactor event handler assignment in UploadTrigger using object spread
- Preserve custom className when cloning child element
- Add test case for custom button className

fix(Uploader): refine children prop type and improve class handling

---

src/DatePicker/test/DatePickerStylesSpec.tsx
src/internals/Picker/styles/index.less

This pull request includes changes to the `DatePicker` component to enhance its styling and ensure consistency across different sizes. The most important changes are as follows:
* [`src/DatePicker/test/DatePickerStylesSpec.tsx`](diffhunk://#diff-4e0bdaac42a7fd9426cfa651c3a83cfb828c5abbbc07f0eb8eea029252ea0beeR25-R38): Added a new test to verify that the label padding updates correctly based on the size of the `DatePicker` component.
* [`src/internals/Picker/styles/index.less`](diffhunk://#diff-39e60be854f6f35595816822070452a633398f2f4e4923a5c32ace4bcd07346bL95-R97): Modified the padding style for the `DatePicker` label to use a calculated value based on existing CSS variables, ensuring consistent spacing.

fix(DatePicker): adjust label padding based on size

---

README.md
README_zh.md

This pull request includes updates to the `README.md` and `README_zh.md` files to modify the GitHub Actions badge references. The changes ensure that the badges correctly link to the Node.js CI workflow.

docs: fix nodejs-ci badge link

---

docs/pages/components/toaster/en-US/index.md
docs/pages/components/toaster/zh-CN/index.md

This pull request includes updates to the documentation for the `Toaster` component in both English and Chinese. The changes provide additional guidance on how to use the `useToaster` hook within a specified container using a `CustomProvider` component.

docs: add guidance for usage issues with `useToaster`

---

package-lock.json
package.json
src/Form/hooks/useSchemaModel.ts
src/Form/test/FormValidationSpec.tsx
src/Form/test/constructFlatSchemaSpec.ts
src/Form/utils/constructFlatSchema.ts

Reproduction: https://codesandbox.io/p/devbox/nifty-breeze-5r2sfn?workspaceId=ws_QeEyaqyPtYWhjP5TTM8Yhh
When using a nested array and passing different types of elements within array
After this change

fix(form): support explicit type of array type when use rule of formControl

---

docs/pages/components/slider/en-US/index.md
docs/pages/components/slider/fragments/keep-tooltip-open.md
docs/pages/components/slider/zh-CN/index.md
src/Slider/Handle.tsx
src/Slider/styles/index.less

This pull request includes several changes to the slider component documentation and codebase, focusing on adding a new feature to keep the tooltip open and simplifying the tooltip placement styling.
* Added a new section for "Keep tooltip open" in both English and Chinese documentation files (`docs/pages/components/slider/en-US/index.md`, `docs/pages/components/slider/zh-CN/index.md`). [[1]](diffhunk://#diff-b3359ec012454c753f8eaede4385a6134bb7ae80edcaf6c8c2b166f8b00ac47bL48-R55) [[2]](diffhunk://#diff-956b780a6537411eebbd61366524971225fd37bee038bfb58cffbf8ed3a585b0L48-R55)
* Included the `keepTooltipOpen` property in the slider component's property tables in both English and Chinese documentation files (`docs/pages/components/slider/en-US/index.md`, …

fix(Slider): fix issue where arrow in Tooltip is not displayed

---

docs/components/overview/CategorizedList.tsx
docs/components/overview/ComponentThumbnail.tsx
docs/components/thumbnails/buttons.tsx
docs/components/thumbnails/dataDisplay.tsx
docs/components/thumbnails/dataEntry.tsx
docs/components/thumbnails/dataGrid.tsx
docs/components/thumbnails/dataPickers.tsx
docs/components/thumbnails/dateTime.tsx
docs/components/thumbnails/default.tsx
docs/components/thumbnails/disclosure.tsx
docs/components/thumbnails/form.tsx
docs/components/thumbnails/index.ts
docs/components/thumbnails/layout.tsx
docs/components/thumbnails/media.tsx
docs/components/thumbnails/misc.tsx
docs/components/thumbnails/navigation.tsx
docs/components/thumbnails/overlays.tsx
docs/components/thumbnails/status.tsx
docs/components/thumbnails/styles.less
docs/components/thumbnails/typography.tsx
docs/less/index.less
docs/pages/components/frame/examples/center.tsx
docs/pages/components/frame/examples/horizontal.tsx
docs/pages/components/overview/styles.less

This pull request introduces a significant update to the component overview section by adding thumbnail images for various components and reorganizing the `CategorizedList` to include these thumbnails. The changes span multiple files and focus on enhancing the visual representation and organization of component data.
https://rsuite-nextjs-git-docs-add-component-thumbnails-rsuite.vercel.app/components/overview/

docs(thumbnails): add component thumbnails for all components

---

docs/pages/components/rate/zh-CN/index.md

https://rsuitejs.com/zh/components/rate/

docs(Rate): fix display error in Props documentation table

---

docs/pages/components/divider/en-US/index.md
docs/pages/components/divider/fragments/with-label.md
docs/pages/components/divider/zh-CN/index.md
docs/pages/components/rate/fragments/advanced-rating.md
docs/pages/components/rate/fragments/character.md
docs/pages/components/rate/fragments/color.md
docs/pages/components/rate/fragments/custom-character.md
docs/pages/components/rate/fragments/size.md
src/Divider/Divider.tsx
src/Divider/styles/index.less
src/Divider/test/DividerSpec.tsx

This pull request updates the `Divider` component to use the term "labelPlacement" instead of "labelPosition" across various files and documentation. The changes ensure consistency and clarity in the API.

refactor(divider): rename labelPosition to labelPlacement for consistency

---

package-lock.json
package.json

This pull request includes a minor version update to the `schema-typed` dependency in the `package.json` file. The version has been updated from `^2.4.1` to `^2.4.2` to ensure compatibility with the latest features or fixes.

build(deps): bump schema-typed from 2.4.1 to 2.4.2

---

src/Message/styles/index.less

This pull request updates the `src/Message/styles/index.less` file to improve the flexibility and maintainability of spacing and padding by using CSS variables consistently. It replaces hardcoded values with calculations based on the `--rs-spacing` variable and introduces a new `--rs-message-spacing` variable for managing gaps between elements.
* Updated `--rs-message-padding` to use a calculation based on `--rs-spacing` for consistency and easier scalability.
* Introduced a new `--rs-message-spacing` variable to standardize gaps between elements and applied it to the `gap` property for message containers. [[1]](diffhunk://#diff-df24926ca5248a419c0138994fe566accd26195dece1055a9dc4b7f721c141c3L16-R20) [[2]](diffhunk://#diff-df24926ca5248a419c0138994fe566accd26195dece1055a9dc4b7f721c141c3R54 …

fix(message): update spacing to use css variables

---

docs/pages/components/modal/index.tsx
src/Modal/ModalHeader.tsx
src/internals/CloseButton/styles/index.less
src/internals/Picker/styles/index.less
src/styles/color-modes/dark.less
src/styles/color-modes/high-contrast.less
src/styles/color-modes/light.less

This pull request refactors the `CloseButton` component and its associated styles to simplify its implementation and improve maintainability. The changes include removing unnecessary conditional logic, cleaning up unused styles, and adjusting hover behavior for consistency.
* Removed the `isDrawer` conditional logic in `ModalHeader` and updated the `CloseButton` to always use `IconButton` for consistency. (`src/Modal/ModalHeader.tsx`)
* Removed hover and focus styles for the `CloseButton` in `src/internals/CloseButton/styles/index.less`, as they are no longer needed.
* Deleted the `--rs-close-button-hover-color` variable from all color mode files (`dark.less`, `high-contrast.less`, `light.less`) since it is no longer used. [[1]](diffhunk://#diff-e4cdb20a74189b40fc05ef2ec0b326250b36f2509553 …

fix(CloseButton): standardize close button styles

---

docs/package-lock.json
docs/package.json
package-lock.json
package.json

This pull request updates the version of the `@rsuite/icons` dependency from `^1.3.0` to `^1.3.2` in two files to ensure consistency and take advantage of the latest features or bug fixes provided by the updated version.
Dependency updates:
* [`docs/package.json`](diffhunk://#diff-adfa337ce44dc2902621da20152a048dac41878cf3716dfc4cc56d03aa212a56L27-R27): Updated `@rsuite/icons` from `^1.3.0` to `^1.3.2`.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L62-R62): Updated `@rsuite/icons` from `^1.3.0` to `^1.3.2`.

build(deps): bump @rsuite/icons from 1.3.0 to 1.3.2

---

src/DateInput/test/testUtils.tsx
src/DateInput/test/types/TestKeyPressProps.ts
src/DateRangeInput/DateRangeInput.tsx
src/DateRangeInput/test/DateRangeInputSpec.tsx

Fixes #4183 
When pressing function keys (F1–F12) inside the DateRangePicker input, it was causing NaN to appear.
A check was added to detect and ignore function keys to avoid unintended input.

fix(DateRangeInput): ignore function keys (F1–F12) to prevent NaN input

---

src/DateInput/DateInput.tsx
src/DateInput/test/DateInputSpec.tsx
src/DateRangeInput/test/DateRangeInputSpec.tsx

Related to #4263 
When pressing function keys (F1–F12) inside the DateInput, it was causing NaN to appear.
A check was added to detect and ignore function keys to avoid unintended input.

fix(DateInput): ignore function keys (F1–F12) to prevent NaN input

---

src/InlineEdit/test/InlineEditSpec.tsx
src/InlineEdit/useEditState.ts

This PR fixes an issue in the InlineEdit component where the current input value was incorrectly preserved after triggering the onCancel callback.
Previously, when onCancel was called, the value that had been modified in the input field was stored and reused, instead of reverting to the original unedited value.
The component now correctly resets the input to its initial value when canceling an edit.
Related issue: #4274 
https://github.com/user-attachments/assets/303abcea-0db7-4b97-acf3-ae70ebae4072

fix(InlineEdit): reset input value to original on cancel instead of preserving edited value

---

docs/pages/components/password-input/en-US/index.md
docs/pages/components/password-input/zh-CN/index.md

This pull request reorganizes the documentation for the password input component by moving the `icons.md` include to a more logical position in both the English and Chinese documentation files.

docs(PasswordInput): fix incorrect order of examples

---

src/locales/es_ES.ts

The locale code in `src/locales/es_ES.ts` was incorrectly set to `es-AR` (Spanish - Argentina). This commit corrects the locale code to `es-ES` (Spanish - Spain).

fix: correct locale code for Spanish (Spain)

---

src/toaster/ToastContainer.tsx

This pull request updates the `useMessages` function in `src/toaster/ToastContainer.tsx` to ensure state updates are based on the previous state, improving reliability when handling asynchronous updates.
State management improvements:
* Updated the `setMessages` call to use a functional state update in the `setTimeout` for clearing all messages. This ensures the state update is based on the most recent state.
* Updated the `setMessages` call to use a functional state update when filtering visible messages. This prevents potential issues caused by stale state references.

fix(toaster): fix issue where delayed closing affects state

---

docs/pages/components/frame/examples/center.tsx

This pull request introduces a small improvement to the `Form.Control` component in the `docs/pages/components/frame/examples/center.tsx` file. The change disables autocomplete for the email input field.
* [`docs/pages/components/frame/examples/center.tsx`](diffhunk://#diff-137329b02f06c3c4c9fd3cd9473f00097564c1a77e608707b8c444cb8eb48c4cL60-R60): Added the `autoComplete="off"` attribute to the email input field to prevent browsers from autofilling the field.

docs: disable auto-focus and autocomplete on email input

---

docs/pages/components/icon-button/en-US/index.md
docs/pages/components/icon-button/zh-CN/index.md
src/IconButton/IconButton.tsx
src/IconButton/styles/index.scss
src/IconButton/test/IconButton.spec.tsx

This pull request introduces enhancements and refactoring to the `IconButton` component, including updates to its API, styling, and test coverage. The most significant changes involve adding new placement options, replacing class-based styling with data attributes, and improving test coverage for the component's behavior.
* Added new placement options (`start` and `end`) to the `placement` prop in `IconButtonProps` and set the default placement to `start`. (`src/IconButton/IconButton.tsx`, [[1]](diffhunk://#diff-d4c771526353735c71f0e18256a8228e97af18f3f47925ddbebbd856f94e8faaL15-R15) [[2]](diffhunk://#diff-d4c771526353735c71f0e18256a8228e97af18f3f47925ddbebbd856f94e8faaL25-R45)
* Replaced class-based selectors (e.g., `.rs-btn-icon-circle`) with attribute-based selectors (e.g., …

refactor(IconButton): use data-shape for circle styling instead of class name

---

docs/pages/components/stat/en-US/index.md
docs/pages/components/stat/fragments/trend.md
docs/pages/components/stat/zh-CN/index.md
src/Stat/StatTrend.tsx
src/Stat/styles/index.less
src/Stat/test/StatTrendSpec.tsx

Added an equal indicator to the StatTrend component so that flat trends can also be represented. This new trend indicator displays an = icon and uses the primary color scheme.

feat(Stat/StatTrend): add 'equal' trend indicator

---

package-lock.json
package.json

This pull request includes a minor version update to the `rsuite-table` dependency in the `package.json` file. The version was incremented from `^5.19.1` to `^5.19.2` to ensure compatibility with the latest features or fixes.

build(deps): bump rsuite-table from 5.19.1 to 5.19.2

---

docs/pages/components/progress/en-US/index.md
docs/pages/components/progress/zh-CN/index.md
examples/with-flow/flow-typed/npm/rsuite_v3.x.x.js
src/Progress/ProgressCircle.tsx

Fixed Issue #4352: Progress.Circle properties do not include width - it's use is required but results in typescript error TS2322

fix: Progress.Circle properties do not include width (#4352)

---

docs/package-lock.json
docs/package.json
gulpfile.js
package.json
scripts/validate-builds.js

Replaced the prepublish build validation script to use a new Node.js script (`scripts/validate-builds.js`) that runs Vitest instead of Mocha for post-build validation. The relevant command in `gulpfile.js` was updated accordingly. [[1]](diffhunk://#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L91-R91) [[2]](diffhunk://#diff-50c9abb520060a8c4c0475963dcf56263ff1c2d7a9af265b57a016474792d862R1-R25)

fix(build): update prepublishOnly to use TypeScript validation test

---

src/styles/_css-reset.scss

This pull request makes minor adjustments to the CSS reset styles, specifically affecting the `h1-6` and `p` elements.

fix(css-reset): remove default margin from headings and paragraph styles

---

src/Textarea/Textarea.tsx
src/Textarea/test/Textarea.test.tsx

This pull request introduces support for a new `onChange` prop in the `Textarea` component, allowing consumers to access both the new value and the original change event when handling input changes.

fix(Textarea): improve onChange type definition

---

docs/package.json

This pull request updates the required Node.js version for the documentation package to ensure compatibility with the latest runtime.
Dependency update:
* [`docs/package.json`](diffhunk://#diff-adfa337ce44dc2902621da20152a048dac41878cf3716dfc4cc56d03aa212a56L89-R89): Changed the Node.js engine requirement from `^18.17.0` to `22.x` to support newer Node.js features and improve consistency across environments.

chore: update Node.js version to 22.x in engines field
